# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_api.ipynb.

# %% ../nbs/07_api.ipynb #b0f50ba2adb2
from __future__ import annotations

import numpy as np
from fastcore.all import Path, patch

from .core import database, rerank_hits
from .data import dir2chunks, pkg2chunks
from .tree import DOC_EXTS
from .utils import static_retrieval_embedder, doc_encoder, query_encoder

# %% auto #0
__all__ = ['DTYPE', 'HIT_COLS', 'RERANK_FANOUT', 'Index']

# %% ../nbs/07_api.ipynb #ce3d9743bc59
DTYPE = np.float16   # what a store holds by default. Hand it float32 and every distance is 0

# Columns a hit carries. `metadata` is populated for code chunks, the rest for document chunks.
HIT_COLS = ['content', 'metadata', 'node_id', 'page', 'heading', 'doc_id']

RERANK_FANOUT = 30   # candidates merged before the cross-encoder sees them; matches `evals.score`

# %% ../nbs/07_api.ipynb #9e17018e0b48
class Index:
    '''A corpus you can search: ingest files, code or text, then query with a string.

    The defaults are not a matter of taste — they are the configuration `evals/` measures as best
    or tied-best across three genres. Everything is overridable, and `self.db` is the plain
    `database()` underneath.
    '''
    def __init__(self,
                 path=':memory:',     # sqlite file; omit for in-memory
                 encoder=None,        # anything `doc_encoder` takes (default: static potion-retrieval-32M)
                 name:str='store',    # chunk table, if you want several corpora in one file
                 ann:bool=True,       # maintain an HNSW index for the vector leg
                 ):
        self.path, self.name, self.ann = str(path), name, ann
        self.db = database(path)
        self.encoder = static_retrieval_embedder() if encoder is None else encoder
        self._doc, self._qry = doc_encoder(self.encoder), query_encoder(self.encoder)
        self.t = self.db.get_tree(name, ann=ann)
        self.store = self.t.store

    def emb(self, texts) -> np.ndarray:
        'Document vectors, cast to the dtype the store actually holds.'
        return np.asarray(self._doc(list(texts)), dtype=DTYPE)

    def qemb(self, q:str) -> bytes:
        'One query vector, as the bytes the low-level `search` wants.'
        return np.asarray(self._qry([q]), dtype=DTYPE)[0].tobytes()

    def __len__(self): return self.db.q(f'select count(*) as n from [{self.name}]')[0]['n']

    @property
    def docs(self) -> list:
        'One row per ingested document — title, source, kind, pages.'
        return list(self.t.docs())

    def __repr__(self):
        return f'Index(path={self.path!r}, chunks={len(self):,}, docs={len(self.docs)})'

# %% ../nbs/07_api.ipynb #4746ebee0218
def _texts(src) -> list: return [src] if isinstance(src, str) else list(src)

def _title(t:str, i:int, n:int=60) -> str:
    'First non-empty line, trimmed — so `toc()` over raw strings still reads like a listing.'
    ln = next((l.strip() for l in (t or '').splitlines() if l.strip()), '')
    return ln[:n] or f'text-{i+1}'

@patch
def add(self:Index,
        src,                    # directory, file path, string, list of strings, or {title: text}
        types:str=DOC_EXTS,     # extensions to pick up when `src` is a directory
        **kw                    # forwarded to add_dir / add_file / add_doc
        ) -> int:
    'Ingest documents or text. Returns the number of chunks the store gained.'
    before = len(self)
    if isinstance(src, (str, Path)) and Path(src).exists():
        p = Path(src)
        if p.is_dir(): self.db.add_dir(str(p), types=types, store=self.name, emb_fn=self.emb, **kw)
        else:          self.db.add_file(str(p), store=self.name, emb_fn=self.emb, **kw)
    else:
        items = src if isinstance(src, dict) else {_title(t, i): t for i, t in enumerate(_texts(src))}
        for title, txt in items.items():
            self.db.add_doc(txt, title=title, store=self.name, emb_fn=self.emb, **kw)
    return len(self) - before

# %% ../nbs/07_api.ipynb #a70c097d20dc
@patch
def add_code(self:Index,
             src,       # a source directory, or an installed package name
             **kw       # forwarded to dir2chunks / pkg2chunks
             ) -> int:
    'Ingest source code through the AST path — top-level functions, classes and assignments.'
    chunks = dir2chunks(str(src), **kw) if Path(src).exists() else pkg2chunks(str(src), **kw)
    rows = [dict(content=c['content'], metadata=str(c.get('metadata') or {}))
            for c in chunks if (c.get('content') or '').strip()]
    if not rows: return 0
    for r, v in zip(rows, self.emb([r['content'] for r in rows])):
        r['embedding'] = np.asarray(v, dtype=DTYPE).tobytes()
    self.store.insert_all(rows, upsert=True, hash_id='id', hash_id_columns=['content'])
    if self.ann: self.store.rebuild_index()
    return len(rows)

# %% ../nbs/07_api.ipynb #3a413a326270
@patch
def search(self:Index,
           q:str,                # query string
           limit:int=10,         # hits to return
           rerank:bool=False,    # reorder with a flashrank cross-encoder (see above)
           **kw                  # forwarded to Database.search
           ) -> list:
    'Hybrid keyword + vector search over the chunk store.'
    if not (q or '').strip(): return []
    qv = self.qemb(q)
    cols = list(dict.fromkeys(HIT_COLS + (kw.pop('columns', None) or [])))
    n = max(limit, RERANK_FANOUT) if rerank else limit
    hits = self.db.search(q, qv, columns=cols, table_name=self.name, limit=n,
                          dtype=DTYPE, ann=self.ann, **kw) or []
    return rerank_hits(q, hits, None, limit) if rerank else hits

# %% ../nbs/07_api.ipynb #4a3bded13bfd
@patch
def toc(self:Index, doc:str=None, **kw) -> list:
    'The corpus as a nested tree of titles and page ranges. Touches no embeddings.'
    return self.db.toc(doc, store=self.name, **kw)

@patch
def sections(self:Index, q:str, limit:int=5, **kw) -> list:
    'Ranked sections rather than chunks, each with snippets and a `read` handle.'
    return self.db.sections(q, self.qemb(q), limit=limit, store=self.name, **kw)

@patch
def read(self:Index, node_id:str, **kw) -> dict:
    'One whole section, reassembled — the unit to hand a model instead of fragments.'
    return self.db.read(node_id, store=self.name, **kw)

@patch
def context(self:Index, q:str, **kw) -> dict:
    'Operative sections plus what they connect to, composed for a prompt.'
    return self.db.context(q, self.qemb(q), store=self.name, **kw)
