# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_cli.ipynb.

# %% auto #0
__all__ = ['CMDS', 'install', 'main']

# %% ../nbs/04_cli.ipynb #ff25e45b7b21ce1a
import sys
from fastcore.script import call_parse
from .data import mv_skill_md

# %% ../nbs/04_cli.ipynb #d4e5f6a7
@call_parse
def install(
    dir: str = None  # target repo root (default: cwd)
):
    'Install SKILL.md to .agents/, .claude/, .Codex/ skill directories.'
    mv_skill_md(dry_run=False, dir=dir)

CMDS = {'install': install}

def main():
    if len(sys.argv) < 2 or sys.argv[1] not in CMDS:
        print('Usage: litesearch <command>')
        print('Commands: ' + ', '.join(CMDS))
        sys.exit(0)
        return
    cmd = sys.argv.pop(1)
    CMDS[cmd]()
