# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_core.ipynb.

# %% auto #0
__all__ = ['BUSY_TIMEOUT_MS', 'embed_chunk', 'busy_window', 'write_txn', 'process_content', 'rrf_merge', 'database',
           'rerank_hits']

# %% ../nbs/01_core.ipynb #508322702d73b25a
from fastcore.all import Path, Generator, patch, merge, ifnone, first, L, filter_keys, not_, in_, parallel as fcp
from fastlite import Database
from apswutils.db import Table
from apswutils.utils import cursor_row2dict, hash_record
from apsw.fts5 import register_tokenizers, map_tokenizers
from contextlib import contextmanager, nullcontext
import apsw, apsw.bestpractice, threading
import numpy as np, warnings
from .data import pre
BUSY_TIMEOUT_MS = 30_000   # lock wait during a busy_window; apsw's stock default is 100ms

# %% ../nbs/01_core.ipynb #72086eb6ff361455
_dtype_suffixes = {np.int8: 'i8', np.float16: 'f16', np.float64: 'f64', np.float32: 'f32'}
def _dtype_suffix(dtype=np.float16): return _dtype_suffixes.get(dtype, 'f32')
_usearch_metric = {'cosine':'cos', 'inner':'ip', 'sqeuclidean':'l2sq', 'divergence':'divergence'}
_np_dtype = {'i8':np.int8, 'f16':np.float16, 'f32':np.float32, 'f64':np.float64}

def _in(col, vals): return f'{col} in ({",".join(map(repr, vals))})'  # SQL IN clause; callers guard against empty vals

# `porter unicode61` (the FTS5 default) splits on `_` and then stems the pieces, so `fts_search`
# indexes as `ft`+`search` and a search for it matches almost anything. apsw's UAX#29 tokenizer
# treats `_` as a word joiner, so identifiers survive; porter still stems ordinary prose.
_FTS_TOKENIZE = 'porter simplify casefold 1 unicodewords'

def _slug(content):
    "Content hash matching a hash-id store's `id` (hash over the content column)."
    return hash_record({'content': content}) if content else None

def embed_chunk(chunk,      # iterable of dicts with a 'content' key
                emb_fn,     # callable: list[str] -> list of vectors (np arrays)
                **kw):
    'Embed each chunk\'s content via emb_fn and attach `embedding` bytes. Skips blank content.'
    c = L(chunk).filter(lambda b: b.get('content') and b['content'].strip())
    if not c: return []
    for e,b in zip(emb_fn(list(c.itemgot('content')), **kw), c): b['embedding'] = np.asarray(e).tobytes()
    return list(c)

_busy_lock, _busy_depth, _busy_saved = threading.Lock(), 0, None

@contextmanager
def busy_window(busy_ms=BUSY_TIMEOUT_MS, *dbs):
    '''Widen apsw's busy timeout for the duration of the block, then restore it.
    Refcounted: overlapping windows share one widening and only the last exit restores, so
    concurrent ingests can't race the save/restore and strand the widened value forever.'''
    global _busy_depth, _busy_saved
    bp = apsw.bestpractice.connection_busy_timeout
    with _busy_lock:
        if not _busy_depth: _busy_saved = bp.__defaults__
        _busy_depth += 1
        bp.__defaults__ = (busy_ms,)
    conns = [d.conn for d in dbs]
    prev = [list(c.execute('PRAGMA busy_timeout'))[0][0] for c in conns]
    for c in conns: c.set_busy_timeout(busy_ms)
    try: yield
    finally:
        for c,p in zip(conns,prev): c.set_busy_timeout(p)
        with _busy_lock:
            _busy_depth -= 1
            if not _busy_depth: bp.__defaults__ = _busy_saved

@contextmanager
def write_txn(db):
    'BEGIN IMMEDIATE txn: takes the write lock upfront so the busy handler waits instead of failing. No-op inside an open txn.'
    c = db.conn
    if c.in_transaction: yield; return
    c.execute('BEGIN IMMEDIATE')
    try: yield
    except Exception: c.execute('ROLLBACK'); raise
    else: c.execute('COMMIT')

def process_content(store,          # target Table (hash-id store)
                    content,        # iterable of chunk dicts
                    embed=True,     # embed content before upsert
                    emb_fn=None,    # embedder, required when embed=True
                    hash_id_columns=('content',),  # columns the row id is hashed over; add 'node_id' to keep identical text in different sections distinct
                    parallel=False, # safe for concurrent writers: widened busy timeout + chunked BEGIN IMMEDIATE txns
                    chunk=5_000,    # rows per transaction when parallel=True
                    **kw):          # forwarded to emb_fn
    'Embed chunks (optional) and upsert into a hash-id store. No-op on empty content.'
    content = list(content or [])
    if embed:
        assert emb_fn, 'emb_fn is required when embed=True'
        content = embed_chunk(content, emb_fn, **kw)
    if not content: return
    _ins = lambda rows: store.insert_all(rows, upsert=True, hash_id='id', hash_id_columns=list(hash_id_columns))
    if not parallel: return _ins(content)
    with busy_window(BUSY_TIMEOUT_MS, store.db):
        for i in range(0, len(content), chunk):
            with write_txn(store.db): _ins(content[i:i+chunk])
    return store

# %% ../nbs/01_core.ipynb #eb6da9000ce71a23
@patch
def get_store(self:Database,        # database connection
            name:str='store',       # table name
            hash:bool=False,        # whether to create hash index on content
            ann:bool=False,         # also register a usearch HNSW index (sidecar) for this store
            ndim:int=None,          # embedding dims for the ANN index (inferred on first sync if None)
            metric:str='cosine',    # ANN distance metric (cosine,inner,sqeuclidean,divergence)
            dtype=np.float16,       # ANN vector dtype
            connectivity:int=None,  # HNSW connectivity (usearch default if None)
            expansion_add:int=None, # HNSW add expansion
            expansion_search:int=None, # HNSW search expansion
            index_path:str=None,    # sidecar path (defaults to <db>.<name>.usearch; None db -> in-memory)
            tokenize:str=None,      # FTS5 tokenizer (default: apsw unicodewords chain, else 'porter')
            **kw,                   # additional args to pass to fastlite create
):
    "creates a content/embedding/metadata table with FTS5. Set ann=True to also maintain a usearch HNSW index."
    cols = dict(content=str, embedding=bytes, metadata=str, uploaded_at=float,defaults=dict(uploaded_at='CURRENT_TIMESTAMP'),pk='id')
    if hash: cols.update(dict(hash_id='id',hash_id_columns=['content']))
    else: cols.update(dict(id=int, not_null=['content']))
    _content = self.t[name].create(**cols,if_not_exists=True, **kw)
    tok = tokenize or (_FTS_TOKENIZE if getattr(self, '_fts_tokenizers', False) else 'porter')
    if not _content.detect_fts(): _content.enable_fts(['content','metadata'], create_triggers=True, tokenize=tok, replace=True)
    if ann: self._register_ann(name, ndim, metric, dtype, connectivity, expansion_add, expansion_search, index_path)
    return _content

# %% ../nbs/01_core.ipynb #803a2e5497883d62
@patch
def _register_ann(self:Database, name, ndim=None, metric='cosine', dtype=np.float16,
                  connectivity=None, expansion_add=None, expansion_search=None, index_path=None):
    'Create the usearch_indices registry (if needed) and record this ANN store. Idempotent.'
    self.t.usearch_indices.create(name=str, path=str, ndim=int, metric=str, dtype=str, connectivity=int,
        expansion_add=int, expansion_search=int, created_at=float, pk='name', if_not_exists=True,
        defaults=dict(created_at='CURRENT_TIMESTAMP'))
    fn = self.conn.filename
    ipath = index_path or (f'{fn}.{name}.usearch' if fn else None)
    self.t.usearch_indices.insert(dict(name=name, path=ipath, ndim=ndim, metric=metric, dtype=_dtype_suffix(dtype),
        connectivity=connectivity, expansion_add=expansion_add, expansion_search=expansion_search), ignore=True)

@patch(as_prop=True)
def ann_indices(self:Database):
    'Per-connection cache of loaded usearch Index objects, keyed by store name.'
    if not hasattr(self, '_ann_indices'): self._ann_indices = {}
    return self._ann_indices

@patch
def _ann_meta(self:Database, name):
    'Registry row for an ANN store, or None if not registered.'
    return first(self.t.usearch_indices(where=f'name={name!r}')) if 'usearch_indices' in self.t else None

@patch
def get_index(self:Database,        # database connection
              name:str='ann_store', # ANN store name
              load:bool=True):      # load the sidecar file if present
    'Build (and cache) the usearch Index for an ANN store. Requires a known ndim.'
    if name in self.ann_indices: return self.ann_indices[name]
    from usearch.index import Index
    m = self._ann_meta(name)
    assert m, f'{name!r} is not a registered ANN store'
    assert m['ndim'], f'{name!r}: ndim unknown — add vectors via sync/rebuild_index or pass ndim= to get_store'
    kw = merge(dict(ndim=m['ndim'], metric=_usearch_metric.get(m['metric'],'cos'), dtype=m['dtype']),
               {k:m[k] for k in ('connectivity','expansion_add','expansion_search') if m[k]})
    idx = Index(**kw)
    if load and m['path'] and Path(m['path']).exists(): idx.load(m['path'])
    self.ann_indices[name] = idx
    return idx

@patch
def _save_index(self:Database, name):
    'Persist the in-memory Index to its sidecar path (no-op for in-memory dbs).'
    m = self._ann_meta(name)
    if m and m['path'] and name in self.ann_indices: self.ann_indices[name].save(m['path'])

# %% ../nbs/01_core.ipynb #aea0410ad7106548
@patch
def fts_search(self:Table,
               q:str, # query string
               columns:list|None=None, # columns to return
               order_by:str|None=None, # order by clause
               limit:int|None=None, # limit on number of results
               offset:int|None=None, # offset for results
               where:str|None=None, # additional where clause
               where_args:dict|None=None, # args for where clause
               quote:bool=False, # quote FTS query to disable special chars
               include_rank:bool=True # include rank column
               ) -> list:
    'FTS search on any table with FTS5 enabled.'
    fts_q = self.db.quote_fts(q) if quote else q
    sql = self.search_sql(columns,order_by,limit,offset,where,include_rank)
    return self.db.q(sql, merge(dict(query=fts_q), where_args or {}))

def _dtype_check(tbl, dtype, rows):
    '''Warn when `dtype` cannot be the dtype these vectors were stored as.

    The failure is otherwise silent and total. `model2vec` returns float32, `FastEncode` returns
    float16, and this function defaults to float16 — store the first and search as the second and
    `distance_cosine_f16` reads the f32 bytes as twice as many f16 values, whose inf/nan bit patterns
    make the distance function return *SQL NULL for every row*. No exception, no empty result: the
    vector leg just returns rows in rowid order, and a hybrid search quietly degrades to FTS only.'''
    want = _dtype_suffix(dtype)
    m = tbl.db._ann_meta(tbl.name)
    if m and m['dtype'] and m['dtype'] != want:
        warnings.warn(f'{tbl.name!r}: vector search using dtype={want!r} but the store is registered '
                      f'as {m["dtype"]!r}. Distances are being computed over reinterpreted bytes — '
                      f'pass dtype= matching the embeddings you inserted.')
    elif len(rows) > 1 and all(r.get('_dist') in (0, None) for r in rows):
        warnings.warn(f'{tbl.name!r}: every distance came back null or 0, which usually means dtype={want!r} '
                      f'does not match how the embeddings were stored (e.g. float32 vectors from '
                      f'model2vec searched as float16). The ranking is meaningless.')
    return rows


@patch
def vec_search(self: Table,
               emb: bytes,                    # query embedding vector (as bytes)
               columns: list = None,          # columns to return (None = all)
               where: str = None,             # additional WHERE clause
               where_args: dict = None,       # args for WHERE clause
               emb_col: str = 'embedding',    # name of the embedding column
               emb_metric: str = 'cosine',    # distance metric
               dtype=np.float16,              # embedding dtype
               limit: int | None = 50,        # max results
               offset: int | None = None,     # offset for pagination
               ) -> list:
    "Vector similarity search on any table with an embedding column."
    dist = f'distance_{emb_metric}_{_dtype_suffix(dtype)}({emb_col}, :qvec)'
    sel_cols = [f'{c} as {c}' if c == 'rowid' else c for c in columns] if columns else ['*']
    sel = ','.join(sel_cols) + f', {dist} as _dist'
    wh = f'{emb_col} is not null' + (f' AND {where}' if where else '')
    rows = self.db.q(f'SELECT {sel} FROM {self.name} WHERE {wh} ORDER BY _dist LIMIT :limit OFFSET :offset',
                dict(qvec=emb, limit=limit, offset=ifnone(offset, 0), **(where_args or {})))
    return _dtype_check(self, dtype, rows)

# %% ../nbs/01_core.ipynb #f77f5d4162ca5935
def _rid(): return 'rowid as rowid'
@patch
def ann_search(self:Table,          # store table (must be ANN-registered)
               emb:bytes,           # query embedding
               columns:list=None,   # columns to return (rowid always included)
               limit:int=50,        # max results
               where:str= None,        # additional where clause (ignored if no rows returned by ANN)
               where_args: dict = None,  # args for where clause
               dtype=np.float16
               ):   # embedding dtype
    'HNSW ANN search via the store\'s usearch Index. Returns rows (+`_dist`) ordered by similarity.'
    m = self.db._ann_meta(self.name)
    if not (m and m['ndim']): return []
    idx = self.db.get_index(self.name)
    if not idx.size: return []
    res = idx.search(np.frombuffer(emb, dtype=dtype), count=limit*2)
    keys = np.atleast_1d(res.keys).tolist()   # -> python ints (L() would wrap the whole ndarray)
    if not keys: return []
    dist, ord = dict(zip(keys, np.atleast_1d(res.distances).tolist())), dict(L(keys).renumerate())
    cols = [c for c in (columns or []) if c != 'rowid']
    sel = ','.join(cols + [_rid()]) if cols else '*, %s'%_rid()
    wh = f'where {_in("rowid", keys)}' + (f' AND {where}' if where else '')
    rows = self.db.q(f'select {sel} from {self.name} {wh}', where_args or None)
    for r in rows: r['_dist'] = dist.get(r['rowid'])
    return sorted(rows, key=lambda r: ord.get(r['rowid'],1e10))[:limit]

@patch
def _idx_remove(self:Table, idx, keys):
    'Remove the keys that the index actually contains (usearch remove is not a no-op on absent keys).'
    if (present := [k for k in keys if idx.contains(k)]): idx.remove(np.array(present, dtype=np.int64))

@patch
def _sync_index(self:Table, add_ids, rm_rowids, dtype=np.float16):
    'Apply adds (by id) / removes (by rowid) to the ANN index from current blobs; infer+persist ndim; save.'
    m = self.db._ann_meta(self.name)
    if rm_rowids and m['ndim']: self._idx_remove(self.db.get_index(self.name), rm_rowids)
    kw = dict(select=f'{_rid()}, embedding', where=_in('id', add_ids))
    rows = L(self(**kw)).filter(lambda r: r['embedding']) if add_ids else L()
    if rows:
        if not m['ndim']:
            m['ndim'] = len(np.frombuffer(rows[0]['embedding'], dtype=dtype))
            self.db.t.usearch_indices.update(dict(name=self.name, ndim=m['ndim']))
        idx = self.db.get_index(self.name)
        keys = rows.itemgot('rowid')
        self._idx_remove(idx, keys)
        idx.add(np.array(keys, dtype=np.int64),
                np.stack([np.frombuffer(b, dtype=dtype) for b in rows.itemgot('embedding')]))
    self.db._save_index(self.name)

@patch
def sync(self:Table,            # store table (hash-id; ANN mirrored if registered)
         content,               # iterable of chunk dicts with 'content'
         key_col:str=None,      # scope existing rows by this column's values (e.g. 'path','package'); None = whole table
         emb_fn=None,           # embedder for new/changed chunks
         embed:bool=True,       # embed before upsert
         force:bool=False,      # treat all content as new (skip diff)
         parallel:bool=False,   # chunked BEGIN IMMEDIATE writes; needs database(busy_timeout=...)
         chunk:int=5_000):      # rows per transaction when parallel=True
    'Smart hash-diff update: delete stale rows, embed+upsert changed, mirror into the ANN index. Returns {changed,same,removed}.'
    content = L(content).filter(lambda d: d.get('content') and d['content'].strip())
    cont_hash = {_slug(d['content']): d for d in content}
    if force: ex = set()
    elif key_col:
        vals = {v for d in content if (v:=d.get(key_col)) is not None}
        kw = dict(select='id', where=_in(key_col, vals))
        ex = set(L(self(**kw)).itemgot('id')) if vals else set()
    else: ex = set(L(self(select='id')).itemgot('id'))
    stale  = ex - cont_hash.keys()
    to_add = filter_keys(cont_hash, not_(in_(ex)))
    m  = self.db._ann_meta(self.name)
    dt = _np_dtype.get(m['dtype'], np.float16) if m else np.float16
    rm_rowids = L(self(select=_rid(), where=_in('id', stale))).itemgot('rowid') if (m and stale) else L()
    if stale: self.delete_where(where=_in('id', stale))
    if to_add: process_content(self, list(to_add.values()), embed=embed, emb_fn=emb_fn, parallel=parallel, chunk=chunk)
    if m: self._sync_index(list(to_add), list(rm_rowids), dt)
    return dict(changed=len(to_add), same=len(ex)-len(stale), removed=len(stale))

@patch
def rebuild_index(self:Table, dtype=None):
    'Rebuild the ANN Index from scratch using the embedding blobs in SQLite. Returns index size.'
    m = self.db._ann_meta(self.name)
    assert m, f'{self.name!r} is not an ANN store'
    dt = dtype or _np_dtype.get(m['dtype'], np.float16)
    rows = L(self(select=f'{_rid()}, embedding')).filter(lambda r: r['embedding'])
    self.db.ann_indices.pop(self.name, None)
    if not rows:
        if not m['ndim']: return 0                                   # never had vectors; nothing to clear
        self.db.get_index(self.name, load=False).reset()  # empty index, ignore the stale sidecar
        self.db._save_index(self.name)                               # overwrite sidecar to reflect empty table
        return 0
    nd = len(np.frombuffer(rows[0]['embedding'], dtype=dt))
    if m['ndim'] != nd: self.db.t.usearch_indices.update(dict(name=self.name, ndim=nd))
    idx = self.db.get_index(self.name, load=False); idx.reset()
    idx.add(np.array(rows.itemgot('rowid'), dtype=np.int64),
            np.stack([np.frombuffer(b, dtype=dt) for b in rows.itemgot('embedding')]))
    self.db._save_index(self.name)
    return idx.size

# %% ../nbs/01_core.ipynb #4258d0ab30d7610b
@patch
def ann_vec(self:Table,          # ANN-registered store
            key:int,             # usearch key (the row's rowid)
            dtype=np.float16):   # fallback dtype when the registry has none
    'The vector the index already holds for `key`, or None when the key is not indexed.'
    m = self.db._ann_meta(self.name)
    if not (m and m['ndim']): return None
    idx = self.db.get_index(self.name)
    if not idx.size or not idx.contains(key): return None
    return np.asarray(idx[key], dtype=_np_dtype.get(m['dtype'], dtype)).reshape(-1)

@patch
def ann_neighbors(self:Table,             # ANN-registered store
                  key:int,                # usearch key (rowid) to search from
                  limit:int=15,           # neighbours to return
                  columns:list=None,      # columns to return (rowid always included)
                  where:str=None,         # additional where clause
                  where_args:dict=None,   # args for where clause
                  include_self:bool=False,# keep the anchor row in the results
                  dtype=np.float16):      # embedding dtype
    '''Rows nearest an already-indexed row — "what else looks like this".

    Reuses the stored vector rather than re-embedding the row, so no model is loaded and no
    text is tokenised: the whole call is one HNSW probe plus one `rowid IN (...)` fetch.'''
    v = self.ann_vec(key, dtype)
    if v is None: return []
    rows = self.ann_search(v.tobytes(), columns, limit + (0 if include_self else 1), where, where_args, dtype)
    return rows[:limit] if include_self else [r for r in rows if r['rowid'] != key][:limit]

# %% ../nbs/01_core.ipynb #ecffd1079678f470
def rrf_merge(fts_results, vec_results, k=60, limit=50, id_key='rowid') -> list:
    "Reciprocal Rank Fusion: merges FTS and vector results. Items in both lists score highest."
    scores = {}
    for rank, row in enumerate(fts_results):
        rid = row.get(id_key, id(row))
        scores[rid] = merge(row, {'_rrf_score': 1.0/(k + rank)})
    for rank, row in enumerate(vec_results):
        rid = row.get(id_key, id(row))
        if rid in scores: scores[rid]['_rrf_score'] += 1.0/(k + rank)
        else: scores[rid] = merge(row, {'_rrf_score': 1.0/(k + rank)})
    return sorted(scores.values(), key=lambda x: x['_rrf_score'], reverse=True)[:limit]

# %% ../nbs/01_core.ipynb #92985104635cbc5b
def database(pth_or_uri:str=':memory:',     # the database name or URL
             wal:bool=True,                 # use WAL mode
             sem_search:bool=True,          # enable usearch extensions
             busy_timeout:int=None,         # ms to wait on a locked db; None = apsw default. Set for parallel ingestion
             **kw,                          # additional args to pass to apswutils database
             ) -> Database:
    'Set up a database connection and load usearch extensions.'
    if isinstance(pth_or_uri, (str, Path)): Path(pth_or_uri).parent.mkdir(parents=True,exist_ok=True)
    # apsw runs its bestpractice hook (100ms timeout, then `PRAGMA optimize`) *during* Connection
    # construction, so the window has to span the open -- retuning afterwards is already too late.
    with (busy_window(busy_timeout) if busy_timeout else nullcontext()):
        _db = Database(pth_or_uri, **kw)
        if busy_timeout: _db.conn.set_busy_timeout(busy_timeout)   # persists past the window
        if wal: _db.enable_wal()
    _db._fts_tokenizers = register_tokenizers(_db.conn, map_tokenizers)
    if not sem_search: return _db
    from usearch import sqlite_path
    _db.conn.enableloadextension(True)
    _db.conn.loadextension(sqlite_path())
    _db.conn.enableloadextension(False)
    return _db

# %% ../nbs/01_core.ipynb #b0ca47afb872e0d6
_RERANKERS = {}
def _get_reranker(model=None):
    'Cached flashrank Ranker (default: fast ms-marco-TinyBERT-L-2-v2).'
    from flashrank import Ranker
    key = model or 'default'
    if key not in _RERANKERS: _RERANKERS[key] = Ranker(model_name=model) if model else Ranker()
    return _RERANKERS[key]

def rerank_hits(q, hits, model=None, limit=None, text_col='content'):
    'Reorder search hits by a flashrank cross-encoder on (q, hit[text_col]); returns the top `limit`.'
    from flashrank import RerankRequest
    if not hits: return hits
    passages = [{'id':i, 'text':h.get(text_col) or ''} for i,h in enumerate(hits)]
    ranked = _get_reranker(model).rerank(RerankRequest(query=q, passages=passages))
    out = [hits[r['id']] for r in ranked]
    return out[:limit] if limit else out

# %% ../nbs/01_core.ipynb #533c9264e227dc25
@patch
def search(self: Database,  # database connection
           q:str,  # query string
           emb:bytes,  # embedding vector
           columns:list=None,  # columns to return
           where:str=None,  # additional where clause
           where_args:dict=None,  # args for where clause
           limit:int|None=50,  # limit on number of results
           offset:int|None=None,  # offset for results (ignored when rrf=True)
           table_name='store',  # table name
           emb_col='embedding',  # embedding column name
           emb_metric:str='cosine',  # embedding distance metric (cosine,sqeuclidean,inner,divergence)
           rrf=True,  # rerank results with reciprocal rank fusion
           rrf_k:int=60,  # RRF k parameter
           dtype=np.float16,  # embedding dtype
           id_key:str='rowid',  # key to join RRF results on
           quote:bool=True,  # quote FTS query to disable special chars (ignored when fts_pre=True)
           fts_pre:bool=True,  # send the FTS leg through `pre()`: keywords, wildcards, OR
           ann:bool=False,  # use the HNSW ANN index for the vector leg falls back to the exact vec scan when `where` is set
           parallel:bool=False, # not used. kept for backward compatability. to be removed in later releases
           reranking:bool=False,  # rerank the merged (rrf) hits with a flashrank cross-encoder
           rerank_model:str=None  # flashrank model name (None -> fast default)
           ):
    'Search the litesearch store with fts and vector search combined.'
    if not q.strip(): return None
    tbl = self.t[table_name]
    cols = list(columns or [])
    if rrf and id_key not in cols: cols = [id_key] + cols
    if reranking and 'content' not in cols: cols = cols + ['content']  # need text for the cross-encoder
    lim, off = (limit + offset) if rrf and offset else limit, offset if not rrf else None
    use_ann = ann and not where
    fts_q, fts_quote = q, quote
    if fts_pre and (p := pre(q)): fts_q, fts_quote = p, False
    vec_leg = lambda t: (lambda: t.ann_search(emb,cols,lim,where,where_args,dtype) if use_ann else t.vec_search(
	          emb,cols,where,where_args,emb_col,emb_metric,dtype,lim,off))
    exec_ls = [lambda: tbl.fts_search(fts_q, cols, 'rank', lim, off, where, where_args, fts_quote), vec_leg(tbl)]
    fts, vec = L(exec_ls).map(lambda g: g())
    if rrf:
        hits = rrf_merge(fts, vec, rrf_k, lim, id_key)[ifnone(off, 0):]
        if reranking: hits = rerank_hits(q, hits, rerank_model, limit)
        return hits
    return dict(fts=fts, vec=vec)
