# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_core.ipynb.

# %% auto #0
__all__ = ['rrf_merge', 'database', 'format_for_context', 'get_search_tool', 'SemanticCache', 'search_batch']

# %% ../nbs/01_core.ipynb #cda88b6a
from fastcore.all import Path, Generator, patch, Optional, Union, Iterable, merge, ifnone, parallel
from fastlite import Database
from apswutils.db import Table
from apswutils.utils import cursor_row2dict
import numpy as np

_dtype_suffixes = {np.int8: 'i8', np.float16: 'f16', np.float64: 'f64', np.float32: 'f32'}
def _dtype_suffix(dtype=np.float16): return _dtype_suffixes.get(dtype, 'f32')

# %% ../nbs/01_core.ipynb #ddeccc26
@patch
def query(self: Database, sql: str, params: Optional[Union[Iterable, dict]] = None) -> Generator[dict, None, None]:
    '''Execute a query and return results as a list of AttrDict'''
    p = params if isinstance(params, dict) else tuple(params or tuple())
    cursor = self.execute(sql, p)
    cursor.row_trace = cursor_row2dict
    yield from cursor

# %% ../nbs/01_core.ipynb #3a08e489
@patch
def get_store(self:Database,    # database connection
            name:str='store',   # table name
            hash:bool=False,    # whether to create hash index on content
            **kw,               # additional args to pass to fastlite create
):
    "Convenience for simple RAG: creates a content/embedding/metadata table with FTS5. For custom schemas, use vec_search and rrf_merge directly."
    cols = dict(content=str, embedding=bytes, metadata=str, uploaded_at=float,defaults=dict(uploaded_at='CURRENT_TIMESTAMP'),pk='id')
    if hash: cols.update(dict(hash_id='id',hash_id_columns=['content']))
    else: cols.update(dict(id=int, not_null=['content']))
    _content = self.t[name].create(**cols,if_not_exists=True, **kw)
    if not _content.detect_fts(): _content.enable_fts(['content','metadata'], create_triggers=True, tokenize='porter', replace=True)
    return _content

# %% ../nbs/01_core.ipynb #c1c04ba9
@patch
def vec_search(self: Table,
               emb: bytes,                    # query embedding vector (as bytes)
               columns: list = None,          # columns to return (None = all)
               where: str = None,             # additional WHERE clause
               where_args: dict = None,       # args for WHERE clause
               emb_col: str = 'embedding',    # name of the embedding column
               emb_metric: str = 'cosine',    # distance metric
               dtype=np.float16,              # embedding dtype
               limit: int | None = 50,        # max results
               offset: int | None = None,     # offset for pagination
               ) -> list:
    "Vector similarity search on any table with an embedding column."
    dist = f'distance_{emb_metric}_{_dtype_suffix(dtype)}({emb_col}, :qvec)'
    sel_cols = [f'{c} as {c}' if c == 'rowid' else c for c in columns] if columns else ['*']
    sel = ','.join(sel_cols) + f', {dist} as _dist'
    wh = f'{emb_col} is not null' + (f' AND {where}' if where else '')
    return self.db.q(f'SELECT {sel} FROM {self.name} WHERE {wh} ORDER BY _dist LIMIT :limit OFFSET :offset',
                dict(qvec=emb, limit=limit, offset=ifnone(offset, 0), **(where_args or {})))

# %% ../nbs/01_core.ipynb #1838b5e3
def rrf_merge(fts_results, vec_results, k=60, limit=50, id_key='rowid') -> list:
    "Reciprocal Rank Fusion: merges FTS and vector results. Items in both lists score highest."
    scores = {}
    for rank, row in enumerate(fts_results):
        rid = row.get(id_key, id(row))
        scores[rid] = merge(row, {'_rrf_score': 1.0/(k + rank)})
    for rank, row in enumerate(vec_results):
        rid = row.get(id_key, id(row))
        if rid in scores: scores[rid]['_rrf_score'] += 1.0/(k + rank)
        else: scores[rid] = merge(row, {'_rrf_score': 1.0/(k + rank)})
    return sorted(scores.values(), key=lambda x: x['_rrf_score'], reverse=True)[:limit]

# %% ../nbs/01_core.ipynb #46cb5685
def database(pth_or_uri:str=':memory:',     # the database name or URL
             wal:bool=True,                 # use WAL mode
             sem_search:bool=True,          # enable usearch extensions
             **kw,                          # additional args to pass to apswutils database
             ) -> Database:
    'Set up a database connection and load usearch extensions.'

    if isinstance(pth_or_uri, (str, Path)): Path(pth_or_uri).parent.mkdir(exist_ok=True)
    _db = Database(pth_or_uri, **kw)
    if wal: _db.enable_wal()
    if not sem_search: return _db
    from usearch import sqlite_path
    _db.conn.enableloadextension(True)
    _db.conn.loadextension(sqlite_path())
    _db.conn.enableloadextension(False)
    return _db

# %% ../nbs/01_core.ipynb #5b40d2cd
@patch
def search(self: Database,  # database connection
           q:str,  # query string
           emb:bytes,  # embedding vector
           columns:list=None,  # columns to return
           where:str=None,  # additional where clause
           where_args:dict=None,  # args for where clause
           limit:int|None=50,  # limit on number of results
           offset:int|None=None,  # offset for results (ignored when rrf=True)
           table_name='store',  # table name
           emb_col='embedding',  # embedding column name
           emb_metric:str='cosine',  # embedding distance metric (cosine,sqeuclidean,inner,divergence)
           rrf=True,  # rerank results with reciprocal rank fusion
           rrf_k:int=60,  # RRF k parameter
           dtype=np.float16,  # embedding dtype
           id_key:str='rowid',  # key to join RRF results on
           quote:bool=False,  # quote FTS query to disable special chars
           ):
    'Search the litesearch store with fts and vector search combined.'
    if not q.strip(): return None
    tbl = self.t[table_name]
    cols = list(columns or [])
    if rrf and id_key not in cols: cols = [id_key] + cols
    fts_q= self.quote_fts(q) if quote else q
    lim, off = (limit + offset) if rrf and offset else limit, offset if not rrf else None
    sql = tbl.search_sql(order_by='rank', columns=cols, limit=lim, where=where, include_rank=True, offset=off)
    fts = self.q(sql, merge(dict(query=fts_q), where_args or {}))
    vec = tbl.vec_search(emb, columns=cols, where=where, where_args=where_args, emb_col=emb_col, emb_metric=emb_metric,
                         dtype=dtype, limit=lim, offset=off)
    if rrf: return rrf_merge(fts, vec, k=rrf_k, limit=lim, id_key=id_key)[ifnone(off, 0):]
    return dict(fts=fts, vec=vec)

# %% ../nbs/01_core.ipynb #76894841
def format_for_context(results: list,        # list of dicts from db.search(), ranked by RRF score
                       max_tokens: int=4096, # approximate token budget (1 token ≈ 4 chars)
                       template: str=None,   # per-result format string; may use {score}, {source}, {content}
                       ) -> str:
    "Format search results into a context string within a token budget. Truncates to fit."
    tmpl = template or '[{score:.3f}] {source}\n{content}'
    out, budget = [], max_tokens * 4  # convert tokens → char budget
    for r in results:
        s = tmpl.format(score=r.get('_rrf_score', 0.0), source=r.get('metadata', ''), content=r.get('content', ''))
        if len(s) > budget: s = s[:budget]
        out.append(s)
        budget -= len(s)
        if budget <= 0: break
    return '\n\n'.join(out)

# %% ../nbs/01_core.ipynb #3c5ef973
from fastcore.imports import llmtool
import json

def get_search_tool(db,              # database connection
                    enc,             # encoder with encode_query(texts) -> list[np.ndarray]
                    store:str='store', # table name to search
                    top_k:int=10,    # default number of results
                    dtype=np.float16 # embedding dtype matching the stored embeddings
                    ):
    "Return an @llmtool-decorated search function bound to this db and encoder. Pass to claudette or any tool-use framework."
    def search_documents(query: str, n_results: int = top_k) -> str:
        """Search indexed documents for the given query. Returns top results as JSON with content, score, source and rank."""
        emb = enc.encode_query([query])[0].ravel().tobytes()
        results = db.search(query, emb, table_name=store, limit=n_results, dtype=dtype)
        return json.dumps([{'content': r.get('content', ''), 'score': r.get('_rrf_score', 0.0),
                            'source': r.get('metadata', ''), 'rank': i}
                           for i, r in enumerate(results or [])])
    return llmtool(search_documents)

# %% ../nbs/01_core.ipynb #d3ec3f60
from usearch.index import Index as USearchIndex

class SemanticCache:
    "In-memory semantic cache backed by a usearch HNSW index. Supports matryoshka truncation for fast lookups."
    def __init__(self,
                 ndim: int,              # full embedding dimension
                 threshold: float=0.05, # cosine distance threshold for a cache hit
                 metric: str='cos',     # distance metric for the usearch Index
                 dtype=np.float32,      # numpy dtype used when trimming embeddings
                 truncate_to: int=None, # matryoshka: use only the first N dims for cache lookup
                 ):
        self.dim = truncate_to or ndim
        self.index = USearchIndex(ndim=self.dim, metric=metric)
        self._cache = {}
        self.threshold = threshold
        self.truncate_to = truncate_to
        self._metric = metric

    def _trim(self, emb: np.ndarray) -> np.ndarray:
        v = emb[:self.truncate_to] if self.truncate_to else emb
        return np.asarray(v, dtype=np.float32)

    def lookup(self, emb: np.ndarray):
        "Return cached result if nearest stored embedding is within threshold distance, else None."
        if not len(self.index): return None
        matches = self.index.search(self._trim(emb), 1)
        if len(matches) and matches[0].distance < self.threshold:
            return self._cache[int(matches[0].key)]
        return None

    def store(self, emb: np.ndarray, result):
        "Add result to the cache keyed by its embedding."
        k = len(self._cache)
        self.index.add(k, self._trim(emb))
        self._cache[k] = result

    def clear(self):
        "Evict all cached entries."
        self.index = USearchIndex(ndim=self.dim, metric=self._metric)
        self._cache = {}

    def __len__(self): return len(self._cache)
    def __repr__(self): return f'SemanticCache(entries={len(self)}, dim={self.dim}, threshold={self.threshold})'

# %% ../nbs/01_core.ipynb #1475920e
def search_batch(db,                  # database connection
                 queries_embs: list,  # list of (query_str, emb_bytes) pairs
                 cache=None,          # optional SemanticCache to check/populate
                 **kwargs             # passed to db.search()
                 ) -> list:
    "Run multiple searches in parallel. Returns list of result lists in the same order as queries_embs."
    dtype = kwargs.get('dtype', np.float16)
    def _search(qe):
        q, emb = qe
        if cache is not None:
            emb_arr = np.frombuffer(emb, dtype=dtype)
            hit = cache.lookup(emb_arr)
            if hit is not None: return hit
        result = db.search(q, emb, **kwargs)
        if cache is not None and result:
            cache.store(np.frombuffer(emb, dtype=dtype), result)
        return result
    return list(parallel(_search, queries_embs, threadpool=True))
