# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_data.ipynb.

# %% auto #0
__all__ = ['skip_folder_re', 'skip_file_re', 'code_exts', 'file_exts', 'PROFILES', 'MIN_PARALLEL_FILES', 'needs_ocr', 'clean_md',
           'ocr_parse', 'oxide_parse', 'pdf_parse', 'SafeFastChunker', 'chunk_markdown', 'chunk_spans', 'repo_root',
           'spec', 'pyparse', 'ipynb_parse', 'non_py_sigs', 'chunk_texts', 'Profile', 'register_profile', 'profile_for',
           'file_parse', 'pkg2files', 'dir2files', 'pkg2chunks', 'dir2chunks', 'installed_packages', 'clean', 'add_wc',
           'mk_wider', 'kw', 'pre', 'img2png', 'png_det', 'images_to_pdf', 'mv_skill_md']

# %% ../nbs/02_data.ipynb #8a1e955269e0d234
from fastcore.all import L,concat,patch,ifnone,Path,delegates,globtastic,parallel,type2str,first,filter_keys,in_,fdelegates,defaults
from pdf_oxide import PdfDocument
import struct as _struct, re

# %% ../nbs/02_data.ipynb #fc014ece1162af13
@patch
def pdf_texts(doc:PdfDocument, st=0, end=None) -> L:
    'Extract plain text from each page.'
    return L(range(st, ifnone(end, doc.page_count()))).map(doc.extract_text)

@patch
def pdf_links(doc:PdfDocument, st=0, end=None) -> L:
    'Extract hyperlinks from each page as a list of URI strings.'
    pages = range(st, ifnone(end, doc.page_count()))
    ann = L(pages).map(lambda i: doc.get_annotations(i))
    return ann.concat().filter(lambda a: 'action_uri' in a).map(lambda a: a['action_uri'])

@patch
def pdf_images(doc:PdfDocument, st=0, end=None, output_dir=None) -> L:
    'Extract images — returns metadata dicts, or saves to output_dir if provided.'
    pages = range(st, ifnone(end, doc.page_count()))
    if output_dir:
        Path(output_dir).mkdir(exist_ok=True)
        return L(pages).map(lambda i: doc.to_plain_text(i, include_images=True, image_output_dir=str(output_dir)))
    return L(pages).map(lambda i: doc.extract_images(i)).concat()

@patch
def pdf_markdown(doc:PdfDocument, st=0, end=None, **kw) -> L:
    'Convert pages to markdown with headings and tables detected.'
    return L(range(st, ifnone(end, doc.page_count()))).map(lambda i: doc.to_markdown(i, **kw))

@patch
def pdf_tables(doc:PdfDocument, st=0, end=None) -> L:
    'Extract structured tables (rows/cells/bbox) from each page.'
    return L(range(st, ifnone(end, doc.page_count()))).map(lambda i: doc.extract_tables(i)).concat()

@patch
def pdf_spans(doc:PdfDocument, st=0, end=None) -> L:
    'Extract text spans with font metadata (size, weight, bbox) per page.'
    return L(range(st, ifnone(end, doc.page_count()))).map(lambda i: doc.extract_spans(i)).concat()

# %% ../nbs/02_data.ipynb #9c0b11cb32e0d9a5
def needs_ocr(md:str) -> bool:
	'True when pdf_oxide flagged the page as scanned (no extractable text layer).'
	return '> [OCR REQUIRED' in md.strip()

def clean_md(md):
	md = re.sub(r'([a-z])-\n([a-z])', r'\1\2', md)
	md = re.sub(r'([a-z])-\n([A-Z])', r'\1-\2', md)
	md = re.sub(r'^ +', '', md, flags=re.M)
	md = re.sub(r' {2,}', ' ', md)
	return re.sub(r'\n{3,}', '\n\n', md)

def ocr_parse(pdf:str|PdfDocument|bytes|Path, # PdfDocument object
              dpi:int=300, # dpi for ocr 150 is okay. 300 is good
              extract_links=True, # extract links within pdf
              **kw  # extra kwargs passed to LiteParse (e.g. dpi, num_workers, extract_links)
              ):
	from liteparse import LiteParse
	data = pdf.to_bytes() if isinstance(pdf, PdfDocument) else pdf
	return LiteParse(ocr_enabled=True, dpi=dpi, extract_links=extract_links, **kw).parse(data)

@fdelegates(PdfDocument.to_markdown_all)
def oxide_parse(pdf: str|PdfDocument|bytes|Path,
                out_path:str|Path|None=None, # dir that holds the image subdir; images link relative to it
                preserve_layout=False, # preserrve layout in pdf-oxide
                image_dir='images', # subdir for extracted images
                **kwargs # extra kwargs passed to pdf-oxide
) -> tuple[list[str],bool]:
	"""Parse a pdf using pdf-oxide to markdown with images extracted to a subdir."""
	if not isinstance(pdf, PdfDocument): pdf=PdfDocument.from_bytes(pdf) if isinstance(pdf, bytes) else PdfDocument(pdf)
	out_path = Path(out_path or 'pdfs').resolve()
	imdir = out_path/image_dir
	imdir.mkdir(exist_ok=True, parents=True)
	kw = dict(image_output_dir=str(imdir), include_images=True,embed_images=False, **kwargs)
	md = clean_md(pdf.to_markdown_all(preserve_layout, **kw)).replace(f'{imdir}/', f'{image_dir}/')
	return md.split('\n---\n'), needs_ocr(md)

def pdf_parse(pdf: PdfDocument | str | Path | bytes,  # PdfDocument object
              out_path:str|Path|None=None,  # dir that holds the image subdir; images link relative to it
              image_dir='images',  # subdir for extracted images
              preserve_layout=False,  # preserrve layout in pdf-oxide
              ocr_selection:str='auto'  # choosing ocr (auto, off, on). auto uses pdf-oxide's ocr detection
              ) -> list[str]:
	'PdfDocument to markdown; if OCR is required, uses LiteParse for better formatting'
	op = lambda doc: [clean_md(p.text) for p in ocr_parse(doc).pages]
	if ocr_selection.lower() == 'on': return op(pdf)
	md, ocr_chk = oxide_parse(pdf, out_path, preserve_layout, image_dir)
	if ocr_selection.lower() == 'off': return md
	return op(pdf) if ocr_chk else md

# %% ../nbs/02_data.ipynb #4a33701ff7ff248b
import chonkie_core
from chonkie import RecursiveChunker, FastChunker, BaseChunker
from chonkie.types import Chunk

def _char_start(b:bytes, i:int) -> int:
    'Back a byte offset up to the first byte of the UTF-8 character it lands inside.'
    while 0 < i < len(b) and b[i] & 0xC0 == 0x80: i -= 1
    return i

class SafeFastChunker(FastChunker):
    '`FastChunker` whose cuts land on character boundaries.'
    def chunk(self, text:str) -> list:
        if not text: return []
        kw = dict(size=self.chunk_size, prefix=self.prefix, consecutive=self.consecutive,
                  forward_fallback=self.forward_fallback)
        kw |= dict(pattern=self.pattern) if self.pattern else dict(delimiters=self.delimiters)
        b, out, pos = text.encode(), [], 0
        for s, e in chonkie_core.chunk_offsets(b, **kw):
            t = b[_char_start(b, s):_char_start(b, e)].decode()
            if not t: continue
            out.append(Chunk(text=t, start_index=pos, end_index=pos+len(t), token_count=0))
            pos += len(t)
        return out


# %% ../nbs/02_data.ipynb #4ddbb058066ad269
def chunk_markdown(text:str,     # markdown text (e.g. from pdf_markdown())
                   chunker:BaseChunker=None
) -> L:
	'Split markdown into paragraph chunks on blank lines'
	r = chunker or SafeFastChunker(chunk_size=512)
	return L(r(text)).map(lambda c: c.text)

@patch
@delegates(chunk_markdown)
def pdf_chunks(self:PdfDocument, # PDF document
               **kwargs
               ) -> L:
	'Markdown-chunked text from each page; yields (page, chunk_idx, text) tuples.'
	return L((pg+1, ci, chunk)
	         for pg, md in enumerate(pdf_parse(self))
	         for ci, chunk in enumerate(chunk_markdown(md, **kwargs)))

# %% ../nbs/02_data.ipynb #bd59b59ae64cea17
def chunk_spans(text:str,            # text to split
                chunker:BaseChunker=None
) -> L:
    'Split text into chunks, returning (start_char, end_char, text) spans into the original text.'
    r = chunker or SafeFastChunker(chunk_size=512)
    return L(r(text)).map(lambda c: (c.start_index, c.end_index, c.text))

# %% ../nbs/02_data.ipynb #d47391264283f71c
from importlib.util import find_spec as fs
from importlib.metadata import distribution as dist, distributions as dists, version
from importlib.machinery import ModuleSpec
import ast, re
from ast import get_source_segment as gs
from codesigs import file_sigs
from fastcore.basics import fdelegates, true
from fastcore.nbio import read_nb

# %% ../nbs/02_data.ipynb #e2d83d2c61b7dfe2
skip_folder_re = r'^[.]|^(?:tests?|examples?|docs?|build|dist)$'
skip_file_re = r'^[.]|^(?:setup\.py|conftest\.py)$'
code_exts = '.py,.js,.ts,.jsx,.tsx,.java,.go,.cs,.ruby,.php,.swift,.kt,.kts,.rs,.scala,.lua'
file_exts = code_exts + ',.md,.txt,.pdf,.ipynb'

def repo_root() -> Path:
	'Find the root of the current git repository, or None if not in a repo.'
	return first((Path.cwd(), *Path.cwd().parents), lambda p: (p/'.git').exists())

def spec(pkg:str) -> ModuleSpec | None:
	'Return the importlib ModuleSpec for a package, or None if not found.'
	try:
		if s := fs(pkg) or fs(pkg.replace('-', '_')): return s
		if not (d:= dist(pkg)): return None
		if tl:=d.read_text('top_level.txt'): return s if (s:=fs(tl.splitlines()[0])) else None
		chk = lambda f: len(f.parts) >= 2 and f.name=='__init__.py' and not f.parts[0].endswith('.dist-info')
		if p:= L(d.files).filter(chk).map(lambda f: f.parts[0]): return fs(first(p))
		return None
	except ModuleNotFoundError: return None

def _seg(lines, n):
    '''`ast.get_source_segment` with the line split hoisted out to the caller.

    The stdlib version re-splits the *entire file* on every call, so a module with 30 top-level
    definitions splits itself 30 times: `ast._splitlines_no_ff` was 68% of the time spent parsing
    400 files of `transformers`. Its splitting rules are not `str.splitlines`' — form feeds and
    the unicode line separators are deliberately not breaks — so it is the same function hoisted,
    not an approximation of it, and offsets are byte offsets into each line.'''
    if getattr(n, 'end_lineno', None) is None or getattr(n, 'end_col_offset', None) is None: return None
    lo, hi, c0, c1 = n.lineno-1, n.end_lineno-1, n.col_offset, n.end_col_offset
    if hi == lo: return lines[lo].encode()[c0:c1].decode()
    return ''.join([lines[lo].encode()[c0:].decode(), *lines[lo+1:hi], lines[hi].encode()[:c1].decode()])

def pyparse(p:Path=None,    # path to a python file
            code:str=None,  # code string to parse
            imports=False,   # include import statements as code chunks
            assigns=False       # include top-level assignments as code chunks
) -> L:
    '''Parse a code string or python file and return code chunks as list of dicts with content and metadata.

    Only module-level definitions are ever returned, so `tree.body` *is* the candidate list: walking
    the whole tree to tag every node with a `parent` and then filtering on "parent is the Module"
    computes an answer the body already gives. Dropping the walk and hoisting the line split take
    the same 400 files from 23.4s to 3.3s, chunk-for-chunk identical.'''
    assert bool(code) ^ bool(p), 'Either code or p must be provided, not both.'
    try: code = Path(p).read_text(encoding='utf-8') if not code else code
    except UnicodeDecodeError: return L()
    tree, lines = ast.parse(code), ast._splitlines_no_ff(code)
    mtime = Path(p).stat().st_mtime if p else None
    def n2c(n):
	    return dict(content=(_seg(lines, n) or '').strip(), metadata=dict(path=str(p), uploaded_at=mtime,
            name=getattr(n,'name',None), lang='.py', type=type2str(n.__class__),
            lineno=getattr(n,'lineno',None), end_lineno=getattr(n,'end_lineno',None)))
    def is_mod(n): return isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
    def is_assign(n): return assigns and isinstance(n, (ast.Assign, ast.AnnAssign)) and n.value
    def is_allowed(n): return is_mod(n) or is_assign(n) or (imports and isinstance(n, ast.ImportFrom))
    return L(tree.body).filter(is_allowed).map(n2c)

def ipynb_parse(p):
	'Parse ipynb files'
	def meta_(): return dict(path=str(p), uploaded_at=Path(p).stat().st_mtime, lang=p.suffix)
	fn = lambda c: dict(content=c['source'], metadata = meta_() | dict(type=c['cell_type']))
	return L(read_nb(p).cells).map(fn)

def non_py_sigs(p):
	'Signatures for paths that are not python code files using codesigs'
	def meta_(): return dict(path=str(p), uploaded_at=Path(p).stat().st_mtime, lang=p.suffix)
	return L(file_sigs(p)).map(lambda o: dict(content=o, metadata=meta_()))

def chunk_texts(text:str):
	'Chunk texts using Fast Chunker'
	return L(SafeFastChunker(chunk_size=512, delimiters='\n\n')(text)).map(lambda c: c.text)

# %% ../nbs/02_data.ipynb #profiles
from dataclasses import dataclass, field

@dataclass
class Profile:
    'How one *kind* of document should be read: parser, structure, chunker.'
    name:str
    exts:str = ''            # comma-separated extensions this profile claims
    parse:callable = None    # path -> (pages, meta)
    chunker:callable = None  # () -> a chunker for add_doc
    mode:str = None          # build_tree structural mode, bypassing detect_mode
    detect:callable = None   # (text) -> bool; disambiguates a shared extension like .xml or .txt
    kind:str = None          # doc kind recorded on the doc row, so it can be filtered on
    meta:callable = None     # (chunk text) -> dict of facets, stored as the chunk's `metadata` JSON
    def claims(self, suffix:str) -> bool:
        return not self.exts or suffix.lower() in {f".{e.strip().lstrip('.')}".lower()
                                                   for e in self.exts.split(',') if e.strip()}

PROFILES = {}

def register_profile(p:Profile) -> Profile:
    'Add a profile to the registry, replacing any of the same name.'
    PROFILES[p.name] = p
    return p

def profile_for(path=None,      # file whose extension (and first bytes) select the profile
                text:str=None,  # already-read text, when there is no file
                name:str=None   # ask for one by name, skipping detection
                ) -> Profile|None:
    'The profile that claims this document, or None for the default pipeline.'
    if name: return PROFILES.get(name)
    sfx = Path(path).suffix if path else ''
    if text is None and path is not None:
        # Generous, because markup-heavy formats bury their first content-bearing bytes: a GRETIL
        # `.htm` carries kilobytes of stylesheet and provenance header before any Sanskrit.
        try: text = Path(path).read_text(encoding='utf-8', errors='replace')[:60000]
        except OSError: text = ''
    for p in PROFILES.values():
        if p.claims(sfx) and (p.detect is None or p.detect(text or '')): return p
    return None

@delegates(pyparse)
def file_parse(p:Path=None,  # path to a code file
               **kwargs      # additional args to pass to pyparse
               ) -> L:
    'Parse a code file or code string and return code chunks with metadata.'
    if p.suffix == '.py': return pyparse(p, **kwargs)
    if p.suffix == '.ipynb': return ipynb_parse(p)
    if p.suffix in code_exts.split(','): return non_py_sigs(p)
    def meta_(): return dict(path=p, uploaded_at=Path(p).stat().st_mtime, lang=p.suffix)
    if p.suffix == '.pdf': return PdfDocument(p).pdf_chunks().map(lambda c: dict(content=c[2], metadata=meta_()))
    fn = lambda c: dict(content=c,metadata=meta_())
    if p.suffix  == '.md': return chunk_markdown(p.read_text(encoding='utf-8')).map(fn)
    if p.suffix == '.txt': return chunk_texts(p.read_text(encoding='utf-8')).map(fn)
    return L()


# %% ../nbs/02_data.ipynb #a8efe72ac0b7468a
@delegates(globtastic)
def pkg2files(pkg:str,								# package name
              skip_file_re=skip_file_re,  # regex to skip files
              skip_folder_re=skip_folder_re,  # regex to skip folders
              func=Path,						    # function to apply to file paths (e.g. Path or str)
			  **kwargs								# additional args to pass to globtastic
)->L:
	'Return list of python files in a package excluding tests and setup files.'
	if not (nm := spec(pkg)): return L()
	if nm.origin: o = Path(nm.origin).parent
	elif nm.submodule_search_locations: o= Path(nm.submodule_search_locations[0])
	else: return L()
	return globtastic(o, folder_re=nm.name, skip_folder_re=skip_folder_re,
	                  skip_file_re=skip_file_re, func=func, **kwargs)

# %% ../nbs/02_data.ipynb #41872245b3652853
@delegates(globtastic)
def dir2files(dir:str,  # package name
              skip_file_re=skip_file_re,  # regex to skip files
              skip_folder_re=skip_folder_re,  # regex to skip folders
              func=Path,  # function to apply to file paths (e.g. Path or str)
              **kwargs  # additional args to pass to globtastic
              )->L:
	'Return list of python files in a package excluding tests and setup files.'
	if not (rt :=Path(dir)).exists(): return L()
	return globtastic(rt, skip_folder_re=skip_folder_re, skip_file_re=skip_file_re, func=func, **kwargs)

# %% ../nbs/02_data.ipynb #33217682f16a1c9c
# Below this many files a process pool costs more to start than the parse it saves.
MIN_PARALLEL_FILES = 64

def _parse_files(files, n_workers=None, threadpool=False, **kw):
    '''Parse a list of paths, on a process pool once there are enough of them to pay for one.

    Processes, not threads. `file_parse` is `ast.parse` plus a pure-python tree walk and holds the
    GIL from end to end, so a thread pool contends rather than overlaps: over 2,170 files a
    4-thread pool measured 0.76x — *slower than serial* — against 3.37x for 4 processes. The same
    holds for the PDF branch, where pdf-oxide does the work in Rust but never releases the GIL.'''
    if n_workers is None: n_workers = 0 if len(files) < MIN_PARALLEL_FILES else defaults.cpus
    return parallel(file_parse, files, n_workers=n_workers, threadpool=threadpool, **kw)

def pkg2chunks(pkg:str,             # package name
               imports:bool=False,  # include import statements as code chunks
               n_workers:int=None,  # parse workers; 0 is serial, None picks by file count
               threadpool:bool=False, # threads rather than processes (see `_parse_files`)
               **kw                 # additional args to pass to pkg2files
)->L:
    'Return code chunks from a package with extra metadata.'
    upd_v = lambda d: d['metadata'].update(dict(package=pkg, version=version(pkg))) or d
    files = pkg2files(pkg, **kw)
    return _parse_files(files, n_workers, threadpool, imports=imports).filter(true).concat().map(upd_v)

@delegates(dir2files)
def dir2chunks(dir:str,             # directory path
               imports:bool=False,  # include import statements as code chunks
               assigns:bool=False,  # include top-level assignments as code chunks
               n_workers:int=None,  # parse workers; 0 is serial, None picks by file count
               threadpool:bool=False, # threads rather than processes (see `_parse_files`)
               **kwargs             # additional args to pass to dir2files
)->L:
    'Return code chunks from a directory with extra metadata.'
    upd_v = lambda d: d['metadata'].update(dict(dir=dir)) or d
    files = dir2files(dir, **kwargs)
    return _parse_files(files, n_workers, threadpool, imports=imports, assigns=assigns).concat().filter(true).map(upd_v)


# %% ../nbs/02_data.ipynb #256e1606821e7674
def installed_packages(nms:list=None,    # list of package names
                       pyproject:bool=False,  # restrict to pyproject.toml dependencies
                       xtras:str|None=None       # include extra groups as csv from pyproject.toml
)->L:
    'Return list of installed packages. If nms is provided, return only those packages.'
    if pyproject:
        p = repo_root().joinpath('pyproject.toml')
        if not p.exists(): return L()
        from tomllib import load
        from fastcore.basics import filter_keys, in_
        toml_data = load(p.open('rb'))
        fn = lambda s: re.split(r'[>=<!;\[]', s)[0].strip()
        tlp = L(toml_data.get('project',{}).get('dependencies',[])).map(fn)
        xtras = L.split(xtras or '', ',').filter(true)
        dg = filter_keys(toml_data.get('dependency-groups', {}), in_(xtras))
        if dg: tlp += L(dg.values()).concat().filter(lambda e: isinstance(e, str)).map(fn)
        nms = set(nms).union(tlp) if nms else tlp
    not_stdlib = lambda d: d.metadata.get('Author-email') not in ('Python', None)
    try:
        pkgs = L(nms).filter(spec).map(dist) if nms else L(dists())
        return pkgs.filter(not_stdlib).map(lambda d: d.metadata['Name'])
    except Exception as e: print(f'Error checking installed packages: {e}')

# %% ../nbs/02_data.ipynb #1c4310460fd6c8ec
def clean(q:str,  # query to be passed for fts search
          pattern=r'[*,"\(\)\^]|-(?=\S)' # regex pattern to use to replace with space
          ):
    'Clean the query by removing * and returning None for empty queries.'
    import re
    return re.sub(pattern, ' ', q).strip() or None if q.strip() else None

_BARE = re.compile(r'^[A-Za-z0-9_]+$')

def add_wc(q:str  # query to be passed for fts search
           ):
    'Add wild card * to each word in the query.`kw` uses UAX#29 segmentation, which keeps'
    esc = lambda w: w if _BARE.match(w) else '"%s"' % w.replace('"', '""')
    return ' '.join(esc(w) + '*' for w in q.split(' ') if w)

def mk_wider(q:str  # query to be passed for fts search
             ):
    '''Widen the query by joining words with OR operator.'''
    return ' OR '.join(map(lambda w: f'{w}', q.split(' ')))

_QSTOP = set('''a an the and or of to in on at by for from with as is are was were be been being this that these
those it its how do does did can could should would will what when where why which who whom whose there here
i me my we our you your he she they them their not no nor if then than so such about into over under after
before between out up down off only own same too very just also each other more most some any'''.split())

def kw(q:str,          # query to be passed for fts search
       stop:set=None   # stopwords to drop (defaults to _QSTOP)
       ):
    '''Query keywords by UAX#29 word segmentation (apsw), minus stopwords.'''
    from apsw.unicode import word_iter, casefold
    st = _QSTOP if stop is None else stop
    ws = [casefold(t) for t in word_iter(q)]
    out = [w for w in ws if len(w) > 1 and w not in st]
    return ' '.join(dict.fromkeys(out or ws))

def pre(q:str,          # query to be passed for fts search
        wc=True,        # add wild card to each word
        wide=True,      # widen the query with OR operator
        extract_kw=True, # extract keywords from the query
        pattern=r'[*,"\(\)\^]|-(?=\S)' # regex pattern to use to replace with space
        ):
    '''Preprocess the query for fts search.'''
    q = clean(q, pattern)
    if not q.strip(): return None
    if extract_kw: q = kw(q)
    if wc: q = add_wc(q)
    if wide: q = mk_wider(q)
    return q


# %% ../nbs/02_data.ipynb #jv0r083q7b
def img2png(img) -> bytes:
    'Normalise image input (PIL Image / bytes / path) to PNG bytes as RGB.'
    from PIL import Image
    import io
    if isinstance(img, (str, Path)): img = Image.open(img)
    elif isinstance(img, (bytes, bytearray)): img = Image.open(io.BytesIO(img))
    buf = io.BytesIO()
    img.convert('RGB').save(buf, format='PNG')
    return buf.getvalue()

def png_det(png: bytes):
    'Return (width, height, concatenated IDAT bytes) from a PNG.'
    w = _struct.unpack('>I', png[16:20])[0]
    h = _struct.unpack('>I', png[20:24])[0]
    idat, i = bytearray(), 8
    while i < len(png):
        ln = _struct.unpack('>I', png[i:i+4])[0]
        if png[i+4:i+8] == b'IDAT': idat.extend(png[i+8:i+8+ln])
        elif png[i+4:i+8] == b'IEND': break
        i += 12 + ln
    return w, h, bytes(idat)

def images_to_pdf(imgs,       # list of PIL Images, bytes, or file paths
                  output=None # path to save, or None to return bytes
) -> bytes:
    'Convert a list of images into a multi-page image-only PDF (one image per page).'
    pages = [png_det(img2png(img)) for img in imgs]
    N = len(pages)
    kids = ' '.join(f'{3+i*3} 0 R' for i in range(N))
    o = {
        1: b'<</Type /Catalog /Pages 2 0 R>>',
        2: f'<</Type /Pages /Kids [{kids}] /Count {N}>>'.encode(),
    }
    for i, (w, h, idat) in enumerate(pages):
        b = 3 + i * 3
        cm = f'q {w} 0 0 {h} 0 0 cm /Im1 Do Q'.encode()
        o[b]   = f'<</Type /Page /Parent 2 0 R /MediaBox [0 0 {w} {h}] /Contents {b+1} 0 R /Resources <</XObject <</Im1 {b+2} 0 R>>>>>>'.encode()
        o[b+1] = f'<</Length {len(cm)}>>'.encode() + b'\nstream\n' + cm + b'\nendstream'
        o[b+2] = (f'<</Type /XObject /Subtype /Image /Width {w} /Height {h} /ColorSpace /DeviceRGB '
                  f'/BitsPerComponent 8 /Filter /FlateDecode '
                  f'/DecodeParms <</Predictor 15 /Colors 3 /BitsPerComponent 8 /Columns {w}>> '
                  f'/Length {len(idat)}>>').encode() + b'\nstream\n' + idat + b'\nendstream'
    out, offs = b'%PDF-1.7\n', {}
    for n in sorted(o): offs[n] = len(out); out += f'{n} 0 obj\n'.encode() + o[n] + b'\nendobj\n'
    xp = len(out)
    out += (b'xref\n' + f'0 {len(o)+1}\n'.encode() + b'0000000000 65535 f \n'
            + b''.join(f'{offs[n]:010d} 00000 n \n'.encode() for n in sorted(o))
            + f'trailer\n<</Size {len(o)+1} /Root 1 0 R>>\nstartxref\n{xp}\n%%EOF\n'.encode())
    if output: open(output, 'wb').write(out)
    return out

# %% ../nbs/02_data.ipynb #6593c16e
def mv_skill_md(dry_run:bool=True, dir=None) -> None:
    'Copy bundled SKILL.md to skill directories (.agents/, .claude/, .Codex/).'
    base = Path(__file__).parent if '__file__' in globals() else Path.cwd()
    if not (src := base/'SKILL.md').exists(): return
    root = Path(ifnone(dir, repo_root() or Path.cwd()))
    ts = [root/'.agents/skills/litesearch/SKILL.md',
          root/'.claude/skills/litesearch/SKILL.md',
          root/'.Codex/skills/litesearch/SKILL.md']
    if dry_run: print(f'Copying {src} to: {list(map(str,ts))}')
    else: [p.mk_write(src.read_text(encoding='utf-8')) for p in ts]
    print(f'Installed -> {list(map(str,ts))}')
