# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_data.ipynb.

# %% auto #0
__all__ = ['skip_folder_re', 'skip_file_re', 'code_types', 'file_types', 'chunk_markdown', 'repo_root', 'spec', 'pyparse',
           'ipynb_parse', 'non_py_sigs', 'chunk_texts', 'file_parse', 'pkg2files', 'dir2files', 'pkg2chunks',
           'dir2chunks', 'installed_packages', 'clean', 'add_wc', 'mk_wider', 'kw', 'pre', 'img2png', 'png_det',
           'images_to_pdf']

# %% ../nbs/02_data.ipynb #8a1e955269e0d234
from fastcore.all import L, concat, patch, ifnone, Path, delegates, globtastic, parallel, type2str, first
from pdf_oxide import PdfDocument
import struct as _struct

# %% ../nbs/02_data.ipynb #fc014ece1162af13
@patch
def pdf_texts(doc:PdfDocument, st=0, end=None) -> L:
    'Extract plain text from each page.'
    return L(range(st, ifnone(end, doc.page_count()))).map(doc.extract_text)

@patch
def pdf_links(doc:PdfDocument, st=0, end=None) -> L:
    'Extract hyperlinks from each page as a list of URI strings.'
    pages = range(st, ifnone(end, doc.page_count()))
    ann = L(pages).map(lambda i: doc.get_annotations(i))
    return ann.concat().filter(lambda a: 'action_uri' in a).map(lambda a: a['action_uri'])

@patch
def pdf_images(doc:PdfDocument, st=0, end=None, output_dir=None) -> L:
    'Extract images — returns metadata dicts, or saves to output_dir if provided.'
    pages = range(st, ifnone(end, doc.page_count()))
    if output_dir:
        Path(output_dir).mkdir(exist_ok=True)
        return L(pages).map(lambda i: doc.to_plain_text(i, include_images=True, image_output_dir=str(output_dir)))
    return L(pages).map(lambda i: doc.extract_images(i)).concat()

@patch
def pdf_markdown(doc:PdfDocument, st=0, end=None) -> L:
    'Convert pages to markdown with headings and tables detected.'
    return L(range(st, ifnone(end, doc.page_count()))).map(lambda i: doc.to_markdown(i, detect_headings=True))

@patch
def pdf_tables(doc:PdfDocument, st=0, end=None) -> L:
    'Extract structured tables (rows/cells/bbox) from each page.'
    return L(range(st, ifnone(end, doc.page_count()))).map(lambda i: doc.extract_tables(i)).concat()

@patch
def pdf_spans(doc:PdfDocument, st=0, end=None) -> L:
    'Extract text spans with font metadata (size, weight, bbox) per page.'
    return L(range(st, ifnone(end, doc.page_count()))).map(lambda i: doc.extract_spans(i)).concat()

# %% ../nbs/02_data.ipynb #chunk_markdown_cell
def chunk_markdown(text:str,     # markdown text (e.g. from pdf_markdown())
) -> L:
	'Split markdown into paragraph chunks on blank lines; drop short fragments.'
	from chonkie import RecursiveChunker
	r=RecursiveChunker.from_recipe('markdown')
	return L(r(text)).map(lambda c: c.text)

@patch
@delegates(chunk_markdown)
def pdf_chunks(self:PdfDocument, # PDF document
               st=0,             # start page
               end=None,         # end page (exclusive)
               **kwargs
               ) -> L:
	'Markdown-chunked text from each page; yields (page, chunk_idx, text) tuples.'
	return L((pg, ci, chunk)
	         for pg, md in enumerate(self.pdf_markdown(st, end))
	         for ci, chunk in enumerate(chunk_markdown(md, **kwargs)))

# %% ../nbs/02_data.ipynb #171a3906ce544f95
from importlib.util import find_spec as fs
from importlib.metadata import distribution as dist, distributions as dists, version
from importlib.machinery import ModuleSpec
import ast, re
from ast import get_source_segment as gs
from codesigs import file_sigs
from fastcore.basics import true
from fastcore.nbio import read_nb

# %% ../nbs/02_data.ipynb #2d62e37b470a1055
skip_folder_re = r'^[._]|^(?:tests?|examples?|docs?|build|dist)$'
skip_file_re = r'^[._]|^(?:setup\.py|conftest\.py)$'
code_types = 'py,js,ts,jsx,tsx,java,go,cs,ruby,php,swift,kt,kts,rs,scala,lua'
file_types = code_types + ',md,txt,pdf,ipynb'

def repo_root() -> Path:
	'Find the root of the current git repository, or None if not in a repo.'
	return first((Path.cwd(), *Path.cwd().parents), lambda p: (p/'.git').exists())

def spec(pkg:str) -> ModuleSpec | None:
	'Return the importlib ModuleSpec for a package, or None if not found.'
	try: return fs(pkg) or fs(pkg.replace('-', '_')) or fs(dist(pkg).read_text('top_level.txt').splitlines()[0])
	except ModuleNotFoundError: return None

def pyparse(p:Path=None,    # path to a python file
            code:str=None,  # code string to parse
            imports=False,   # include import statements as code chunks
            assigns=False       # include top-level assignments as code chunks
) -> L:
    'Parse a code string or python file and return code chunks as list of dicts with content and metadata.'
    assert bool(code) ^ bool(p), 'Either code or p must be provided, not both.'
    try: code = Path(p).read_text(encoding='utf-8') if not code else code
    except UnicodeDecodeError: return L()
    tree=ast.parse(code)
    [setattr(c,'parent',n) for n in ast.walk(tree) for c in ast.iter_child_nodes(n)]
    def meta(xtra=None): return dict(path=p,uploaded_at=Path(p).stat().st_mtime if p else None,**ifnone(xtra, {}))
    def n2c(n):
	    return dict(content=gs(code, n).strip(), metadata=meta(dict(name=getattr(n,'name',None),lang='.py',
            type=type2str(n.__class__), lineno=getattr(n,'lineno',None), end_lineno=getattr(n,'end_lineno',None))))
    def is_mod(n): return isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
    def is_assign(n): return assigns and isinstance(n, (ast.Assign, ast.AnnAssign)) and n.value
    def is_p_mod(n): return getattr(getattr(n,'parent',None),'__class__',None) == ast.Module
    def is_allowed(n): return is_p_mod(n) and (is_mod(n) or is_assign(n) or (imports and isinstance(n, ast.ImportFrom)))
    return L(ast.walk(tree)).filter(is_allowed).map(n2c)

def ipynb_parse(p):
	'Parse ipynb files'
	def meta_(): return dict(path=p, uploaded_at=Path(p).stat().st_mtime, lang=p.suffix)
	fn = lambda c: dict(content=c['source'], metadata = meta_() | dict(type=c['cell_type']))
	return L(read_nb(p).cells).map(fn)

def non_py_sigs(p):
	'Signatures for paths that are not python code files using codesigs'
	def meta_(): return dict(path=p, uploaded_at=Path(p).stat().st_mtime, lang=p.suffix)
	return L(file_sigs(p)).map(lambda o: dict(content=o, metadata=meta_()))

def chunk_texts(text:str):
	'Chunk texts using Fast Chunker'
	from chonkie import FastChunker
	return L(FastChunker(delimiters='\n\n')(text)).map(lambda c: c.text)

@delegates(pyparse)
def file_parse(p:Path=None,  # path to a code file
               **kwargs      # additional args to pass to pyparse
               ) -> L:
    'Parse a code file or code string and return code chunks with metadata.'
    if p.suffix == '.py': return pyparse(p, **kwargs)
    if p.suffix == '.ipynb': return ipynb_parse(p)
    if p.suffix[1:] in code_types.split(','): return non_py_sigs(p)
    def meta_(): return dict(path=p, uploaded_at=Path(p).stat().st_mtime, lang=p.suffix)
    if p.suffix == '.pdf': return PdfDocument(p).pdf_chunks().map(lambda c: dict(content=c[2], metadata=meta_()))
    fn = lambda c: dict(content=c,metadata=meta_())
    if p.suffix  == '.md': return chunk_markdown(p.read_text(encoding='utf-8')).map(fn)
    if p.suffix == '.txt': return chunk_texts(p.read_text(encoding='utf-8')).map(fn)
    return L()

# %% ../nbs/02_data.ipynb #76e3e47dd73aec50
@delegates(globtastic)
def pkg2files(pkg:str,								# package name
              skip_file_re=skip_file_re,  # regex to skip files
              skip_folder_re=skip_folder_re,  # regex to skip folders
              func=Path,						    # function to apply to file paths (e.g. Path or str)
			  **kwargs								# additional args to pass to globtastic
)->L:
	'Return list of python files in a package excluding tests and setup files.'
	if not (nm := spec(pkg)): return L()
	return globtastic(Path(nm.origin).parent, folder_re=nm.name, skip_folder_re=skip_folder_re,
	                  skip_file_re=skip_file_re, func=func, **kwargs)

# %% ../nbs/02_data.ipynb #71185cd58a7ad122
@delegates(globtastic)
def dir2files(dir:str,  # package name
              skip_file_re=skip_file_re,  # regex to skip files
              skip_folder_re=skip_folder_re,  # regex to skip folders
              func=Path,  # function to apply to file paths (e.g. Path or str)
              **kwargs  # additional args to pass to globtastic
              )->L:
	'Return list of python files in a package excluding tests and setup files.'
	if not (rt :=Path(dir)).exists(): return L()
	return globtastic(rt, skip_folder_re=skip_folder_re, skip_file_re=skip_file_re, func=func, **kwargs)

# %% ../nbs/02_data.ipynb #55c525653e25a703
def pkg2chunks(pkg:str,             # package name
               imports:bool=False,  # include import statements as code chunks
               **kw                 # additional args to pass to pkg2files
)->L:
    'Return code chunks from a package with extra metadata.'
    upd_v = lambda d: d['metadata'].update(dict(package=pkg, version=version(pkg))) or d
    return parallel(file_parse, pkg2files(pkg,**kw), threadpool=True, imports=imports).filter(true).concat().map(upd_v)

@delegates(dir2files)
def dir2chunks(dir:str,             # directory path
               imports:bool=False,  # include import statements as code chunks
               assigns:bool=False,  # include top-level assignments as code chunks
               **kwargs             # additional args to pass to dir2files
)->L:
    'Return code chunks from a directory with extra metadata.'
    upd_v = lambda d: d['metadata'].update(dict(dir=dir)) or d
    pykw = dict(imports=imports, assigns=assigns)
    return parallel(file_parse, dir2files(dir, **kwargs), threadpool=True, **pykw).concat().filter(true).map(upd_v)

# %% ../nbs/02_data.ipynb #7652cb1d1f39fadc
def installed_packages(nms:list=None,    # list of package names
                       pyproject:bool=False  # restrict to pyproject.toml dependencies
                       )->L:
    'Return list of installed packages. If nms is provided, return only those packages.'
    if pyproject:
        p = repo_root().joinpath('pyproject.toml')
        if not p.exists(): return L()
        from tomllib import load
        tlp = L(load(p.open('rb')).get('project',{}).get('dependencies',[]))
        tlp = tlp.map(lambda s: re.split(r'[>=<!;\[]', s)[0].strip())
        nms = set(nms).union(tlp) if nms else tlp
    not_stdlib = lambda d: d.metadata.get('Author-email') not in ('Python', None)
    try:
        pkgs = L(nms).filter(spec).map(dist) if nms else L(dists())
        return pkgs.filter(not_stdlib).map(lambda d: d.metadata['Name'])
    except Exception as e: print(f'Error checking installed packages: {e}')

# %% ../nbs/02_data.ipynb #f887a2d1e48c7e1d
def clean(q:str  # query to be passed for fts search
          ):
    '''Clean the query by removing * and returning None for empty queries.'''
    return q.replace('*', '') if q.strip() else None

def add_wc(q:str  # query to be passed for fts search
           ):
    '''Add wild card * to each word in the query.'''
    return ' '.join(map(lambda w: w + '*', q.split(' ')))

def mk_wider(q:str  # query to be passed for fts search
             ):
    '''Widen the query by joining words with OR operator.'''
    return ' OR '.join(map(lambda w: f'{w}', q.split(' ')))

def kw(q:str  # query to be passed for fts search
       ):
    '''Extract keywords from the query using YAKE library.'''
    from yake import KeywordExtractor as KW
    return ' '.join((set(concat([k.split(' ') for k, s in KW().extract_keywords(q)]))))

def pre(q:str,          # query to be passed for fts search
        wc=True,        # add wild card to each word
        wide=True,      # widen the query with OR operator
        extract_kw=True # extract keywords from the query
        ):
    '''Preprocess the query for fts search.'''
    q = clean(q)
    if not q.strip(): return None
    if extract_kw: q = kw(q)
    if wc: q = add_wc(q)
    if wide: q = mk_wider(q)
    return q

# %% ../nbs/02_data.ipynb #jv0r083q7b
def img2png(img) -> bytes:
    'Normalise image input (PIL Image / bytes / path) to PNG bytes as RGB.'
    from PIL import Image
    import io
    if isinstance(img, (str, Path)): img = Image.open(img)
    elif isinstance(img, (bytes, bytearray)): img = Image.open(io.BytesIO(img))
    buf = io.BytesIO()
    img.convert('RGB').save(buf, format='PNG')
    return buf.getvalue()

def png_det(png: bytes):
    'Return (width, height, concatenated IDAT bytes) from a PNG.'
    w = _struct.unpack('>I', png[16:20])[0]
    h = _struct.unpack('>I', png[20:24])[0]
    idat, i = bytearray(), 8
    while i < len(png):
        ln = _struct.unpack('>I', png[i:i+4])[0]
        if png[i+4:i+8] == b'IDAT': idat.extend(png[i+8:i+8+ln])
        elif png[i+4:i+8] == b'IEND': break
        i += 12 + ln
    return w, h, bytes(idat)

def images_to_pdf(imgs,       # list of PIL Images, bytes, or file paths
                  output=None # path to save, or None to return bytes
) -> bytes:
    'Convert a list of images into a multi-page image-only PDF (one image per page).'
    pages = [png_det(img2png(img)) for img in imgs]
    N = len(pages)
    kids = ' '.join(f'{3+i*3} 0 R' for i in range(N))
    o = {
        1: b'<</Type /Catalog /Pages 2 0 R>>',
        2: f'<</Type /Pages /Kids [{kids}] /Count {N}>>'.encode(),
    }
    for i, (w, h, idat) in enumerate(pages):
        b = 3 + i * 3
        cm = f'q {w} 0 0 {h} 0 0 cm /Im1 Do Q'.encode()
        o[b]   = f'<</Type /Page /Parent 2 0 R /MediaBox [0 0 {w} {h}] /Contents {b+1} 0 R /Resources <</XObject <</Im1 {b+2} 0 R>>>>>>'.encode()
        o[b+1] = f'<</Length {len(cm)}>>'.encode() + b'\nstream\n' + cm + b'\nendstream'
        o[b+2] = (f'<</Type /XObject /Subtype /Image /Width {w} /Height {h} /ColorSpace /DeviceRGB '
                  f'/BitsPerComponent 8 /Filter /FlateDecode '
                  f'/DecodeParms <</Predictor 15 /Colors 3 /BitsPerComponent 8 /Columns {w}>> '
                  f'/Length {len(idat)}>>').encode() + b'\nstream\n' + idat + b'\nendstream'
    out, offs = b'%PDF-1.7\n', {}
    for n in sorted(o): offs[n] = len(out); out += f'{n} 0 obj\n'.encode() + o[n] + b'\nendobj\n'
    xp = len(out)
    out += (b'xref\n' + f'0 {len(o)+1}\n'.encode() + b'0000000000 65535 f \n'
            + b''.join(f'{offs[n]:010d} 00000 n \n'.encode() for n in sorted(o))
            + f'trailer\n<</Size {len(o)+1} /Root 1 0 R>>\nstartxref\n{xp}\n%%EOF\n'.encode())
    if output: open(output, 'wb').write(out)
    return out
