# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_graph.ipynb.

# %% auto #0
__all__ = ['MIN_PARALLEL_CHUNKS', 'hash_embed', 'code_entities', 'prose_windows', 'text_entities', 'build_graph',
           'resolve_entities', 'cooccur_edges', 'ctfidf_labels', 'topic_nodes', 'rrf_all', 'graph_stats']

# %% ../nbs/05_graph.ipynb #ab82e9d12af8898f
from fastcore.all import Path, patch, merge, ifnone, first, L, AttrDict, defaults
from fastcore.parallel import ProcessPoolExecutor
from fastlite import Database
from apswutils.db import Table
import ast, math, re, zlib
from functools import lru_cache
import numpy as np

from .core import _in, _rid, _slug, _np_dtype, process_content, write_txn, upsert_all

# %% ../nbs/05_graph.ipynb #e2556b625e937d53
@patch
def get_graph(self:Database,
              store:str='store',   # chunk store the graph is built over
              prefix:str=None,     # table prefix (default: '' for 'store', else '<store>_')
              ann:bool=True,       # register an ANN index on the entity store (needed for resolution)
              **kw):               # extra typed columns for the entity store
    'Create the entity/mention/edge tables for a chunk store. Idempotent; returns the tables.'
    p = prefix if prefix is not None else ('' if store == 'store' else f'{store}_')
    en, mn, eg = f'{p}entities', f'{p}mentions', f'{p}edges'
    ents = self.get_store(en, hash=True, ann=ann, kind=str, canon=str, freq=int, **kw)
    self.t[mn].create(chunk_id=str, entity_id=str, surface=str, n=int,
                      pk=('chunk_id', 'entity_id'), if_not_exists=True)
    self.t[eg].create(src=str, dst=str, rel=str, weight=float, n=int,
                      pk=('src', 'dst', 'rel'), if_not_exists=True)
    for t, c in ((mn, 'entity_id'), (mn, 'chunk_id'), (eg, 'src'), (eg, 'dst')):
        self.t[t].create_index([c], if_not_exists=True)
    return AttrDict(entities=ents, mentions=self.t[mn], edges=self.t[eg], store=self.t[store], prefix=p)

# %% ../nbs/05_graph.ipynb #673ffc3a5da7b038
_DET = re.compile(r'^(the|a|an|this|that|these|those|its|their|our|your|his|her)\s+', re.I)
_WS  = re.compile(r'\s+')
_PRON = {'it','its','we','our','they','their','he','she','you','i','me','us','them','this','that',
         'these','those','which','who','what','there','here','one','ones','something','anything'}
_TOK = re.compile(r'[a-z0-9]+')
_NUM = re.compile(r'\d+')

def _norm(s):
    'Canonical surface form for a mention; None when the phrase is not entity-like.'
    if not s: return None
    s = _WS.sub(' ', s).strip().strip('.,;:!?()[]{}"\'`')
    s = _DET.sub('', s).strip()
    s = re.sub(r"'s$", '', s).strip()
    if not (2 <= len(s) <= 60): return None
    if len(s.split()) > 5: return None
    if s.lower() in _PRON: return None
    # any *letter*, in any script — not `[A-Za-z]`. The intent is to drop pure numbers and
    # punctuation, but spelling it in ASCII silently rejected every non-Latin writing system:
    # `धर्मक्षेत्रे` normalised to None, so `build_graph` on a Devanagari corpus produced an empty
    # graph however good its term extraction was.
    if not any(c.isalpha() for c in s): return None
    return s.lower()

@lru_cache(maxsize=1<<17)
def _toks(s):
    'Tokens for the lexical guard. UAX#29 treats `_` as a word joiner, so `fts_search` stays one'
    try: from apsw.unicode import word_iter, casefold
    except ImportError: return frozenset(_TOK.findall(s.lower()))
    return frozenset(casefold(t) for t in word_iter(s or '') if any(c.isalnum() for c in t))

@lru_cache(maxsize=1<<17)
def _acr(s):  return ''.join(w[0] for w in s.split() if w)

@lru_cache(maxsize=1<<17)
def _nums(s): return frozenset(_NUM.findall(s))

def _sentences(text):
    'UAX#29 sentence split via apsw; falls back to the whole text as one window.'
    try: from apsw.unicode import sentence_iter
    except ImportError: return [text]
    return [s for s in (x.strip() for x in sentence_iter(text)) if s]

def _jac(a, b):
    A, B = _toks(a), _toks(b)
    u = len(A) + len(B) - len(A & B)
    return len(A & B) / u if u else 0.0

def _lex_ok(a, b, lex=0.34, cover=0.5):
    '''Lexical guard on a proposed merge.

    Ordered by what actually decides. The token overlap settles all but a handful of candidate
    pairs and costs two cached frozensets; the digit and acronym tests allocate four throwaway
    objects per call and can only ever *veto* or *rescue* a pair the tokens have already ruled on.
    Running them first meant paying for them on the ~99% of pairs the tokens reject outright — 300k
    `_acr` calls and 300k `findall`s per resolve, to change 900 answers. Same answer on every pair;
    the expensive tests just run on far fewer of them.'''
    if a == b: return True
    A, B = _toks(a), _toks(b)
    ok = False
    if A and B:
        inter = len(A & B)
        # union without building it: |A|+|B|-|A&B|, and A,B are non-empty so it cannot be zero
        ok = ((inter == min(len(A), len(B)) and inter/max(len(A), len(B)) >= cover)
              or inter/(len(A) + len(B) - inter) >= lex)
    # an acronym pair shares no tokens by construction, so it is only reachable once tokens fail
    if not ok and not (_acr(a) == b.lower() or _acr(b) == a.lower()): return False
    return _nums(a) == _nums(b)


# %% ../nbs/05_graph.ipynb #eecb2932441a0d19
def hash_embed(texts,            # iterable of strings
               ndim:int=256,     # output dimensions
               ngram=(3,5),      # char n-gram range
               dtype=np.float16):
    '''Deterministic char-n-gram hashing embedder — no model, no download.

    The hash is unchanged and so are the vectors, bit for bit: what changed is that the n-gram
    hashes are collected and binned by one `bincount` instead of fancy-indexing a float row per
    n-gram, and that an all-ASCII string is encoded once and sliced as bytes rather than encoded
    once per n-gram. n-grams are counted in *characters*, so the byte path is only taken when the
    encoding is length-preserving — otherwise a Devanagari name would be cut mid-codepoint.'''
    lo, hi = ngram
    txts = list(L(texts))
    out, crc = np.zeros((len(txts), ndim), dtype=np.float32), zlib.crc32
    for i, t in enumerate(txts):
        s = ' ' + _WS.sub(' ', (t or '').lower().strip()) + ' '
        b = s.encode()
        if len(b) == len(s): h = [crc(b[j:j+n]) % ndim for n in range(lo, hi+1) for j in range(len(b)-n+1)]
        else:                h = [crc(s[j:j+n].encode()) % ndim for n in range(lo, hi+1) for j in range(len(s)-n+1)]
        if h: out[i] = np.bincount(h, minlength=ndim)
    out /= np.clip(np.linalg.norm(out, axis=1, keepdims=True), 1e-12, None)
    return out.astype(dtype)


# %% ../nbs/05_graph.ipynb #5952ad1336601711
_PY_SKIP = {'self','cls','super','print','len','str','int','float','bool','list','dict','set','tuple',
            'range','enumerate','zip','map','filter','isinstance','getattr','setattr','hasattr','type',
            'format','join','append','get','items','keys','values','open','sorted','sum','min','max'}

def _def_name(chunk):
    'Symbol defined by a code chunk, from pyparse metadata or the chunk source itself.'
    md = chunk.get('metadata') or {}
    if isinstance(md, dict) and md.get('name'): return md['name']
    try: tree = ast.parse(chunk['content'])
    except SyntaxError: return None
    n = first(tree.body, lambda x: isinstance(x, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)))
    return getattr(n, 'name', None)

def code_entities(chunk):
    'Exact symbols for a python chunk: (defined, called, imported). AST-derived, no model.'
    try: tree = ast.parse(chunk['content'])
    except (SyntaxError, ValueError): return None, L(), L()
    calls, imps = L(), L()
    for n in ast.walk(tree):
        if isinstance(n, ast.Call):
            f = n.func
            if   isinstance(f, ast.Name):      calls.append(f.id)
            elif isinstance(f, ast.Attribute): calls.append(f.attr)
        elif isinstance(n, ast.Import):
            imps += [a.name.split('.')[0] for a in n.names]
        elif isinstance(n, ast.ImportFrom):
            if n.module: imps.append(n.module.split('.')[0])
    keep = lambda s: s and s not in _PY_SKIP and not s.startswith('_') and len(s) > 2
    return _def_name(chunk), calls.filter(keep).unique(), imps.filter(keep).unique()

# %% ../nbs/05_graph.ipynb #d337238a913ea5d3
def _yake_terms(text, topk=12):
    'Keyphrases via yake — zero model, zero labels, and the default prose extractor.'
    try: from yake import KeywordExtractor
    except ImportError: return L()
    try: return L(KeywordExtractor(n=3, top=topk).extract_keywords(text)).map(lambda kv: kv[0])
    except Exception: return L()

def prose_windows(text,             # chunk text
                  topk=12,          # keyphrase count
                  terms_fn=None):   # (text, topk) -> terms; None -> yake
    'Entity surfaces grouped into co-occurrence windows — one per sentence.'
    terms = (terms_fn or _yake_terms)(text, topk)
    if not terms: return L()
    # the term list is fixed for the whole chunk, so it is lowercased once here rather than once
    # per sentence — `t.lower()` sat in the inner loop and ran topk times for every sentence
    low = [(t, t.lower()) for t in terms]
    wins = []
    for s in _sentences(text):
        sl = s.lower()
        hit = L([(t, 'keyphrase') for t, tl in low if tl in sl])
        if hit: wins.append(hit)
    return L(wins)

def text_entities(text, **kw):
    'Entity surfaces for a prose chunk, flattened across windows. Returns L of (surface, kind).'
    seen, out = set(), L()
    for w in prose_windows(text, **kw):
        for s, k in w:
            n = _norm(s)
            if n and n not in seen: seen.add(n); out.append((s, k))
    return out


# %% ../nbs/05_graph.ipynb #8e1af70983a03a3f
_CODE_TYPES = {'FunctionDef','AsyncFunctionDef','ClassDef'}

def _is_code(chunk):
    md = chunk.get('metadata') or {}
    if not isinstance(md, dict): return False
    return md.get('lang') == '.py' or md.get('type') in _CODE_TYPES

def _pmi_edges(wins,              # list of entity-id sets (one per co-occurrence window)
               min_n=2,           # min co-occurrence count
               min_npmi=0.15,     # min normalized PMI
               max_df=0.4,        # drop entities present in more than this fraction of windows
               max_degree=48,     # keep only the strongest edges per node
               rel='cooc'):
    'Normalized-PMI co-occurrence edges over windows. max_df is what kills hub terms like "section".'
    n = len(wins)
    if n < 2: return []
    if hasattr(wins, 'pair_counts'):                 # a _WindowStore counts on disk, same numbers
        cnt = wins.entity_counts()
        hub = {e for e, c in cnt.items() if c / n > max_df}
        pairs = ((a, b, c) for a, b, c in wins.pair_counts(hub, min_n))
    else:
        cnt = {}
        for w in wins:
            for e in w: cnt[e] = cnt.get(e, 0) + 1
        hub = {e for e, c in cnt.items() if c / n > max_df}
        pair = {}
        for w in wins:
            es = sorted(e for e in w if e not in hub)
            for i, a in enumerate(es):
                for b in es[i+1:]: pair[(a, b)] = pair.get((a, b), 0) + 1
        pairs = ((a, b, c) for (a, b), c in pair.items())
    out = []
    for a, b, c in pairs:
        if c < min_n: continue
        pa, pb, pab = cnt[a]/n, cnt[b]/n, c/n
        npmi = math.log(pab/(pa*pb)) / (-math.log(pab)) if 0 < pab < 1 else 0.0
        if npmi < min_npmi: continue
        out.append(dict(src=a, dst=b, rel=rel, weight=round(npmi, 5), n=c))
    if max_degree:
        # (src, dst) breaks weight ties explicitly. Without it the survivors of the degree cap depend
        # on the order pairs were counted in, which differs between the in-memory dict and SQLite's
        # group-by — 30 of 2,707 edges on a 500-chunk corpus, all of them ties, none of them wrong.
        deg, kept = {}, []
        for e in sorted(out, key=lambda r: (-r['weight'], r['src'], r['dst'])):
            if deg.get(e['src'], 0) < max_degree and deg.get(e['dst'], 0) < max_degree:
                deg[e['src']] = deg.get(e['src'], 0)+1; deg[e['dst']] = deg.get(e['dst'], 0)+1
                kept.append(e)
        out = kept
    return out

# Below this many prose chunks in one drain, a process pool costs more to start than it saves.
MIN_PARALLEL_CHUNKS = 200

def _prose_job(txt):
    '''Windows for one prose chunk, as plain tuples. Module level so a process pool can pickle it.

    Only text crosses the boundary and only tuples come back — no database handle, nothing that a
    fork would have to keep consistent.'''
    return [[(s, k) for s, k in w] for w in prose_windows(txt)]

def _n_workers(n, n_workers):
    'Resolve `n_workers`: None picks by size, 0 stays serial, anything else is taken literally.'
    if n_workers is not None: return n_workers
    return 0 if n < MIN_PARALLEL_CHUNKS else defaults.cpus

class _WindowStore:
    '''Co-occurrence windows kept in a SQLite table instead of a python list.

    `_pmi_edges` already walks its windows twice — once to count entities, once to count pairs, and
    it has to be twice because the hub cut-off is not known until the first pass finishes. That is
    the only thing it needs from a list, so anything with `__len__` and a re-iterable `__iter__`
    will do, and a table costs a bounded amount of memory instead of holding every window of the
    corpus at once. Windows are the part of `build_graph` that grows without limit: entity
    vocabulary saturates, mentions are flushed per batch, windows are one per sentence forever.'''
    def __init__(self, db, name):
        self.db, self.name, self.n, self._w = db, name, 0, 0
        db.conn.execute(f'create table if not exists {name} (w integer, e text)')
        db.conn.execute(f'delete from {name}')
    def extend(self, wins):
        rows = [(self._w + i, e) for i, w in enumerate(wins) for e in w if e]
        if not rows: self._w += len(wins); self.n += len(wins); return
        with write_txn(self.db): self.db.conn.executemany(f'insert into {self.name} values (?,?)', rows)
        self._w += len(wins); self.n += len(wins)
    def entity_counts(self):
        'entity -> windows containing it. Bounded by vocabulary, which saturates; safe in memory.'
        return dict(self.db.conn.execute(f'select e, count(*) from {self.name} group by e'))
    def pair_counts(self, hub, min_n):
        """Co-occurrence count per unordered pair, aggregated on disk.

        The last unbounded structure in the build. Windows are one per sentence and pairs are
        quadratic in window size, so the dict `_pmi_edges` builds tracks the corpus even after the
        windows themselves stop being held — grouping in SQLite spills to a temp b-tree instead of
        to RSS, and `min_n` is applied by the same pass rather than after it."""
        c = self.db.conn
        c.execute(f'create index if not exists {self.name}_w on {self.name}(w)')
        c.execute(f'create temp table if not exists {self.name}_hub (e text primary key)')
        c.execute(f'delete from {self.name}_hub')
        if hub: c.executemany(f'insert or ignore into {self.name}_hub values (?)', [(e,) for e in hub])
        return c.execute(f'''select a.e, b.e, count(*) c from {self.name} a
              join {self.name} b on a.w = b.w and a.e < b.e
              where a.e not in (select e from {self.name}_hub)
                and b.e not in (select e from {self.name}_hub)
              group by a.e, b.e having c >= {int(min_n)}''')
    def __len__(self): return self.n
    def __iter__(self):
        cur, w, acc = self.db.conn.execute(f'select w, e from {self.name} order by w'), None, set()
        for wi, e in cur:
            if wi != w:
                if w is not None: yield acc
                w, acc = wi, set()
            acc.add(e)
        if w is not None: yield acc
    def drop(self):
        self.db.conn.execute(f'drop table if exists {self.name}')
        self.db.conn.execute(f'drop table if exists temp.{self.name}_hub')

def build_graph(db,                  # Database with a chunk store
                chunks,              # chunk dicts ({'content','metadata'}) as returned by dir2chunks/pkg2chunks
                store='store',       # chunk store name
                prefix=None,         # graph table prefix
                terms_fn=None,       # (text, topk) -> terms, replacing yake (see `sanskrit_terms`)
                emb_fn=None,         # embedder for entity names (required for resolve_entities)
                code=True,           # extract AST symbols from code chunks
                prose=True,          # extract surfaces from prose chunks
                cooc=True,           # also write PMI co-occurrence edges over sentence windows
                min_n=2,             # min co-occurrence count
                min_npmi=0.15,       # min normalized PMI
                max_df=0.4,          # drop entities present in >max_df of windows
                max_degree=48,       # max cooc edges kept per node
                batch:int=None,      # chunks per flush; keeps windows on disk instead of in memory
                n_workers:int=None): # extraction workers; 0 is serial, None picks by queue size
    '''Extract entities + mentions + edges (exact for code, PMI co-occurrence for prose) from chunks.

    `batch` is what makes a large corpus finish. Left as None everything accumulates in memory for
    the whole call, which is fine for a package or a few thousand pages and is not fine for a
    corpus: windows are one per sentence and never stop arriving, so memory tracks the corpus with
    no bound. Set it and mentions are flushed every `batch` chunks and windows go to a scratch
    table, which `_pmi_edges` reads back twice exactly as it would a list. The edges are identical
    either way — the batched path is a different place to keep the same numbers.

    `n_workers` spreads extraction across processes, which is where a build spends 88% of its time.
    Use it with `batch` large enough to be worth a pool: the queue is drained once per batch, so a
    small `batch` pays pool startup repeatedly for very little work.'''
    g = db.get_graph(store, prefix)
    ents, mens, edges = {}, {}, {}
    wins = _WindowStore(db, f'{g.prefix}_win_scratch') if batch else []
    def ent(name, kind):
        'Register an entity by canonical name, returning its hash id.'
        n = _norm(name)
        if not n: return None
        i = _slug(n)
        e = ents.setdefault(i, dict(content=n, kind=kind, freq=0, canon=i))
        e['freq'] += 1
        return i
    def men(cid, eid, surface):
        if not (cid and eid): return
        m = mens.setdefault((cid, eid), dict(chunk_id=cid, entity_id=eid, surface=surface, n=0))
        m['n'] += 1
    def edge(s, d, rel, w=1.0):
        if not (s and d) or s == d: return
        e = edges.setdefault((s, d, rel), dict(src=s, dst=d, rel=rel, weight=0.0, n=0))
        e['weight'] += w; e['n'] += 1
    def flush_mentions():
        'Mentions are complete once their chunk is processed, so they need not wait for the corpus.'
        if not mens: return
        upsert_all(g.mentions, mens.values(), ('chunk_id','entity_id'))
        mens.clear()

    pend = []                                   # windows waiting for the next flush
    def add_wins(ws):
        if batch: pend.extend(ws)
        else: wins.extend(ws)

    prose_q, pool = [], None
    def prose_wins():
        '''Windows per queued prose chunk, over a process pool once there are enough to pay for one.

        Extraction is 88% of a build and is a pure function of the chunk text, so this is a map
        with a cheap serial reduce after it. Processes, not threads: yake is python and holds the
        GIL end to end, so a thread pool contends rather than overlaps.

        The pool is opened once per *call*, not once per drain. `parallel` opens and closes a
        `ProcessPoolExecutor` around every invocation and `drain_prose` runs once per `batch`, so
        the two arguments that exist to make a large corpus finish were each making the other
        worse: 2,000 chunks at `batch=200` spawned forty workers to do the work of four, and spent
        7.7s extracting what one pool extracts in 5.1s.

        Order is preserved by both pools, and the reduce depends on it: `ents.setdefault` keeps the
        `kind` of an entity's *first* mention, so a reordered stream would relabel entities.'''
        nonlocal pool
        nw = 0 if terms_fn is not None else _n_workers(len(prose_q), n_workers)
        if nw and nw > 1:
            if pool is None: pool = ProcessPoolExecutor(nw)
            # both sides materialised: `drain_prose` clears the queue these are drawn from
            cids, txts = [c for c, _ in prose_q], [t for _, t in prose_q]
            return zip(cids, pool.map(_prose_job, txts))
        return ((cid, prose_windows(txt, terms_fn=terms_fn)) for cid, txt in prose_q)

    def drain_prose():
        'Turn the queued prose chunks into entities, mentions and windows, then clear the queue.'
        for cid, wl in prose_wins():
            for win in wl:
                w = set()
                for surf, kind in win:
                    i = ent(surf, kind)
                    if i: men(cid, i, surf); w.add(i)
                if len(w) > 1: add_wins([w])
        prose_q.clear()

    n_seen = 0
    # iterated, not `L(chunks)`: wrapping the input in an L materialises it, so a caller who hands in
    # a generator to keep a corpus off the heap had it read into a list before the first chunk was
    # touched. With this, `batch` plus a generator means the corpus never exists in memory at once.
    try:
        for c in ([chunks] if isinstance(chunks, dict) else chunks):
            txt = c.get('content')
            if not (txt and txt.strip()): continue
            cid = c.get('id') or _slug(txt)
            if code and _is_code(c):
                dname, calls, imps = code_entities(c)
                did = ent(dname, 'symbol') if dname else None
                if did: men(cid, did, dname)
                w = {did} if did else set()
                for nm in calls:
                    i = ent(nm, 'symbol'); men(cid, i, nm); edge(did, i, 'calls'); w.add(i)
                for nm in imps:
                    i = ent(nm, 'module'); men(cid, i, nm); edge(did, i, 'imports'); w.add(i)
                if len(w) > 1: add_wins([w - {None}])
            elif prose: prose_q.append((cid, txt))
            n_seen += 1
            if batch and n_seen % batch == 0:
                drain_prose(); wins.extend(pend); pend.clear(); flush_mentions()

        drain_prose()
    finally:
        if pool is not None: pool.shutdown()
    if batch: wins.extend(pend); pend.clear()

    rows = list(ents.values())
    if cooc and len(wins):
        for e in _pmi_edges(wins, min_n, min_npmi, max_df, max_degree):
            edges[(e['src'], e['dst'], e['rel'])] = e
    n_wins = len(wins)
    if batch: wins.drop()
    with write_txn(db):
        if rows:
            if emb_fn: process_content(g.entities, rows, embed=True, emb_fn=emb_fn)
            else:      g.entities.insert_all(rows, upsert=True, hash_id='id', hash_id_columns=['content'])
        if mens:  upsert_all(g.mentions, mens.values(), ('chunk_id','entity_id'))
        if edges: upsert_all(g.edges, edges.values(), ('src','dst','rel'))
    if emb_fn and rows: g.entities.rebuild_index()
    return dict(entities=len(rows), mentions=first(db.q(f'select count(*) c from {g.mentions.name}'))['c'],
                edges=len(edges), windows=n_wins)


# %% ../nbs/05_graph.ipynb #f1e0bc8fd1ac5d91
_EXACT_KINDS = ('symbol', 'module', 'topic')   # names that are already canonical — never merge these

def _uf_find(par, x):
    while par[x] != x: par[x] = par[par[x]]; x = par[x]
    return x

def _uf_union(par, rank, a, b, name=None, ok=None, members=None, max_check=32):
    'Merge two groups. With `name`/`ok`, only if the merged group stays a **clique** under `ok`.'
    ra, rb = _uf_find(par, a), _uf_find(par, b)
    if ra == rb: return False
    if name is not None and ok is not None:
        A = (members.get(ra, [ra]) if members else [ra])[:max_check]
        B = (members.get(rb, [rb]) if members else [rb])[:max_check]
        if not all(ok(name[x], name[y]) for x in A for y in B): return False
    if rank[ra] < rank[rb]: ra, rb = rb, ra
    par[rb] = ra
    if members is not None: members.setdefault(ra, [ra]).extend(members.pop(rb, [rb]))
    return True

def _ann_pairs(tbl, rows, k=8, dtype=np.float16):
    '''`(id, neighbour_id, distance)` for every embedded row, from one batched HNSW probe.

    usearch searches a matrix of queries across its own thread pool, so asking it once for 8,487
    vectors is not the same work as asking it 8,487 times: the per-entity loop also ran one
    `rowid IN (...)` query per entity, and the two together were 10.3s of a 23.0s resolve. The
    candidate set is unchanged — same k, same neighbours, same distances.'''
    idx_ = tbl.db.get_index(tbl.name)
    emb = [r for r in rows if r['embedding']]
    if not emb or not idx_.size: return
    key = {r['rowid']: r for r in tbl.db.q(f'select {_rid()}, id, content from {tbl.name}')}
    res = idx_.search(np.stack([np.frombuffer(r['embedding'], dtype=dtype) for r in emb]),
                      count=min(k, idx_.size))
    ks, ds = np.atleast_2d(res.keys), np.atleast_2d(res.distances)
    for r, kr, dr in zip(emb, ks, ds):
        for kk, dd in zip(np.atleast_1d(kr).tolist(), np.atleast_1d(dr).tolist()):
            if (o := key.get(int(kk))): yield r, o, float(dd)

def _lexical_pairs(name, max_group=60):
    '''Candidate merge pairs by shared-token blocking — catches containment variants

    Tokens are walked in sorted order, which is what makes a resolve reproducible. `_toks` returns
    a frozenset, so its iteration order follows string hashes and therefore `PYTHONHASHSEED`; that
    decided the insertion order of `inv`, which decided the order pairs were proposed in, and
    `_uf_union` only accepts a merge that keeps the group a clique — an order-dependent test. Two
    resolves of the *same* database in two processes came back with different partitions and merge
    counts drifting over a range of three, which looked like HNSW noise and was not: hold the seed
    still and both the old code and the new one are exactly reproducible, and `verify_ann_probe`
    says the ANN candidates were stable the whole time.'''
    inv = {}
    for i, s in name.items():
        for t in sorted(_toks(s)):
            if len(t) > 2: inv.setdefault(t, []).append(i)
    seen = set()
    for ids in inv.values():
        if len(ids) < 2: continue
        if len(ids) <= max_group: pairs = ((ids[a], ids[b]) for a in range(len(ids)) for b in range(a+1, len(ids)))
        else:
            srt = sorted(ids, key=lambda i: name[i])
            pairs = ((srt[a], srt[b]) for a in range(len(srt)) for b in range(a+1, min(a+max_group, len(srt))))
        for x, y in pairs:
            p = (x, y) if x < y else (y, x)
            if p not in seen: seen.add(p); yield p

def resolve_entities(db,                # Database
                     store='store',     # chunk store the graph belongs to
                     prefix=None,       # graph table prefix
                     thresh=0.18,       # max ANN distance for a merge candidate
                     lex=0.34,          # min token Jaccard for the lexical guard
                     k=8,               # ANN neighbours considered per entity
                     lexical=True,      # also block on shared tokens (works without embeddings)
                     max_group=60,      # skip token groups bigger than this in the lexical pass
                     skip_kinds=_EXACT_KINDS,  # kinds whose names are already canonical
                     dtype=np.float16):
    'Merge near-duplicate entities: ANN + shared-token candidates, both gated by the lexical guard.'
    g = db.get_graph(store, prefix)
    allr = L(g.entities(select=f'{_rid()}, id, content, freq, embedding, kind, canon'))
    rows = allr.filter(lambda r: r['kind'] not in set(skip_kinds or ()))
    if len(rows) < 2:
        return dict(merged=0, by_ann=0, by_lexical=0, edges=len(list(g.edges())),
                    entities=len(allr), resolvable=len(rows), canonical=len(allr))
    par  = {r['id']: r['id'] for r in rows}
    rank = {r['id']: (r['freq'] or 0) for r in rows}
    name = {r['id']: r['content'] for r in rows}
    ann_m = lex_m = 0
    guard, members = (lambda x, y: _lex_ok(x, y, lex)), {}
    for r, h, dist in _ann_pairs(g.entities, rows, k, dtype):
        oid = h.get('id')
        if not oid or oid == r['id'] or oid not in par: continue
        if dist > thresh: continue
        if not _lex_ok(r['content'], h['content'], lex): continue
        if _uf_union(par, rank, r['id'], oid, name, guard, members): ann_m += 1
    if lexical:
        for a, b in _lexical_pairs(name, max_group):
            if _lex_ok(name[a], name[b], lex) and _uf_union(par, rank, a, b, name, guard, members): lex_m += 1
    upd = [(_uf_find(par, i), i) for i in par]
    # Only the rows whose canon actually *moves* are written, and they are written inside one
    # transaction. `canon` is not an FTS column, but apswutils' AFTER UPDATE trigger fires on any
    # update to the row, so every statement here re-tokenised `content` into the FTS index — and
    # outside a transaction apsw commits each statement, which in WAL mode is an fsync per entity.
    # 5,650 entities, 2,056 of them actually merged: 5,650 fsync'd reindexes to record 2,056 facts.
    # Compared against the *stored* canon rather than against the id, so a re-resolve that undoes a
    # merge still writes the row back — skipping `c == i` alone would leave a stale canon behind.
    was = {r['id']: r['canon'] for r in rows}
    chg = [(c, i) for c, i in upd if c != was.get(i)]
    if chg:
        with write_txn(db):
            db.conn.cursor().executemany(f'update {g.entities.name} set canon=? where id=?', chg)
    canon = {i: c for c, i in upd}
    n_edges = _collapse_edges(db, g, canon)
    skipped = len(allr) - len(rows)
    return dict(merged=ann_m+lex_m, by_ann=ann_m, by_lexical=lex_m, edges=n_edges,
                entities=len(allr), resolvable=len(rows),
                canonical=len({c for c, _ in upd}) + skipped)

def _collapse_edges(db, g, canon):
    'Rewrite edge endpoints onto canonical ids. Traversal reads src/dst straight from the table,'
    rows = list(g.edges())
    if not rows: return 0
    agg = {}
    for r in rows:
        s, d = canon.get(r['src'], r['src']), canon.get(r['dst'], r['dst'])
        if s == d: continue
        if s > d and r['rel'] == 'cooc': s, d = d, s     # cooc is symmetric; keep one direction
        k = (s, d, r['rel'])
        a = agg.setdefault(k, dict(src=s, dst=d, rel=r['rel'], weight=0.0, n=0))
        a['weight'] = max(a['weight'], r['weight'] or 0.0); a['n'] += (r['n'] or 0)
    # one transaction for the delete and the reinsert: apswutils commits per insert batch, so the
    # rewrite paid an fsync per batch on top of leaving the table briefly empty for a concurrent
    # reader. Both halves are now the same write.
    with write_txn(db):
        g.edges.delete_where()
        upsert_all(g.edges, agg.values(), ('src','dst','rel'))
    return len(agg)


# %% ../nbs/05_graph.ipynb #dd02940510f58745
def cooccur_edges(db,                 # Database
                  store='store',      # chunk store
                  prefix=None,        # graph table prefix
                  min_n=2,            # min co-occurrence count
                  min_npmi=0.15,      # min normalized PMI (prunes stopword-ish hub nodes)
                  max_df=0.4,         # drop entities present in >max_df of chunks
                  max_degree=48,      # keep only the strongest edges per node
                  rel='cooc',
                  use_canon=True):    # collapse to canonical ids from resolve_entities
    'Rebuild co-occurrence edges from the stored mentions, using the chunk as the window.'
    g = db.get_graph(store, prefix)
    canon = {}
    if use_canon:
        canon = {r['id']: (r['canon'] or r['id']) for r in g.entities(select='id, canon')}
    cid_ents = {}
    for m in g.mentions(select='chunk_id, entity_id'):
        e = canon.get(m['entity_id'], m['entity_id'])
        cid_ents.setdefault(m['chunk_id'], set()).add(e)
    out = _pmi_edges(list(cid_ents.values()), min_n, min_npmi, max_df, max_degree, rel)
    if out: upsert_all(g.edges, out, ('src','dst','rel'))
    return len(out)


# %% ../nbs/05_graph.ipynb #3bd6bc9f72663973
# connector words — cluster names built from these describe the corpus, not the cluster
_STOP = set('''the a an and or of to in is are was were be been being for on at by with from this that these those
it its as not but if then than so such can will would could should may might do does did have has had he she they
we you i him her them our your their about into over under after before between out up down off only own same too
very just also each other more most some any no nor own s t don now here there when where why how all both'''.split())
_LWORD = re.compile(r'[A-Za-z_][A-Za-z0-9_]{2,}')   # keeps identifiers whole

def ctfidf_labels(texts,        # one text per member, aligned with `lab`
                  lab,          # cluster index per member
                  k,            # number of clusters
                  top_n=4,      # terms per label
                  stop=None,    # stopword set (defaults to _STOP)
                  sep=', '):
    'Name each cluster by terms common inside it and rare across the other clusters.'
    st = _STOP if stop is None else stop
    tf = [{} for _ in range(k)]
    for t, j in zip(texts, lab):
        for w in set(_LWORD.findall((t or '').lower())):
            if w in st or len(w) < 3: continue
            tf[j][w] = tf[j].get(w, 0) + 1
    df = {}
    for d in tf:
        for w in d: df[w] = df.get(w, 0) + 1
    # one pass for every cluster's member count. Counting inside the loop below re-walked the whole
    # `lab` array once per cluster, which is quadratic in the number of clusters for no reason.
    sz = {}
    for j in lab: sz[j] = sz.get(j, 0) + 1
    out = []
    for j, d in enumerate(tf):
        n = max(1, sz.get(j, 0))
        sc = {w: (c/n) * math.log(k/df[w]) for w, c in d.items() if df[w] < k}
        top = sorted(sc.items(), key=lambda kv: -kv[1])[:top_n]
        out.append(sep.join(w for w, _ in top))
    return out

def _usearch_clusters(idx, min_count, max_count):
    '(centroid, members) straight off the HNSW graph. usearch walks the index levels, so it needs'
    kw = {k: v for k, v in dict(min_count=min_count, max_count=max_count).items() if v}
    cl = idx.cluster(**kw)
    keys, _ = cl.centroids_popularity
    out = L()
    for ck in np.atleast_1d(keys).tolist():
        try: out.append((int(ck), [int(x) for x in np.atleast_1d(cl.members_of(ck)).tolist()]))
        except Exception: continue
    return out

def _knn_clusters(idx, keys, k=8, max_size=None, min_sim=None, dtype=np.float16):
    '(seed, members) from a greedy pass over the kNN graph harvested from HNSW. Works at any size.'
    keys = list(keys)
    if len(keys) < 4: return L()
    # one batched lookup, not one per key: usearch reconstructs a whole key array in C++, and the
    # search below is already handed the matrix rather than a query at a time
    vecs = np.asarray(idx[np.array(keys, dtype=np.int64)], dtype=dtype).reshape(len(keys), -1)
    res = idx.search(vecs, count=min(k+1, len(keys)))
    nbr, sims = {}, []
    for i, kk in enumerate(keys):
        ks = np.atleast_1d(res.keys[i]).tolist()
        ds = np.atleast_1d(res.distances[i]).tolist()
        n = [(int(a), 1.0-float(b)) for a, b in zip(ks, ds) if int(a) != kk]
        nbr[kk] = n
        sims += [s for _, s in n]
    if min_sim is None: min_sim = float(np.median(sims)) if sims else 0.0
    cap = max_size or max(k, 4)
    dens = {kk: sum(s for _, s in v if s >= min_sim) for kk, v in nbr.items()}
    out, seen = L(), set()
    for kk in sorted(keys, key=lambda x: -dens.get(x, 0.0)):
        if kk in seen: continue
        grp = [kk]; seen.add(kk)
        for nk, s in sorted(nbr.get(kk, []), key=lambda t: -t[1]):
            if len(grp) >= cap: break
            if nk not in seen and s >= min_sim: grp.append(nk); seen.add(nk)
        out.append((int(kk), [int(x) for x in grp]))
    return out

def _cluster_groups(idx,               # usearch Index
                    keys=None,         # keys to cluster (defaults to everything in the index)
                    min_count=None,    # usearch: smallest cluster to emit
                    max_count=None,    # usearch: largest cluster to emit
                    k=8,               # neighbours per node in the kNN fallback
                    dtype=np.float16):
    '`([(centroid, members)], method)` for an index.'
    try: return _usearch_clusters(idx, min_count, max_count), 'usearch'
    except Exception:
        ks = np.atleast_1d(idx.keys).tolist() if keys is None else list(keys)
        return _knn_clusters(idx, ks, k, dtype=dtype), 'knn'

def topic_nodes(db,                # Database
                store='store',     # chunk store (must be ANN-registered)
                prefix=None,       # graph table prefix
                min_count=None,    # usearch cluster min size
                max_count=None,    # usearch cluster max size
                k=8,               # neighbours per node in the fallback kNN graph
                min_size=2,        # smallest cluster kept as a topic
                label_k=4,         # terms per topic label
                max_label_chars=4000,
                dtype=np.float16):
    'Cluster the store index into topic nodes labelled by c-TF-IDF. Returns {topics, method}.'
    g = db.get_graph(store, prefix)
    m = db._ann_meta(store)
    if not (m and m['ndim']): return dict(topics=0, method=None)
    idx = db.get_index(store)
    if idx.size < 4: return dict(topics=0, method=None)
    dt = _np_dtype.get(m['dtype'], dtype)
    rid2cid = {r['rowid']: r['id'] for r in db.t[store](select=f'{_rid()}, id')}
    groups, method = _cluster_groups(idx, rid2cid.keys(), min_count, max_count, k, dt)
    kept = [[rid2cid[r] for r in mem if r in rid2cid] for _, mem in groups]
    kept = [c for c in kept if len(c) >= min_size]
    if not kept: return dict(topics=0, method=method)
    # labels are scored across all clusters at once, so gather members first
    txt = {r['id']: r['content'] for r in db.t[store](select='id, content',
                                                      where=_in('id', [c for g_ in kept for c in g_[:24]]))}
    texts, lab = [], []
    for j, cids in enumerate(kept):
        for c in cids[:24]: texts.append((txt.get(c) or '')[:max_label_chars]); lab.append(j)
    names = ctfidf_labels(texts, lab, len(kept), label_k)
    ents, mens = [], []
    for j, cids in enumerate(kept):
        # deliberately not _norm(): topic labels are multi-phrase and would trip its 5-token cap
        name = f'topic: {names[j]}'[:60] if names[j] else f'topic-{j}'
        eid = _slug(name)
        ents.append(dict(content=name, kind='topic', freq=len(cids), canon=eid))
        mens += [dict(chunk_id=c, entity_id=eid, surface=name, n=1) for c in cids]
    if ents: g.entities.insert_all(ents, upsert=True, hash_id='id', hash_id_columns=['content'])
    if mens: upsert_all(g.mentions, mens, ('chunk_id','entity_id'))
    return dict(topics=len(ents), method=method)


# %% ../nbs/05_graph.ipynb #15eaacbc30189934
@patch
def _cluster_cached(self:Table, min_count, max_count, k, dtype):
    'Cluster once per (store, params, index size). `peers` would otherwise recluster on every call.'
    idx = self.db.get_index(self.name)
    ck = (self.name, min_count, max_count, k, idx.size)
    cache = getattr(self.db, '_cluster_cache', None)
    if cache is None: cache = self.db._cluster_cache = {}
    if ck not in cache:
        groups, method = _cluster_groups(idx, None, min_count, max_count, k, dtype)
        assign = {m: g for _, g in groups for m in g}
        cache[ck] = (groups, method, assign)
    return cache[ck]

@patch
def _member_rows(self:Table, keys, columns=None):
    'Store rows for a list of usearch keys, keyed by rowid. `content` is always fetched (labels need it).'
    if not keys: return {}
    cols = list(dict.fromkeys([c for c in (columns or []) if c != 'rowid'] + ['content']))
    sel, out = ','.join(cols + [_rid()]), {}
    for i in range(0, len(keys), 400):
        for r in self.db.q(f'select {sel} from {self.name} where {_in("rowid", keys[i:i+400])}'): out[r['rowid']] = r
    return out

@patch
def clusters(self:Table,              # ANN-registered store
             min_count:int=None,      # usearch: smallest cluster to emit
             max_count:int=None,      # usearch: largest cluster to emit
             k:int=8,                 # neighbours per node in the kNN fallback
             min_size:int=2,          # drop groups smaller than this
             label_k:int=4,           # terms per c-TF-IDF label
             members:int=24,          # member rows fetched per cluster
             columns:list=None,       # store columns to return per member row
             max_label_chars:int=4000,# per-member text budget for labelling
             dtype=np.float16):
    'The corpus grouped by embedding shape, each group named by c-TF-IDF.'
    m = self.db._ann_meta(self.name)
    if not m: return AttrDict(clusters=L(), method=None, note=f'{self.name!r} is not an ANN store')
    if not m['ndim']: return AttrDict(clusters=L(), method=None, note=f'{self.name!r} has no vectors yet')
    idx = self.db.get_index(self.name)
    if idx.size < 4: return AttrDict(clusters=L(), method=None, note=f'index holds {idx.size} vectors; too few to cluster')
    dt = _np_dtype.get(m['dtype'], dtype)
    groups, method, _ = self._cluster_cached(min_count, max_count, k, dt)
    kept = [(c, g) for c, g in groups if len(g) >= min_size]
    if not kept: return AttrDict(clusters=L(), method=method, note=f'no group reached min_size={min_size}')
    rows = self._member_rows([r for _, g in kept for r in g[:members]], columns)
    texts, lab = [], []
    for j, (_, g) in enumerate(kept):
        for r in g[:members]: texts.append(((rows.get(r) or {}).get('content') or '')[:max_label_chars]); lab.append(j)
    names = ctfidf_labels(texts, lab, len(kept), label_k)
    out = L(AttrDict(centroid=c, size=len(g), label=names[j] or f'group-{j}', member_keys=g,
                     members=L(rows[r] for r in g[:members] if r in rows))
            for j, (c, g) in enumerate(kept))
    return AttrDict(clusters=out.sorted(key=lambda c: -c.size), method=method,
                    note=f'{len(out)} clusters over {idx.size} vectors ({method})')

@patch
def peers(self:Table,            # ANN-registered store
          key:int,               # usearch key (rowid) whose group you want
          limit:int=25,          # members to return
          columns:list=None,     # store columns to return per member row
          min_count:int=None,    # usearch: smallest cluster to emit
          max_count:int=None,    # usearch: largest cluster to emit
          k:int=8,               # neighbours per node in the kNN fallback
          dtype=np.float16):
    'The group `key` belongs to — its family, not a ranked list of what is nearest to it.'
    nbr = lambda note: AttrDict(hits=L(self.ann_neighbors(key, limit, columns, dtype=dtype)), method='ann', note=note)
    m = self.db._ann_meta(self.name)
    if not m: return AttrDict(hits=L(), method=None, note=f'{self.name!r} is not an ANN store')
    if not m['ndim']: return AttrDict(hits=L(), method=None, note=f'{self.name!r} has no vectors yet')
    idx = self.db.get_index(self.name)
    if not idx.size or not idx.contains(key): return AttrDict(hits=L(), method=None, note=f'key {key} is not indexed')
    dt = _np_dtype.get(m['dtype'], dtype)
    if idx.size < 4: return nbr(f'index holds {idx.size} vectors; showing nearest neighbours')
    _, method, assign = self._cluster_cached(min_count, max_count, k, dt)
    grp = assign.get(key)
    if not grp: return nbr('row is in no cluster; showing nearest neighbours')
    mem = [x for x in grp if x != key][:limit]
    if not mem: return nbr('cluster has one member; showing nearest neighbours')
    rows, order = self._member_rows(mem, columns), {r: i for i, r in enumerate(mem)}
    return AttrDict(hits=L(rows[r] for r in sorted(rows, key=lambda r: order.get(r, 1<<30)) if r in rows),
                    method=method, note=f'cluster of {len(grp)} ({method})')


# %% ../nbs/05_graph.ipynb #a380070d2dd9d9da
def _adjacency(g, nodes, hops=2, max_nodes=4000):
    '''BFS the edge table out to `hops` from `nodes`; returns an undirected dict-of-dict adjacency.

    Read as raw tuples rather than through the table wrapper. A two-hop walk off twelve seeds pulls
    ~16k edges, and fastlite turns each one into a dict with a description lookup per row — 326k
    dicts over twenty queries, of which this needs three columns and none of the keys.'''
    adj, seen, frontier = {}, set(nodes), set(nodes)
    con, tbl = g.edges.db.conn, g.edges.name
    for _ in range(max(hops, 0)):
        if not frontier or len(seen) >= max_nodes: break
        fl = list(frontier)
        rows = []
        for i in range(0, len(fl), 400):
            b = fl[i:i+400]
            rows += con.execute(f"select src, dst, weight from {tbl} "
                                f"where {_in('src', b)} OR {_in('dst', b)}").fetchall()
        nxt = set()
        for s, d, w in rows:
            w = w or 1.0
            adj.setdefault(s, {})[d] = max(adj.setdefault(s, {}).get(d, 0.0), w)
            adj.setdefault(d, {})[s] = max(adj.setdefault(d, {}).get(s, 0.0), w)
            for x in (s, d):
                if x not in seen: nxt.add(x)
        seen |= nxt
        frontier = nxt
    return adj

def _csr(adj, order):
    '''`(src, dst, w)` index arrays for `adj`, row-normalised — the transition matrix as three arrays.

    Built once and reused by every power iteration, which is the whole point: the walk itself is
    then twelve numpy passes instead of twelve nested python loops over the same unchanging edges.'''
    src, dst, wt = [], [], []
    for u, nb in adj.items():
        iu, s = order[u], (sum(nb.values()) or 1.0)
        for v, w in nb.items(): src.append(iu); dst.append(order[v]); wt.append(w/s)
    return (np.array(src, dtype=np.intp), np.array(dst, dtype=np.intp),
            np.array(wt, dtype=np.float64))

def _ppr(adj, seeds, damping=0.85, iters=12):
    '''Personalized PageRank over a dict-of-dict adjacency.

    The iteration is `r <- d * Wᵀr + (1-d) * p0` and nothing but `r` changes between rounds, so the
    edges are flattened into index arrays once and each round becomes a gather plus a `bincount` —
    the same sum, done by numpy instead of by a dict lookup per edge per round. Dangling nodes still
    drop their mass rather than redistributing it, exactly as the dict version did.'''
    if not seeds: return {}
    order = {}
    for u, nb in adj.items():
        if u not in order: order[u] = len(order)
        for v in nb:
            if v not in order: order[v] = len(order)
    for k in seeds:
        if k not in order: order[k] = len(order)
    n = len(order)
    p0 = np.zeros(n)
    tot = sum(seeds.values()) or 1.0
    for k, v in seeds.items(): p0[order[k]] = v/tot
    src, dst, wt = _csr(adj, order)
    wt = wt * damping
    r, rest = p0, (1-damping)*p0
    for _ in range(iters):
        r = np.bincount(dst, weights=r[src]*wt, minlength=n) + rest
    return {k: float(r[i]) for k, i in order.items() if r[i]}

# %% ../nbs/05_graph.ipynb #66f98425ed3e448
def rrf_all(lists,              # list of ranked result lists
            k=60,               # RRF k
            limit=50,           # max results
            id_key='rowid',     # join key
            weights=None):      # per-list weights
    'Reciprocal Rank Fusion over any number of ranked lists.'
    ws = weights or [1.0]*len(lists)
    scores = {}
    for lst, w in zip(lists, ws):
        for rank, row in enumerate(lst or []):
            rid = row.get(id_key, id(row))
            if rid in scores: scores[rid]['_rrf_score'] += w/(k + rank)
            else: scores[rid] = merge(row, {'_rrf_score': w/(k + rank)})
    return sorted(scores.values(), key=lambda x: x['_rrf_score'], reverse=True)[:limit]

def _canon_mentions(g,                # graph tables from `get_graph`
                    col,              # 'chunk_id' or 'entity_id' — the side being filtered
                    vals,             # values to filter on
                    use_canon=True,   # resolve entity_id to its canonical id
                    batch=400):
    '''`(chunk_id, entity_id)` for the matching mentions, with `entity_id` already canonicalised.

    The canonical id comes from a join on the mentions being read, not from a dict of the whole
    entity table. `coalesce(nullif(...))` reproduces `canon.get(eid, eid)` over `{id: canon or id}`
    exactly: a missing entity, a null canon and an empty canon all fall back to the mention's own
    entity_id.'''
    con, mn, en = g.mentions.db.conn, g.mentions.name, g.entities.name
    sel = (f'select m.chunk_id, coalesce(nullif(e.canon, \'\'), m.entity_id) from {mn} m '
           f'left join {en} e on e.id = m.entity_id') if use_canon else \
          f'select m.chunk_id, m.entity_id from {mn} m'
    out = []
    for i in range(0, len(vals), batch):
        out += con.execute(f"{sel} where {_in('m.'+col, vals[i:i+batch])}").fetchall()
    return out

# %% ../nbs/05_graph.ipynb #fba9515fca9c5b56
@patch
def graph_search(self:Database,
                 q:str,                 # query string
                 emb:bytes,             # query embedding
                 columns:list=None,     # columns to return
                 limit:int=20,          # max results
                 table_name='store',    # chunk store
                 prefix=None,           # graph table prefix
                 seed_n:int=12,         # hybrid hits used to seed the graph walk
                 hops:int=2,            # edge-table BFS depth
                 damping:float=0.85,    # PPR damping
                 iters:int=10,          # PPR iterations
                 graph_w:float=0.5,     # weight of the graph leg (low by default — see docstring)
                 rrf_k:int=60,
                 use_canon=True,
                 **kw):                 # forwarded to Database.search
    'Hybrid search plus a graph leg: PPR over the entity graph seeded by the top hybrid hits.'
    g = self.get_graph(table_name, prefix)
    cols = list(columns or [])
    if 'rowid' not in cols: cols = ['rowid'] + cols
    if 'id' not in cols: cols = cols + ['id']
    base = self.search(q, emb, columns=cols, limit=max(seed_n*3, limit), table_name=table_name,
                       rrf=False, **kw)
    if not base: return []
    fts, vec = base['fts'], base['vec']
    seed_rows = rrf_all([fts, vec], rrf_k, seed_n)
    seed_cids = [r['id'] for r in seed_rows if r.get('id')]
    if not seed_cids: return rrf_all([fts, vec], rrf_k, limit)
    # canon is resolved by joining the mentions being read rather than by loading the whole entity
    # table into a dict. Every query paid O(entities) for a map it used O(mentions-of-12-chunks) of,
    # which is the one cost in `graph_search` that grew with the corpus rather than with the query.
    seeds = {}
    for _, e in _canon_mentions(g, 'chunk_id', seed_cids, use_canon): seeds[e] = seeds.get(e, 0.0) + 1.0
    if not seeds: return rrf_all([fts, vec], rrf_k, limit)
    adj = _adjacency(g, set(seeds), hops)
    mass = _ppr(adj, seeds, damping, iters)
    if not mass: return rrf_all([fts, vec], rrf_k, limit)
    top = sorted(mass.items(), key=lambda kv: -kv[1])[:200]
    eids = [e for e, _ in top if _ > 0]
    if not eids: return rrf_all([fts, vec], rrf_k, limit)
    inv = {}
    for cid, e in _canon_mentions(g, 'entity_id', eids, use_canon):
        inv[cid] = inv.get(cid, 0.0) + mass.get(e, 0.0)
    if not inv: return rrf_all([fts, vec], rrf_k, limit)
    ranked = sorted(inv.items(), key=lambda kv: -kv[1])[:limit*3]
    cids = [c for c, _ in ranked]
    sel = ','.join([_rid() if c == 'rowid' else c for c in cols])
    rows = {r['id']: r for r in self.t[table_name](select=sel, where=_in('id', cids))}
    graph_leg = [rows[c] for c, _ in ranked if c in rows]
    return rrf_all([fts, vec, graph_leg], rrf_k, limit, weights=[1.0, 1.0, graph_w])


# %% ../nbs/05_graph.ipynb #96b2124dafe08d01
def graph_stats(db, store='store', prefix=None):
    'Row counts and top-degree nodes for a built graph.'
    g = db.get_graph(store, prefix)
    ne = first(db.q(f'select count(*) c from {g.entities.name}'))['c']
    nm = first(db.q(f'select count(*) c from {g.mentions.name}'))['c']
    ng = first(db.q(f'select count(*) c from {g.edges.name}'))['c']
    nc = first(db.q(f'select count(distinct canon) c from {g.entities.name}'))['c']
    top = db.q(f'''select e.content, e.kind, count(*) d from {g.edges.name} g
                   join {g.entities.name} e on e.id=g.src group by g.src order by d desc limit 10''')
    return dict(entities=ne, canonical=nc, mentions=nm, edges=ng, top_degree=top)
