# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_graph.ipynb.

# %% auto #0
__all__ = ['hash_embed', 'code_entities', 'spacy_pipe', 'stanza_pipe', 'prose_windows', 'text_entities', 'build_graph',
           'resolve_entities', 'cooccur_edges', 'ctfidf_labels', 'topic_nodes', 'rrf_all', 'graph_stats']

# %% ../nbs/05_graph.ipynb #imports
from fastcore.all import Path, patch, merge, ifnone, first, L, AttrDict
from fastlite import Database
from apswutils.db import Table
import ast, math, re, zlib
import numpy as np

from .core import _in, _rid, _slug, _np_dtype, process_content

# %% ../nbs/05_graph.ipynb #schema
@patch
def get_graph(self:Database,
              store:str='store',   # chunk store the graph is built over
              prefix:str=None,     # table prefix (default: '' for 'store', else '<store>_')
              ann:bool=True,       # register an ANN index on the entity store (needed for resolution)
              **kw):               # extra typed columns for the entity store
    'Create the entity/mention/edge tables for a chunk store. Idempotent; returns the tables.'
    p = prefix if prefix is not None else ('' if store == 'store' else f'{store}_')
    en, mn, eg = f'{p}entities', f'{p}mentions', f'{p}edges'
    ents = self.get_store(en, hash=True, ann=ann, kind=str, canon=str, freq=int, **kw)
    self.t[mn].create(chunk_id=str, entity_id=str, surface=str, n=int,
                      pk=('chunk_id', 'entity_id'), if_not_exists=True)
    self.t[eg].create(src=str, dst=str, rel=str, weight=float, n=int,
                      pk=('src', 'dst', 'rel'), if_not_exists=True)
    for t, c in ((mn, 'entity_id'), (mn, 'chunk_id'), (eg, 'src'), (eg, 'dst')):
        self.t[t].create_index([c], if_not_exists=True)
    return AttrDict(entities=ents, mentions=self.t[mn], edges=self.t[eg], store=self.t[store], prefix=p)

# %% ../nbs/05_graph.ipynb #norm
_DET = re.compile(r'^(the|a|an|this|that|these|those|its|their|our|your|his|her)\s+', re.I)
_WS  = re.compile(r'\s+')
_PRON = {'it','its','we','our','they','their','he','she','you','i','me','us','them','this','that',
         'these','those','which','who','what','there','here','one','ones','something','anything'}
_TOK = re.compile(r'[a-z0-9]+')
_NUM = re.compile(r'\d+')

def _norm(s):
    'Canonical surface form for a mention; None when the phrase is not entity-like.'
    if not s: return None
    s = _WS.sub(' ', s).strip().strip('.,;:!?()[]{}"\'`')
    s = _DET.sub('', s).strip()
    s = re.sub(r"'s$", '', s).strip()
    if not (2 <= len(s) <= 60): return None
    if len(s.split()) > 5: return None
    if s.lower() in _PRON: return None
    if not re.search(r'[A-Za-z]', s): return None          # pure numbers / punctuation
    return s.lower()

def _toks(s):
    '''Tokens for the lexical guard. UAX#29 treats `_` as a word joiner, so `fts_search` stays one
    token — splitting it gives {fts, search}, which merges it into `search` by containment.'''
    try: from apsw.unicode import word_iter, casefold
    except ImportError: return set(_TOK.findall(s.lower()))
    return {casefold(t) for t in word_iter(s or '') if any(c.isalnum() for c in t)}

def _acr(s):  return ''.join(w[0] for w in s.split() if w)

def _sentences(text):
    'UAX#29 sentence split via apsw; falls back to the whole text as one window.'
    try: from apsw.unicode import sentence_iter
    except ImportError: return [text]
    return [s for s in (x.strip() for x in sentence_iter(text)) if s]

def _jac(a, b):
    A, B = _toks(a), _toks(b)
    return len(A & B) / len(A | B) if (A | B) else 0.0

def _lex_ok(a, b, lex=0.34, cover=0.5):
    '''Lexical guard on a proposed merge.
    Blocks pairs whose numbers disagree ("python 3.11" vs "python 3.12"), and accepts token
    containment only when the shorter side covers `cover` of the longer — bare substring matching
    chains transitively through union-find and collapses the whole graph into one node.'''
    if a == b: return True
    if set(_NUM.findall(a)) != set(_NUM.findall(b)): return False
    if _acr(a) == b.lower() or _acr(b) == a.lower(): return True
    A, B = _toks(a), _toks(b)
    if not (A and B): return False
    inter = len(A & B)
    if inter == min(len(A), len(B)) and inter/max(len(A), len(B)) >= cover: return True
    return inter/len(A | B) >= lex

# %% ../nbs/05_graph.ipynb #hashemb
def hash_embed(texts,            # iterable of strings
               ndim:int=256,     # output dimensions
               ngram=(3,5),      # char n-gram range
               dtype=np.float16):
    '''Deterministic char-n-gram hashing embedder — no model, no download.
    Sized for *entity-name* resolution (subword overlap is what matters there) and for offline/CI runs.
    Use FastEncode for chunk embeddings, where you need real semantics.'''
    lo, hi = ngram
    txts = list(L(texts))
    out = np.zeros((len(txts), ndim), dtype=np.float32)
    for i, t in enumerate(txts):
        s = ' ' + _WS.sub(' ', (t or '').lower().strip()) + ' '
        for n in range(lo, hi+1):
            for j in range(len(s)-n+1):
                out[i, zlib.crc32(s[j:j+n].encode()) % ndim] += 1.0
    out /= np.clip(np.linalg.norm(out, axis=1, keepdims=True), 1e-12, None)
    return out.astype(dtype)

# %% ../nbs/05_graph.ipynb #code_ents
_PY_SKIP = {'self','cls','super','print','len','str','int','float','bool','list','dict','set','tuple',
            'range','enumerate','zip','map','filter','isinstance','getattr','setattr','hasattr','type',
            'format','join','append','get','items','keys','values','open','sorted','sum','min','max'}

def _def_name(chunk):
    'Symbol defined by a code chunk, from pyparse metadata or the chunk source itself.'
    md = chunk.get('metadata') or {}
    if isinstance(md, dict) and md.get('name'): return md['name']
    try: tree = ast.parse(chunk['content'])
    except SyntaxError: return None
    n = first(tree.body, lambda x: isinstance(x, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)))
    return getattr(n, 'name', None)

def code_entities(chunk):
    'Exact symbols for a python chunk: (defined, called, imported). AST-derived, no model.'
    try: tree = ast.parse(chunk['content'])
    except (SyntaxError, ValueError): return None, L(), L()
    calls, imps = L(), L()
    for n in ast.walk(tree):
        if isinstance(n, ast.Call):
            f = n.func
            if   isinstance(f, ast.Name):      calls.append(f.id)
            elif isinstance(f, ast.Attribute): calls.append(f.attr)
        elif isinstance(n, ast.Import):
            imps += [a.name.split('.')[0] for a in n.names]
        elif isinstance(n, ast.ImportFrom):
            if n.module: imps.append(n.module.split('.')[0])
    keep = lambda s: s and s not in _PY_SKIP and not s.startswith('_') and len(s) > 2
    return _def_name(chunk), calls.filter(keep).unique(), imps.filter(keep).unique()

# %% ../nbs/05_graph.ipynb #text_ents
_KEEP_ENTS = {'ORG','PRODUCT','PERSON','WORK_OF_ART','LAW','EVENT','GPE','NORP','FAC','SYMBOL'}

def spacy_pipe(model='en_core_web_sm',  # spaCy model name
               terms=None,              # exact-match terms for an EntityRuler (e.g. code symbols)
               label='SYMBOL',          # label applied to ruler matches
               download=True):          # fetch the model on first use if it isn't installed
    '''spaCy pipeline with an optional EntityRuler seeded from exact terms. None when spaCy is unavailable.
    The model is lazy-loaded and fetched once on first use — spaCy models aren't shippable as
    install-time deps (not on PyPI, and PyPI rejects URL deps), so we download on demand.'''
    try: import spacy
    except ImportError: return None
    try: nlp = spacy.load(model)
    except (OSError, IOError):
        if not download: return None
        try:
            from spacy.cli import download as _dl
            _dl(model); nlp = spacy.load(model)
        except Exception: return None
    if terms:
        pats = [{'label': label, 'pattern': t} for t in sorted(set(terms)) if t and len(t) > 2]
        if pats: nlp.add_pipe('entity_ruler', before='ner', config={'overwrite_ents': True}).add_patterns(pats)
    return nlp

def stanza_pipe(lang:str='en',                            # stanza language code ('en', 'sa', 'hi', ...)
                processors:str='tokenize,pos,lemma',      # add 'ner' where stanza has a model for it
                download:bool=True,                       # fetch the models on first use
                **kw):                                    # forwarded to spacy_stanza.load_pipeline
    """A spaCy pipeline backed by stanza, for languages `spacy_pipe` has no model for. None if unavailable.

    Stanza covers 68 languages against spaCy's ~25, and Sanskrit is one of the ones only it has —
    which is the reason this exists: without it, `build_graph(prose=True)` on a Sanskrit corpus
    falls through to yake, and yake on Devanagari is keyphrase extraction with no notion of a word.

    Three things to know before reaching for it.

    **It is not a drop-in upgrade for English.** `spacy_pipe` is the right default there: stanza is
    a neural pipeline and runs one to two orders of magnitude slower than `en_core_web_sm`, for NER
    that is comparable. Use this when the language is the constraint, not when speed is.

    **`noun_chunks` does not exist for most of these languages** — spaCy implements that iterator
    per language and `sa` is not among them. `_wins_from_doc` falls back to a POS-run approximation
    (`_nominal_spans`), which is why prose extraction works here at all.

    **stanza has no NER model for Sanskrit**, so `processors='...,ner'` will fail for `sa`. What you
    get for Sanskrit is tokenisation, tags and lemmas — and the lemmas are the valuable part; see
    `litesearch.sanskrit.lemma_facets`.

    Needs `pip install litesearch[stanza]`, and downloads a model per language on first use."""
    try: import spacy_stanza, stanza
    except ImportError: return None
    try: return spacy_stanza.load_pipeline(lang, processors=processors, verbose=False, **kw)
    except Exception:
        if not download: return None
        try:
            stanza.download(lang, processors=processors, verbose=False)
            return spacy_stanza.load_pipeline(lang, processors=processors, verbose=False, **kw)
        except Exception: return None

def _yake_terms(text, topk=12):
    'Keyphrases via yake — the zero-model, zero-label fallback when spaCy is absent.'
    try: from yake import KeywordExtractor
    except ImportError: return L()
    try: return L(KeywordExtractor(n=3, top=topk).extract_keywords(text)).map(lambda kv: kv[0])
    except Exception: return L()

_NOMINAL = ('NOUN', 'PROPN')

def _nominal_spans(sent):
    """Noun-phrase-like spans for a language whose spaCy class has no `noun_chunks` iterator.

    `doc.noun_chunks` is implemented for a handful of languages and raises `NotImplementedError`
    for the rest — including `sa`, so a stanza pipeline would take the whole prose path down. The
    approximation is a maximal run of adjacent nominals and their adjectives, which is what a
    noun-chunk iterator mostly produces anyway on a language with little function-word marking.
    It is deliberately a *span* rule rather than a dependency rule: stanza's Sanskrit parser is
    trained on Vedic prose, and its attachments on classical verse are much weaker than its tags."""
    out, run = L(), []
    def emit():
        # a run of adjectives with no nominal in it is a predicate ("is severe"), not a phrase
        if run and any(w.pos_ in _NOMINAL for w in run): out.append(sent.doc[run[0].i:run[-1].i+1])
    for w in sent:
        # ADJ joins a run from either side: English puts it before the noun (`radioactive
        # polonium`), Sanskrit routinely puts an agreeing adjective after it, and a span rule that
        # only looked backwards returned the bare noun in the first case and split the second
        if w.pos_ in _NOMINAL or w.pos_ == 'ADJ': run.append(w)
        else:
            emit(); run = []
    emit()
    return out

def _chunks_of(sent):
    'Noun chunks when the language has an iterator, else the POS-run approximation.'
    try: return list(sent.noun_chunks)
    except (NotImplementedError, ValueError): return list(_nominal_spans(sent))

def _wins_from_doc(doc, noun_chunks=True, keep=_KEEP_ENTS):
    """Sentence windows from a spaCy doc; shared by single-text and batched paths.

    The `seen` set drops a surface the sentence has already contributed. That matters more than it
    looks: an entity recognised by NER is *also* a noun chunk, so without the guard every named
    entity is emitted twice and its `freq` — which is the union-find rank `resolve_entities` picks
    a group's canonical name by — is inflated by exactly the mentions that were most reliable."""
    wins = []
    for sent in doc.sents:
        out, seen = L(), set()
        def add(s, k):
            n = _norm(s)
            if not n or n in seen: return
            seen.add(n)
            out.append((s, k))
        for e in sent.ents:
            if e.label_ in keep: add(e.text, e.label_.lower())
        if noun_chunks:
            for nc in _chunks_of(sent):
                if all(w.is_stop or w.is_punct or w.pos_ == 'PRON' for w in nc): continue
                add(nc.text, 'term')
        if out: wins.append(out)
    return L(wins)

def prose_windows(text,                 # chunk text
                  nlp=None,             # spaCy pipeline from spacy_pipe(); None -> yake fallback
                  noun_chunks=True,     # use doc.noun_chunks (the main recall driver on technical prose)
                  keep=_KEEP_ENTS,      # spaCy ent labels kept as a `kind` facet
                  topk=12):             # yake fallback keyphrase count
    '''Entity surfaces grouped into co-occurrence windows — one per sentence when spaCy is available.
    Sentence windows are what make PMI meaningful: page-sized chunks turn every entity pair into a
    clique and no amount of pruning recovers from that.'''
    if nlp: return _wins_from_doc(nlp(text), noun_chunks=noun_chunks, keep=keep)
    terms = _yake_terms(text, topk)
    if not terms: return L()
    wins = []
    for s in _sentences(text):
        sl = s.lower()
        hit = L([(t, 'keyphrase') for t in terms if t.lower() in sl])
        if hit: wins.append(hit)
    return L(wins)

def text_entities(text, nlp=None, **kw):
    'Entity surfaces for a prose chunk, flattened across windows. Returns L of (surface, kind).'
    seen, out = set(), L()
    for w in prose_windows(text, nlp, **kw):
        for s, k in w:
            n = _norm(s)
            if n and n not in seen: seen.add(n); out.append((s, k))
    return out

# %% ../nbs/05_graph.ipynb #build
_CODE_TYPES = {'FunctionDef','AsyncFunctionDef','ClassDef'}

def _is_code(chunk):
    md = chunk.get('metadata') or {}
    if not isinstance(md, dict): return False
    return md.get('lang') == '.py' or md.get('type') in _CODE_TYPES

def _pmi_edges(wins,              # list of entity-id sets (one per co-occurrence window)
               min_n=2,           # min co-occurrence count
               min_npmi=0.15,     # min normalized PMI
               max_df=0.4,        # drop entities present in more than this fraction of windows
               max_degree=48,     # keep only the strongest edges per node
               rel='cooc'):
    'Normalized-PMI co-occurrence edges over windows. max_df is what kills hub terms like "section".'
    n = len(wins)
    if n < 2: return []
    cnt = {}
    for w in wins:
        for e in w: cnt[e] = cnt.get(e, 0) + 1
    hub = {e for e, c in cnt.items() if c / n > max_df}
    pair = {}
    for w in wins:
        es = sorted(e for e in w if e not in hub)
        for i, a in enumerate(es):
            for b in es[i+1:]: pair[(a, b)] = pair.get((a, b), 0) + 1
    out = []
    for (a, b), c in pair.items():
        if c < min_n: continue
        pa, pb, pab = cnt[a]/n, cnt[b]/n, c/n
        npmi = math.log(pab/(pa*pb)) / (-math.log(pab)) if 0 < pab < 1 else 0.0
        if npmi < min_npmi: continue
        out.append(dict(src=a, dst=b, rel=rel, weight=round(npmi, 5), n=c))
    if max_degree:
        deg, kept = {}, []
        for e in sorted(out, key=lambda r: -r['weight']):
            if deg.get(e['src'], 0) < max_degree and deg.get(e['dst'], 0) < max_degree:
                deg[e['src']] = deg.get(e['src'], 0)+1; deg[e['dst']] = deg.get(e['dst'], 0)+1
                kept.append(e)
        out = kept
    return out

def build_graph(db,                  # Database with a chunk store
                chunks,              # chunk dicts ({'content','metadata'}) as returned by dir2chunks/pkg2chunks
                store='store',       # chunk store name
                prefix=None,         # graph table prefix
                nlp=None,            # spaCy pipeline for prose (None -> yake fallback)
                emb_fn=None,         # embedder for entity names (required for resolve_entities)
                code=True,           # extract AST symbols from code chunks
                prose=True,          # extract surfaces from prose chunks
                cooc=True,           # also write PMI co-occurrence edges over sentence windows
                min_n=2,             # min co-occurrence count
                min_npmi=0.15,       # min normalized PMI
                max_df=0.4,          # drop entities present in >max_df of windows
                max_degree=48,       # max cooc edges kept per node
                spacy_batch_size=64):# batch size for the batched spaCy pass over prose chunks
    'Extract entities + mentions + edges (exact for code, PMI co-occurrence for prose) from chunks.'
    g = db.get_graph(store, prefix)
    ents, mens, edges, wins = {}, {}, {}, []
    def ent(name, kind):
        'Register an entity by canonical name, returning its hash id.'
        n = _norm(name)
        if not n: return None
        i = _slug(n)
        e = ents.setdefault(i, dict(content=n, kind=kind, freq=0, canon=i))
        e['freq'] += 1
        return i
    def men(cid, eid, surface):
        if not (cid and eid): return
        m = mens.setdefault((cid, eid), dict(chunk_id=cid, entity_id=eid, surface=surface, n=0))
        m['n'] += 1
    def edge(s, d, rel, w=1.0):
        if not (s and d) or s == d: return
        e = edges.setdefault((s, d, rel), dict(src=s, dst=d, rel=rel, weight=0.0, n=0))
        e['weight'] += w; e['n'] += 1

    prose_q = []
    def prose_wins():
        'Windows per queued prose chunk — batched through nlp.pipe when a pipeline is given.'
        if nlp is None: return ((cid, prose_windows(txt)) for cid, txt in prose_q)
        docs = nlp.pipe(L(prose_q).itemgot(1), batch_size=spacy_batch_size)
        return ((cid, _wins_from_doc(d)) for (cid, _), d in zip(prose_q, docs))

    for c in L(chunks):
        txt = c.get('content')
        if not (txt and txt.strip()): continue
        cid = c.get('id') or _slug(txt)
        if code and _is_code(c):
            dname, calls, imps = code_entities(c)
            did = ent(dname, 'symbol') if dname else None
            if did: men(cid, did, dname)
            w = {did} if did else set()
            for nm in calls:
                i = ent(nm, 'symbol'); men(cid, i, nm); edge(did, i, 'calls'); w.add(i)
            for nm in imps:
                i = ent(nm, 'module'); men(cid, i, nm); edge(did, i, 'imports'); w.add(i)
            if len(w) > 1: wins.append(w - {None})
        elif prose: prose_q.append((cid, txt))

    for cid, wl in prose_wins():
        for win in wl:
            w = set()
            for surf, kind in win:
                i = ent(surf, kind)
                if i: men(cid, i, surf); w.add(i)
            if len(w) > 1: wins.append(w)

    rows = list(ents.values())
    if cooc and wins:
        for e in _pmi_edges(wins, min_n, min_npmi, max_df, max_degree):
            edges[(e['src'], e['dst'], e['rel'])] = e
    if rows:
        if emb_fn: process_content(g.entities, rows, embed=True, emb_fn=emb_fn)
        else:      g.entities.insert_all(rows, upsert=True, hash_id='id', hash_id_columns=['content'])
    if mens:  g.mentions.insert_all(list(mens.values()), upsert=True, pk=('chunk_id','entity_id'))
    if edges: g.edges.insert_all(list(edges.values()), upsert=True, pk=('src','dst','rel'))
    if emb_fn and rows: g.entities.rebuild_index()
    return dict(entities=len(rows), mentions=len(mens), edges=len(edges), windows=len(wins))

# %% ../nbs/05_graph.ipynb #resolve
_EXACT_KINDS = ('symbol', 'module', 'topic')   # names that are already canonical — never merge these

def _uf_find(par, x):
    while par[x] != x: par[x] = par[par[x]]; x = par[x]
    return x

def _uf_union(par, rank, a, b, name=None, ok=None, members=None, max_check=32):
    """Merge two groups. With `name`/`ok`, only if the merged group stays a **clique** under `ok`.

    Transitivity is the whole problem. `_lex_ok` accepts containment on purpose — `polonium` really
    is the same entity as `isolated polonium` — but plain union-find makes every accepted pair
    transitive, and overlapping keyphrases hand it a ladder: `marie curie isolated` ~
    `curie isolated polonium` ~ `isolated polonium` ~ `polonium`. Every rung is a legitimate merge
    and the endpoints are not. Measured on the yake path, 54 entities collapsed into one 18-member
    group in which Marie Curie *was* polonium.

    Checking the two representatives is not enough either, because which member becomes the
    representative is decided by `freq` and ties are broken by arrival order: `marie curie` and
    `pierre curie` fail the guard directly, and still merged through a `curie` that happened to be
    the root at the time. Requiring every cross pair to pass makes the group a clique, which is
    order-independent and is the invariant the caller can actually state — *every* member is
    lexically compatible with *every* other, so whichever one ends up canonical is defensible.

    `max_check` bounds the comparison at 32x32; groups this resolver produces are far smaller, and
    a group that ever got that large is one that should stop absorbing members anyway."""
    ra, rb = _uf_find(par, a), _uf_find(par, b)
    if ra == rb: return False
    if name is not None and ok is not None:
        A = (members.get(ra, [ra]) if members else [ra])[:max_check]
        B = (members.get(rb, [rb]) if members else [rb])[:max_check]
        if not all(ok(name[x], name[y]) for x in A for y in B): return False
    if rank[ra] < rank[rb]: ra, rb = rb, ra
    par[rb] = ra
    if members is not None: members.setdefault(ra, [ra]).extend(members.pop(rb, [rb]))
    return True

def _lexical_pairs(name, max_group=60):
    '''Candidate merge pairs by shared-token blocking — catches containment variants
    ("isolated polonium" / "polonium") that an ANN pass on short strings misses.
    Groups larger than max_group are skipped: common tokens would make this quadratic.'''
    inv = {}
    for i, s in name.items():
        for t in _toks(s):
            if len(t) > 2: inv.setdefault(t, []).append(i)
    seen = set()
    for ids in inv.values():
        if not (2 <= len(ids) <= max_group): continue
        for a in range(len(ids)):
            for b in range(a+1, len(ids)):
                p = (ids[a], ids[b]) if ids[a] < ids[b] else (ids[b], ids[a])
                if p not in seen: seen.add(p); yield p

def resolve_entities(db,                # Database
                     store='store',     # chunk store the graph belongs to
                     prefix=None,       # graph table prefix
                     thresh=0.18,       # max ANN distance for a merge candidate
                     lex=0.34,          # min token Jaccard for the lexical guard
                     k=8,               # ANN neighbours considered per entity
                     lexical=True,      # also block on shared tokens (works without embeddings)
                     max_group=60,      # skip token groups bigger than this in the lexical pass
                     skip_kinds=_EXACT_KINDS,  # kinds whose names are already canonical
                     dtype=np.float16):
    '''Merge near-duplicate entities: ANN + shared-token candidates, both gated by the lexical guard.

    Every merged group is a **clique** under the guard (`_uf_union`), not merely a chain of
    pairwise-valid merges — which is what stops containment rungs like
    `marie curie` ~ `curie` ~ `pierre curie` from fusing entities that fail the guard directly.
    Kinds in `skip_kinds` are left alone — AST symbols are exact identifiers, and resolving them
    collapses `search`/`fts_search`/`vec_search` into one node.'''
    g = db.get_graph(store, prefix)
    allr = L(g.entities(select='id, content, freq, embedding, kind'))
    rows = allr.filter(lambda r: r['kind'] not in set(skip_kinds or ()))
    if len(rows) < 2:
        return dict(merged=0, by_ann=0, by_lexical=0, edges=len(list(g.edges())),
                    entities=len(allr), resolvable=len(rows), canonical=len(allr))
    par  = {r['id']: r['id'] for r in rows}
    rank = {r['id']: (r['freq'] or 0) for r in rows}
    name = {r['id']: r['content'] for r in rows}
    ann_m = lex_m = 0
    guard, members = (lambda x, y: _lex_ok(x, y, lex)), {}
    for r in rows.filter(lambda r: r['embedding']):
        for h in g.entities.ann_search(r['embedding'], columns=['id','content'], limit=k, dtype=dtype):
            oid = h.get('id')
            if not oid or oid == r['id'] or oid not in par: continue
            if (h.get('_dist') or 1.0) > thresh: continue
            if not _lex_ok(r['content'], h['content'], lex): continue
            if _uf_union(par, rank, r['id'], oid, name, guard, members): ann_m += 1
    if lexical:
        for a, b in _lexical_pairs(name, max_group):
            if _lex_ok(name[a], name[b], lex) and _uf_union(par, rank, a, b, name, guard, members): lex_m += 1
    upd = [(_uf_find(par, i), i) for i in par]
    db.conn.cursor().executemany(f'update {g.entities.name} set canon=? where id=?', upd)
    canon = {i: c for c, i in upd}
    n_edges = _collapse_edges(db, g, canon)
    skipped = len(allr) - len(rows)
    return dict(merged=ann_m+lex_m, by_ann=ann_m, by_lexical=lex_m, edges=n_edges,
                entities=len(allr), resolvable=len(rows),
                canonical=len({c for c, _ in upd}) + skipped)

def _collapse_edges(db, g, canon):
    '''Rewrite edge endpoints onto canonical ids. Traversal reads src/dst straight from the table,
    so leaving raw ids here would silently strand every merged node.'''
    rows = list(g.edges())
    if not rows: return 0
    agg = {}
    for r in rows:
        s, d = canon.get(r['src'], r['src']), canon.get(r['dst'], r['dst'])
        if s == d: continue
        if s > d and r['rel'] == 'cooc': s, d = d, s     # cooc is symmetric; keep one direction
        k = (s, d, r['rel'])
        a = agg.setdefault(k, dict(src=s, dst=d, rel=r['rel'], weight=0.0, n=0))
        a['weight'] = max(a['weight'], r['weight'] or 0.0); a['n'] += (r['n'] or 0)
    g.edges.delete_where()
    g.edges.insert_all(list(agg.values()), upsert=True, pk=('src','dst','rel'))
    return len(agg)

# %% ../nbs/05_graph.ipynb #cooc
def cooccur_edges(db,                 # Database
                  store='store',      # chunk store
                  prefix=None,        # graph table prefix
                  min_n=2,            # min co-occurrence count
                  min_npmi=0.15,      # min normalized PMI (prunes stopword-ish hub nodes)
                  max_df=0.4,         # drop entities present in >max_df of chunks
                  max_degree=48,      # keep only the strongest edges per node
                  rel='cooc',
                  use_canon=True):    # collapse to canonical ids from resolve_entities
    '''Rebuild co-occurrence edges from the stored mentions, using the chunk as the window.
    build_graph already does this over sentence windows; use this to recompute after
    resolve_entities, or for corpora indexed without a spaCy pass.'''
    g = db.get_graph(store, prefix)
    canon = {}
    if use_canon:
        canon = {r['id']: (r['canon'] or r['id']) for r in g.entities(select='id, canon')}
    cid_ents = {}
    for m in g.mentions(select='chunk_id, entity_id'):
        e = canon.get(m['entity_id'], m['entity_id'])
        cid_ents.setdefault(m['chunk_id'], set()).add(e)
    out = _pmi_edges(list(cid_ents.values()), min_n, min_npmi, max_df, max_degree, rel)
    if out: g.edges.insert_all(out, upsert=True, pk=('src','dst','rel'))
    return len(out)

# %% ../nbs/05_graph.ipynb #topics
# connector words — cluster names built from these describe the corpus, not the cluster
_STOP = set('''the a an and or of to in is are was were be been being for on at by with from this that these those
it its as not but if then than so such can will would could should may might do does did have has had he she they
we you i him her them our your their about into over under after before between out up down off only own same too
very just also each other more most some any no nor own s t don now here there when where why how all both'''.split())
_LWORD = re.compile(r'[A-Za-z_][A-Za-z0-9_]{2,}')   # keeps identifiers whole

def ctfidf_labels(texts,        # one text per member, aligned with `lab`
                  lab,          # cluster index per member
                  k,            # number of clusters
                  top_n=4,      # terms per label
                  stop=None,    # stopword set (defaults to _STOP)
                  sep=', '):
    '''Name each cluster by terms common inside it and rare across the other clusters.

    Plain term frequency names every cluster after the same few words the corpus is made of;
    weighting by IDF across the *clusters* is what makes the names differ from each other,
    which is the only job they have. (Approach taken from lego/atlas/cluster.py.)'''
    st = _STOP if stop is None else stop
    tf = [{} for _ in range(k)]
    for t, j in zip(texts, lab):
        for w in set(_LWORD.findall((t or '').lower())):
            if w in st or len(w) < 3: continue
            tf[j][w] = tf[j].get(w, 0) + 1
    df = {}
    for d in tf:
        for w in d: df[w] = df.get(w, 0) + 1
    out = []
    for j, d in enumerate(tf):
        n = max(1, sum(1 for x in lab if x == j))
        sc = {w: (c/n) * math.log(k/df[w]) for w, c in d.items() if df[w] < k}
        top = sorted(sc.items(), key=lambda kv: -kv[1])[:top_n]
        out.append(sep.join(w for w, _ in top))
    return out

def _usearch_clusters(idx, min_count, max_count):
    '''(centroid, members) straight off the HNSW graph. usearch walks the index levels, so it needs
    a tall enough graph and raises "Index too small to cluster!" on small corpora — caller falls back.'''
    kw = {k: v for k, v in dict(min_count=min_count, max_count=max_count).items() if v}
    cl = idx.cluster(**kw)
    keys, _ = cl.centroids_popularity
    out = L()
    for ck in np.atleast_1d(keys).tolist():
        try: out.append((int(ck), [int(x) for x in np.atleast_1d(cl.members_of(ck)).tolist()]))
        except Exception: continue
    return out

def _knn_clusters(idx, keys, k=8, max_size=None, min_sim=None, dtype=np.float16):
    '''(seed, members) from a greedy pass over the kNN graph harvested from HNSW. Works at any size.
    Seeds at the densest unassigned node and claims its unassigned neighbours, so clusters stay
    bounded — plain label propagation collapses a dense kNN graph into one giant component.'''
    keys = list(keys)
    if len(keys) < 4: return L()
    vecs = np.stack([np.asarray(idx[kk], dtype=dtype).reshape(-1) for kk in keys])
    res = idx.search(vecs, count=min(k+1, len(keys)))
    nbr, sims = {}, []
    for i, kk in enumerate(keys):
        ks = np.atleast_1d(res.keys[i]).tolist()
        ds = np.atleast_1d(res.distances[i]).tolist()
        n = [(int(a), 1.0-float(b)) for a, b in zip(ks, ds) if int(a) != kk]
        nbr[kk] = n
        sims += [s for _, s in n]
    if min_sim is None: min_sim = float(np.median(sims)) if sims else 0.0
    cap = max_size or max(k, 4)
    dens = {kk: sum(s for _, s in v if s >= min_sim) for kk, v in nbr.items()}
    out, seen = L(), set()
    for kk in sorted(keys, key=lambda x: -dens.get(x, 0.0)):
        if kk in seen: continue
        grp = [kk]; seen.add(kk)
        for nk, s in sorted(nbr.get(kk, []), key=lambda t: -t[1]):
            if len(grp) >= cap: break
            if nk not in seen and s >= min_sim: grp.append(nk); seen.add(nk)
        out.append((int(kk), [int(x) for x in grp]))
    return out

def _cluster_groups(idx,               # usearch Index
                    keys=None,         # keys to cluster (defaults to everything in the index)
                    min_count=None,    # usearch: smallest cluster to emit
                    max_count=None,    # usearch: largest cluster to emit
                    k=8,               # neighbours per node in the kNN fallback
                    dtype=np.float16):
    '''`([(centroid, members)], method)` for an index.

    usearch raises rather than degrading when the HNSW graph has too few levels to cut, so the
    greedy kNN pass is not a nicety: without it clustering is simply unavailable on a fresh or
    small store, which is exactly when someone is most likely to try it.'''
    try: return _usearch_clusters(idx, min_count, max_count), 'usearch'
    except Exception:
        ks = np.atleast_1d(idx.keys).tolist() if keys is None else list(keys)
        return _knn_clusters(idx, ks, k, dtype=dtype), 'knn'

def topic_nodes(db,                # Database
                store='store',     # chunk store (must be ANN-registered)
                prefix=None,       # graph table prefix
                min_count=None,    # usearch cluster min size
                max_count=None,    # usearch cluster max size
                k=8,               # neighbours per node in the fallback kNN graph
                min_size=2,        # smallest cluster kept as a topic
                label_k=4,         # terms per topic label
                max_label_chars=4000,
                dtype=np.float16):
    'Cluster the store index into topic nodes labelled by c-TF-IDF. Returns {topics, method}.'
    g = db.get_graph(store, prefix)
    m = db._ann_meta(store)
    if not (m and m['ndim']): return dict(topics=0, method=None)
    idx = db.get_index(store)
    if idx.size < 4: return dict(topics=0, method=None)
    dt = _np_dtype.get(m['dtype'], dtype)
    rid2cid = {r['rowid']: r['id'] for r in db.t[store](select=f'{_rid()}, id')}
    groups, method = _cluster_groups(idx, rid2cid.keys(), min_count, max_count, k, dt)
    kept = [[rid2cid[r] for r in mem if r in rid2cid] for _, mem in groups]
    kept = [c for c in kept if len(c) >= min_size]
    if not kept: return dict(topics=0, method=method)
    # labels are scored across all clusters at once, so gather members first
    txt = {r['id']: r['content'] for r in db.t[store](select='id, content',
                                                      where=_in('id', [c for g_ in kept for c in g_[:24]]))}
    texts, lab = [], []
    for j, cids in enumerate(kept):
        for c in cids[:24]: texts.append((txt.get(c) or '')[:max_label_chars]); lab.append(j)
    names = ctfidf_labels(texts, lab, len(kept), label_k)
    ents, mens = [], []
    for j, cids in enumerate(kept):
        # deliberately not _norm(): topic labels are multi-phrase and would trip its 5-token cap
        name = f'topic: {names[j]}'[:60] if names[j] else f'topic-{j}'
        eid = _slug(name)
        ents.append(dict(content=name, kind='topic', freq=len(cids), canon=eid))
        mens += [dict(chunk_id=c, entity_id=eid, surface=name, n=1) for c in cids]
    if ents: g.entities.insert_all(ents, upsert=True, hash_id='id', hash_id_columns=['content'])
    if mens: g.mentions.insert_all(mens, upsert=True, pk=('chunk_id','entity_id'))
    return dict(topics=len(ents), method=method)

# %% ../nbs/05_graph.ipynb #865c2e21
@patch
def _cluster_cached(self:Table, min_count, max_count, k, dtype):
    'Cluster once per (store, params, index size). `peers` would otherwise recluster on every call.'
    idx = self.db.get_index(self.name)
    ck = (self.name, min_count, max_count, k, idx.size)
    cache = getattr(self.db, '_cluster_cache', None)
    if cache is None: cache = self.db._cluster_cache = {}
    if ck not in cache:
        groups, method = _cluster_groups(idx, None, min_count, max_count, k, dtype)
        assign = {m: g for _, g in groups for m in g}
        cache[ck] = (groups, method, assign)
    return cache[ck]

@patch
def _member_rows(self:Table, keys, columns=None):
    'Store rows for a list of usearch keys, keyed by rowid. `content` is always fetched (labels need it).'
    if not keys: return {}
    cols = list(dict.fromkeys([c for c in (columns or []) if c != 'rowid'] + ['content']))
    sel, out = ','.join(cols + [_rid()]), {}
    for i in range(0, len(keys), 400):
        for r in self.db.q(f'select {sel} from {self.name} where {_in("rowid", keys[i:i+400])}'): out[r['rowid']] = r
    return out

@patch
def clusters(self:Table,              # ANN-registered store
             min_count:int=None,      # usearch: smallest cluster to emit
             max_count:int=None,      # usearch: largest cluster to emit
             k:int=8,                 # neighbours per node in the kNN fallback
             min_size:int=2,          # drop groups smaller than this
             label_k:int=4,           # terms per c-TF-IDF label
             members:int=24,          # member rows fetched per cluster
             columns:list=None,       # store columns to return per member row
             max_label_chars:int=4000,# per-member text budget for labelling
             dtype=np.float16):
    '''The corpus grouped by embedding shape, each group named by c-TF-IDF.

    Returns `AttrDict(clusters, method, note)`; each cluster is
    `AttrDict(centroid, size, label, member_keys, members)`. `method` is `usearch` or the `knn` fallback.'''
    m = self.db._ann_meta(self.name)
    if not m: return AttrDict(clusters=L(), method=None, note=f'{self.name!r} is not an ANN store')
    if not m['ndim']: return AttrDict(clusters=L(), method=None, note=f'{self.name!r} has no vectors yet')
    idx = self.db.get_index(self.name)
    if idx.size < 4: return AttrDict(clusters=L(), method=None, note=f'index holds {idx.size} vectors; too few to cluster')
    dt = _np_dtype.get(m['dtype'], dtype)
    groups, method, _ = self._cluster_cached(min_count, max_count, k, dt)
    kept = [(c, g) for c, g in groups if len(g) >= min_size]
    if not kept: return AttrDict(clusters=L(), method=method, note=f'no group reached min_size={min_size}')
    rows = self._member_rows([r for _, g in kept for r in g[:members]], columns)
    texts, lab = [], []
    for j, (_, g) in enumerate(kept):
        for r in g[:members]: texts.append(((rows.get(r) or {}).get('content') or '')[:max_label_chars]); lab.append(j)
    names = ctfidf_labels(texts, lab, len(kept), label_k)
    out = L(AttrDict(centroid=c, size=len(g), label=names[j] or f'group-{j}', member_keys=g,
                     members=L(rows[r] for r in g[:members] if r in rows))
            for j, (c, g) in enumerate(kept))
    return AttrDict(clusters=out.sorted(key=lambda c: -c.size), method=method,
                    note=f'{len(out)} clusters over {idx.size} vectors ({method})')

@patch
def peers(self:Table,            # ANN-registered store
          key:int,               # usearch key (rowid) whose group you want
          limit:int=25,          # members to return
          columns:list=None,     # store columns to return per member row
          min_count:int=None,    # usearch: smallest cluster to emit
          max_count:int=None,    # usearch: largest cluster to emit
          k:int=8,               # neighbours per node in the kNN fallback
          dtype=np.float16):
    '''The group `key` belongs to — its family, not a ranked list of what is nearest to it.

    Degrades to `ann_neighbors` (and says so in `note`) whenever the index cannot be clustered or
    the row landed in a group of one. Returns `AttrDict(hits, method, note)`.'''
    nbr = lambda note: AttrDict(hits=L(self.ann_neighbors(key, limit, columns, dtype=dtype)), method='ann', note=note)
    m = self.db._ann_meta(self.name)
    if not m: return AttrDict(hits=L(), method=None, note=f'{self.name!r} is not an ANN store')
    if not m['ndim']: return AttrDict(hits=L(), method=None, note=f'{self.name!r} has no vectors yet')
    idx = self.db.get_index(self.name)
    if not idx.size or not idx.contains(key): return AttrDict(hits=L(), method=None, note=f'key {key} is not indexed')
    dt = _np_dtype.get(m['dtype'], dtype)
    if idx.size < 4: return nbr(f'index holds {idx.size} vectors; showing nearest neighbours')
    _, method, assign = self._cluster_cached(min_count, max_count, k, dt)
    grp = assign.get(key)
    if not grp: return nbr('row is in no cluster; showing nearest neighbours')
    mem = [x for x in grp if x != key][:limit]
    if not mem: return nbr('cluster has one member; showing nearest neighbours')
    rows, order = self._member_rows(mem, columns), {r: i for i, r in enumerate(mem)}
    return AttrDict(hits=L(rows[r] for r in sorted(rows, key=lambda r: order.get(r, 1<<30)) if r in rows),
                    method=method, note=f'cluster of {len(grp)} ({method})')

# %% ../nbs/05_graph.ipynb #ppr
def _adjacency(g, nodes, hops=2, max_nodes=4000):
    'BFS the edge table out to `hops` from `nodes`; returns an undirected dict-of-dict adjacency.'
    adj, seen, frontier = {}, set(nodes), set(nodes)
    for _ in range(max(hops, 0)):
        if not frontier or len(seen) >= max_nodes: break
        fl = list(frontier)
        rows = []
        for i in range(0, len(fl), 400):
            b = fl[i:i+400]
            rows += g.edges(where=f"{_in('src', b)} OR {_in('dst', b)}")
        nxt = set()
        for r in rows:
            s, d, w = r['src'], r['dst'], (r['weight'] or 1.0)
            adj.setdefault(s, {})[d] = max(adj.setdefault(s, {}).get(d, 0.0), w)
            adj.setdefault(d, {})[s] = max(adj.setdefault(d, {}).get(s, 0.0), w)
            for x in (s, d):
                if x not in seen: nxt.add(x)
        seen |= nxt
        frontier = nxt
    return adj

def _ppr(adj, seeds, damping=0.85, iters=12):
    'Personalized PageRank over a dict-of-dict adjacency.'
    if not seeds: return {}
    tot = sum(seeds.values()) or 1.0
    p0 = {k: v/tot for k, v in seeds.items()}
    r = dict(p0)
    for _ in range(iters):
        nxt = {}
        for u, mass in r.items():
            nb = adj.get(u)
            if not nb: continue
            s = sum(nb.values()) or 1.0
            for v, w in nb.items(): nxt[v] = nxt.get(v, 0.0) + damping*mass*w/s
        for k, v in p0.items(): nxt[k] = nxt.get(k, 0.0) + (1-damping)*v
        r = nxt
    return r

# %% ../nbs/05_graph.ipynb #rrf_all
def rrf_all(lists,              # list of ranked result lists
            k=60,               # RRF k
            limit=50,           # max results
            id_key='rowid',     # join key
            weights=None):      # per-list weights
    'Reciprocal Rank Fusion over any number of ranked lists.'
    ws = weights or [1.0]*len(lists)
    scores = {}
    for lst, w in zip(lists, ws):
        for rank, row in enumerate(lst or []):
            rid = row.get(id_key, id(row))
            if rid in scores: scores[rid]['_rrf_score'] += w/(k + rank)
            else: scores[rid] = merge(row, {'_rrf_score': w/(k + rank)})
    return sorted(scores.values(), key=lambda x: x['_rrf_score'], reverse=True)[:limit]

# %% ../nbs/05_graph.ipynb #graph_search
@patch
def graph_search(self:Database,
                 q:str,                 # query string
                 emb:bytes,             # query embedding
                 columns:list=None,     # columns to return
                 limit:int=20,          # max results
                 table_name='store',    # chunk store
                 prefix=None,           # graph table prefix
                 seed_n:int=12,         # hybrid hits used to seed the graph walk
                 hops:int=2,            # edge-table BFS depth
                 damping:float=0.85,    # PPR damping
                 iters:int=10,          # PPR iterations
                 graph_w:float=0.5,     # weight of the graph leg (low by default — see docstring)
                 rrf_k:int=60,
                 use_canon=True,
                 **kw):                 # forwarded to Database.search
    '''Hybrid search plus a graph leg: PPR over the entity graph seeded by the top hybrid hits.

    The graph leg is weighted low on purpose. It pays when the answer shares no vocabulary with
    the query and is reachable only along an entity path — common in prose, rare in code, where
    call edges link different levels of abstraction rather than substitutable answers. On code
    corpora prefer `graph_w=0` and use the graph for context assembly (callers/callees of a hit)
    rather than for ranking.'''
    g = self.get_graph(table_name, prefix)
    cols = list(columns or [])
    if 'rowid' not in cols: cols = ['rowid'] + cols
    if 'id' not in cols: cols = cols + ['id']
    base = self.search(q, emb, columns=cols, limit=max(seed_n*3, limit), table_name=table_name,
                       rrf=False, **kw)
    if not base: return []
    fts, vec = base['fts'], base['vec']
    seed_rows = rrf_all([fts, vec], rrf_k, seed_n)
    seed_cids = [r['id'] for r in seed_rows if r.get('id')]
    if not seed_cids: return rrf_all([fts, vec], rrf_k, limit)
    canon = {}
    if use_canon: canon = {r['id']: (r['canon'] or r['id']) for r in g.entities(select='id, canon')}
    seeds = {}
    for i in range(0, len(seed_cids), 400):
        for m in g.mentions(select='chunk_id, entity_id', where=_in('chunk_id', seed_cids[i:i+400])):
            e = canon.get(m['entity_id'], m['entity_id'])
            seeds[e] = seeds.get(e, 0.0) + 1.0
    if not seeds: return rrf_all([fts, vec], rrf_k, limit)
    adj = _adjacency(g, set(seeds), hops)
    mass = _ppr(adj, seeds, damping, iters)
    if not mass: return rrf_all([fts, vec], rrf_k, limit)
    top = sorted(mass.items(), key=lambda kv: -kv[1])[:200]
    eids = [e for e, _ in top if _ > 0]
    if not eids: return rrf_all([fts, vec], rrf_k, limit)
    inv = {}
    for i in range(0, len(eids), 400):
        for m in g.mentions(select='chunk_id, entity_id', where=_in('entity_id', eids[i:i+400])):
            e = canon.get(m['entity_id'], m['entity_id'])
            inv[m['chunk_id']] = inv.get(m['chunk_id'], 0.0) + mass.get(e, 0.0)
    if not inv: return rrf_all([fts, vec], rrf_k, limit)
    ranked = sorted(inv.items(), key=lambda kv: -kv[1])[:limit*3]
    cids = [c for c, _ in ranked]
    sel = ','.join([_rid() if c == 'rowid' else c for c in cols])
    rows = {r['id']: r for r in self.t[table_name](select=sel, where=_in('id', cids))}
    graph_leg = [rows[c] for c, _ in ranked if c in rows]
    return rrf_all([fts, vec, graph_leg], rrf_k, limit, weights=[1.0, 1.0, graph_w])

# %% ../nbs/05_graph.ipynb #stats
def graph_stats(db, store='store', prefix=None):
    'Row counts and top-degree nodes for a built graph.'
    g = db.get_graph(store, prefix)
    ne = first(db.q(f'select count(*) c from {g.entities.name}'))['c']
    nm = first(db.q(f'select count(*) c from {g.mentions.name}'))['c']
    ng = first(db.q(f'select count(*) c from {g.edges.name}'))['c']
    nc = first(db.q(f'select count(distinct canon) c from {g.entities.name}'))['c']
    top = db.q(f'''select e.content, e.kind, count(*) d from {g.edges.name} g
                   join {g.entities.name} e on e.id=g.src group by g.src order by d desc limit 10''')
    return dict(entities=ne, canonical=nc, mentions=nm, edges=ng, top_degree=top)
