# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_sanskrit.ipynb.

# %% auto #0
__all__ = ['VEDIC_MARKS', 'DANDA', 'DDANDA', 'SANSKRIT_TOKENIZE', 'CITE_RE', 'VERSE_TARGET', 'VERSE_MAX', 'GANAS', 'METERS',
           'VRTTA_EXTRA', 'MATRA_METERS', 'CATURMATRA', 'PADA_RANGE', 'MW_URL', 'GLOSS_STOP', 'strip_vedic',
           'deva2ascii', 'detect_script', 'fold_token', 'sanskrit_tokenizer', 'register_sanskrit', 'cite_parts',
           'verse_spans', 'chunk_verses', 'VerseChunker', 'ProseChunker', 'deva2iast', 'syllables', 'scan', 'ganas',
           'gana_pattern', 'metrical_text', 'matras', 'detect_matra_meter', 'detect_meter', 'verse_units', 'verse_meta',
           'lemma_facets', 'sanskrit_meta', 'gretil_parse', 'tei_parse', 'vr_xml_parse', 'dcs_parse', 'is_sanskrit',
           'sanskrit_parse', 'register_profiles', 'sanskrit_home', 'vidyut_data', 'to_slp1', 'from_slp1', 'vidyut_pipe',
           'sanskrit_terms', 'mw_lexicon', 'gloss_facets']

# %% ../nbs/09_sanskrit.ipynb #c05
import re, unicodedata
from functools import lru_cache
from fastcore.all import L, Path, ifnone

VEDIC_MARKS = re.compile('['
    '॑-॔'      # udatta, anudatta, devanagari grave/acute
    '᳐-᳹'      # vedic extensions: tone marks, nasalisations
    '꣠-꣰'      # devanagari extended combining digits, stopping before the candrabindu block
    ']')

DANDA, DDANDA = '।', '॥'          # । ॥

_INDEP = {'अ':'a','आ':'a','इ':'i','ई':'i','उ':'u','ऊ':'u','ऋ':'r','ॠ':'r','ऌ':'l','ॡ':'l',
          'ए':'e','ऐ':'ai','ओ':'o','औ':'au','ऍ':'e','ऎ':'e','ऑ':'o','ऒ':'o'}
_CONS  = {'क':'k','ख':'kh','ग':'g','घ':'gh','ङ':'n','च':'c','छ':'ch','ज':'j','झ':'jh','ञ':'n',
          'ट':'t','ठ':'th','ड':'d','ढ':'dh','ण':'n','त':'t','थ':'th','द':'d','ध':'dh','न':'n',
          'प':'p','फ':'ph','ब':'b','भ':'bh','म':'m','य':'y','र':'r','ल':'l','व':'v',
          'श':'s','ष':'s','स':'s','ह':'h','ळ':'l','ऴ':'l','ऱ':'r','ऩ':'n',
          'क़':'k','ख़':'kh','ग़':'g','ज़':'z','ड़':'d','ढ़':'dh','फ़':'f','य़':'y'}
_MATRA = {'ा':'a','ि':'i','ी':'i','ु':'u','ू':'u','ृ':'r','ॄ':'r','ॢ':'l','ॣ':'l',
          'े':'e','ै':'ai','ो':'o','ौ':'au','ॅ':'e','ॆ':'e','ॉ':'o','ॊ':'o'}
# `ꣳ`/`ꣲ`/`꣰` are the Vedic candrabindu signs — a nasal, not an accent, so they fold to `m` and
# line up with the `ṃ` an IAST edition of the same line prints.
_SIGN  = {'ं':'m','ः':'h','ँ':'m','ऽ':'', '़':'', 'ꣲ':'m','ꣳ':'m','ꣴ':'m','ꣵ':'m','ꣶ':'m','ꣷ':'m'}
_VIRAMA = '्'
_DIGITS = {chr(0x966+i): str(i) for i in range(10)}

def strip_vedic(s:str) -> str:
    'Drop Vedic tone marks from Devanagari, leaving Latin diacritics alone. NFC out.'
    if not s: return ''
    return unicodedata.normalize('NFC', VEDIC_MARKS.sub('', unicodedata.normalize('NFD', s)))

def deva2ascii(s:str) -> str:
    'Devanagari to a bare ASCII key, applying the implicit `a` of an unmarked consonant.'
    out, i, n = [], 0, len(s)
    while i < n:
        ch = s[i]
        if ch in _CONS:
            out.append(_CONS[ch]); i += 1
            # look past a nukta that was not pre-composed
            while i < n and s[i] == '़': i += 1
            if i < n and s[i] == _VIRAMA: i += 1; continue          # bare consonant, no vowel
            if i < n and s[i] in _MATRA: out.append(_MATRA[s[i]]); i += 1; continue
            out.append('a'); continue                                # implicit vowel
        if ch in _INDEP: out.append(_INDEP[ch]); i += 1; continue
        if ch in _SIGN:  out.append(_SIGN[ch]);  i += 1; continue
        if ch in _MATRA: out.append(_MATRA[ch]); i += 1; continue    # orphan matra
        if ch in _DIGITS: out.append(_DIGITS[ch]); i += 1; continue
        if ch == _VIRAMA: i += 1; continue
        out.append(ch); i += 1
    return ''.join(out)

def _latn_fold(s:str) -> str:
    'IAST/ISO to ASCII — the same folding `simplify casefold` already applies to a Latin token.'
    d = unicodedata.normalize('NFD', s)
    return ''.join(c for c in d if unicodedata.category(c) != 'Mn').lower()

_DEVA = re.compile('[ऀ-ॿ᳐-᳹꣠-ꣿ]')

def detect_script(s:str) -> str:
    "`'deva'`, `'latn'` or `'other'` — enough to pick a folding path."
    if not s: return 'other'
    d = len(_DEVA.findall(s))
    l = sum(1 for c in s if 'a' <= c.lower() <= 'z' or unicodedata.category(c) == 'Ll')
    if d and d >= l: return 'deva'
    return 'latn' if l else 'other'

@lru_cache(maxsize=1<<16)
def fold_token(s:str) -> str:
    '''The ASCII index key for one token, whatever script it arrived in.

    Cached because it is called once per token per FTS write *and* per query, and a corpus is a
    small vocabulary repeated: 70,413 tokens of the eval corpus are 4,153 distinct strings, so
    94% of the calls are asking a question that has already been answered. It is three unicode
    normalisations and a per-character category scan deep, which is why it was a third of the cost
    of indexing a corpus with no Sanskrit in it at all. Pure function of `s`, so the cache is only
    ever a memo — same output, 5.5x fewer of them computed.'''
    s = strip_vedic(s)
    return _latn_fold(deva2ascii(s) if _DEVA.search(s) else s)


# %% ../nbs/09_sanskrit.ipynb #c08
SANSKRIT_TOKENIZE = 'sanskrit'

def sanskrit_tokenizer(con, args):
    'A *wrapping* FTS5 tokenizer that folds Sanskrit so a query matches regardless of script.'
    import apsw.fts5
    rest = [a for a in args if '=' not in a]
    opts = dict(a.split('=', 1) for a in args if '=' in a)
    keep_orig = opts.get('original', '1') != '0'
    inner = con.fts5_tokenizer(rest[0], rest[1:]) if rest else apsw.fts5.UnicodeWordsTokenizer(con, [])
    def tok(utf8, flags, locale):
        for start, end, *toks in inner(utf8, flags, locale):
            out = []
            for t in toks:
                if keep_orig and t not in out: out.append(t)
                if (f := fold_token(t)) and f not in out: out.append(f)
            if out: yield (start, end, *out)
    return tok

def register_sanskrit(db):
    "Register the `sanskrit` FTS5 tokenizer on a connection. Idempotent."
    conn = getattr(db, 'conn', db)
    try: conn.register_fts5_tokenizer(SANSKRIT_TOKENIZE, sanskrit_tokenizer)
    except Exception: pass
    return db


# %% ../nbs/09_sanskrit.ipynb #c11
CITE_RE = re.compile(r'(?:\|\||//)\s*([A-Za-zĀ-ſ]+)[_\s.]([\d,.\-]+[a-z]?(?:\[[^\]\n]{0,16}\])?)\s*(?:\|\||//)')
# A Devanagari verse number: `॥ १॥` or `॥ 12 ॥`
_DEVNUM = re.compile(r'॥\s*([\d०-९]+)\s*॥')

def cite_parts(c:str) -> tuple:
    "`'BrhUp_1,1.2'` -> `('BrhUp', ['1','1','2'])` — the siglum and its hierarchy."
    c = re.sub(r'\[[^\]]*\]', '', (c or '')).strip()   # drop a `[57M]` alternate-edition number
    m = re.match(r'([^\s_]+)[_\s]([\d,.\-]+[a-z]?)$', c) or re.match(r'([A-Za-zĀ-ſ]+)[.]([\d,.\-]+[a-z]?)$', c)
    if not m: return (c, [])
    return m.group(1), [p for p in re.split(r'[,.]', m.group(2)) if p]

_GLOSS = re.compile(r'(?:[ \t]*\n)?[ \t]*>[^\n]*')
_HEAD  = re.compile(r'^[ \t]*#{1,6}[ \t]+\S', re.M)

def _with_gloss(text:str, end:int) -> int:
    'Extend a cut past the gloss lines that trail it.'
    while (m := _GLOSS.match(text, end)) and m.end() > end: end = m.end()
    return end

def verse_spans(text:str) -> L:
    'Split `text` into verse units, returning `(start, end, text, citation)`.'
    if not (text or '').strip(): return L()
    cuts = []
    for m in CITE_RE.finditer(text): cuts.append((_with_gloss(text, m.end()), f'{m.group(1)}_{m.group(2)}'))
    if not cuts:
        for m in _DEVNUM.finditer(text): cuts.append((_with_gloss(text, m.end()), m.group(1)))
    if not cuts:
        for m in re.finditer(r'(?:॥|\|\||//)[ \t]*(?=\n|$)', text):
            cuts.append((_with_gloss(text, m.end()), None))
    cuts += [(m.start(), None) for m in _HEAD.finditer(text) if m.start() > 0]
    cuts.sort()
    out, prev = L(), 0
    for end, cite in cuts:
        if end <= prev: continue
        if (seg := text[prev:end]).strip(): out.append((prev, end, seg.strip(), cite))
        prev = end
    if (tail := text[prev:]).strip(): out.append((prev, len(text), tail.strip(), None))
    return out

_CLAUSE = re.compile(r'(?:॥|।|//|/|\|)[ \t]*')

def _clause_spans(seg:str) -> L:
    'Split an over-long unit at its clause daṇḍas, never mid-clause.'
    parts, prev = L(), 0
    for m in _CLAUSE.finditer(seg):
        if (s := seg[prev:m.end()]).strip(): parts.append(s.strip())
        prev = m.end()
    if (t := seg[prev:]).strip(): parts.append(t.strip())
    return parts or L([seg.strip()])

def _atoms(seg:str, max_chars:int) -> L:
    'The smallest pieces an over-long unit may be cut into, each with its gloss attached.'
    out = L()
    for p in _clause_spans(seg):
        if len(p) <= max_chars: out.append(p); continue
        lines = [l.strip() for l in p.splitlines() if l.strip()]
        out += (lines if len(lines) > 1 else [p])
    atoms = L()
    for p in out:
        if p.lstrip().startswith('>') and atoms: atoms[-1] += '\n' + p
        else: atoms.append(p)
    return atoms


# %% ../nbs/09_sanskrit.ipynb #c14
VERSE_TARGET, VERSE_MAX = 300, 900

def _width(parts) -> int:
    'Length the parts will have once joined — the newlines count against the budget too.'
    return sum(map(len, parts)) + max(len(parts) - 1, 0)

def chunk_verses(text:str,                 # source text
                 target:int=VERSE_TARGET,  # pack short units forward up to this many chars
                 max_chars:int=VERSE_MAX,  # split a unit longer than this at clause boundaries
                 pack_cited:bool=False,    # let consecutive cited units share a chunk up to `target`
                 ) -> L:
    'Verse-aware chunks: cut on citation/daṇḍa, pack short units, split long prose.'
    units = verse_spans(text)
    if not units: return L([text.strip()]) if (text or '').strip() else L()
    out, buf, cited = L(), [], False
    def flush():
        nonlocal buf, cited
        if buf: out.append('\n'.join(buf).strip())
        buf, cited = [], False
    for _, _, seg, cite in units:
        # A heading opens a section; packing across it would put the tail of one section and the
        # head of the next into a chunk whose breadcrumb can only name one of them.
        if _HEAD.match(seg): flush()
        if len(seg) > max_chars:
            flush()
            cur = []
            for a in _atoms(seg, max_chars):
                if cur and _width(cur) + len(a) > max_chars: out.append('\n'.join(cur)); cur = []
                cur.append(a)
            if cur: out.append('\n'.join(cur))
            continue
        # close the run *before* it overflows, so packing can never produce a chunk larger than a
        # unit the embedder was never going to fit
        if buf and _width(buf) + len(seg) > max_chars: flush()
        buf.append(seg)
        if cite: cited = True
        # a citation closes the unit; otherwise pack forward until the target is reached
        if (cited and not pack_cited) or _width(buf) >= target: flush()
    flush()
    return out.filter(lambda s: s.strip())

class _Chunk:
    'Minimal chonkie-compatible chunk (chonkie.types.Chunk is imported lazily to keep this light).'
    def __init__(self, text, start_index, end_index, token_count=0):
        self.text, self.start_index, self.end_index, self.token_count = text, start_index, end_index, token_count
    def __repr__(self): return f'_Chunk({self.text[:40]!r}…)'

def _mk_chunks(texts, src):
    'Wrap chunk strings as chonkie chunks, carrying real offsets into `src` where they can be found.'
    try: from chonkie.types import Chunk
    except Exception: Chunk = _Chunk
    out, pos = [], 0
    for t in texts:
        i = src.find(t[:60], pos) if t else -1
        st = i if i >= 0 else pos
        out.append(Chunk(text=t, start_index=st, end_index=st+len(t), token_count=0))
        pos = st + len(t)
    return out

class VerseChunker:
    'A chonkie-shaped chunker whose cuts land on verse boundaries.'
    def __init__(self, target:int=VERSE_TARGET, max_chars:int=VERSE_MAX, pack_cited:bool=False):
        self.target, self.max_chars, self.chunk_size = target, max_chars, max_chars
        self.pack_cited = pack_cited
    def chunk(self, text:str):
        return _mk_chunks(chunk_verses(text, self.target, self.max_chars, self.pack_cited), text or '')
    def __call__(self, text:str): return self.chunk(text)
    def __repr__(self):
        return f'{type(self).__name__}(target={self.target}, max_chars={self.max_chars}, pack_cited={self.pack_cited})'

class ProseChunker(VerseChunker):
    '`VerseChunker` tuned for Sanskrit prose — commentary, bhāṣya, the prose Upaniṣads.'
    def __init__(self, target:int=700, max_chars:int=1400, pack_cited:bool=True):
        super().__init__(target, max_chars, pack_cited)


# %% ../nbs/09_sanskrit.ipynb #c_translit
from fastcore.all import AttrDict, patch
from fastlite import Database

_IV = {'अ':'a','आ':'ā','इ':'i','ई':'ī','उ':'u','ऊ':'ū','ऋ':'ṛ','ॠ':'ṝ','ऌ':'ḷ','ॡ':'ḹ',
       'ए':'e','ऐ':'ai','ओ':'o','औ':'au','ऍ':'e','ऎ':'e','ऑ':'o','ऒ':'o'}
_MV = {'ा':'ā','ि':'i','ी':'ī','ु':'u','ू':'ū','ृ':'ṛ','ॄ':'ṝ','ॢ':'ḷ','ॣ':'ḹ',
       'े':'e','ै':'ai','ो':'o','ौ':'au','ॅ':'e','ॆ':'e','ॉ':'o','ॊ':'o'}
_CI = {'क':'k','ख':'kh','ग':'g','घ':'gh','ङ':'ṅ','च':'c','छ':'ch','ज':'j','झ':'jh','ञ':'ñ',
       'ट':'ṭ','ठ':'ṭh','ड':'ḍ','ढ':'ḍh','ण':'ṇ','त':'t','थ':'th','द':'d','ध':'dh','न':'n',
       'प':'p','फ':'ph','ब':'b','भ':'bh','म':'m','य':'y','र':'r','ल':'l','व':'v',
       'श':'ś','ष':'ṣ','स':'s','ह':'h','ळ':'ḻ','ऴ':'ḻ','ऱ':'r','ऩ':'n',
       'क़':'k','ख़':'kh','ग़':'g','ज़':'j','ड़':'ḍ','ढ़':'ḍh','फ़':'ph','य़':'y'}
_SI = {'ं':'ṃ','ः':'ḥ','ँ':'ṃ','ऽ':'','़':'','ॐ':'oṃ'}

def deva2iast(s:str) -> str:
    'Devanagari to IAST, keeping the vowel length that scansion depends on.'
    s = strip_vedic(s or '')
    out, i, n = [], 0, len(s)
    while i < n:
        ch = s[i]
        if ch in _CI:
            out.append(_CI[ch]); i += 1
            while i < n and s[i] == '़': i += 1
            if i < n and s[i] == _VIRAMA: i += 1; continue           # bare consonant, no vowel
            if i < n and s[i] in _MV: out.append(_MV[s[i]]); i += 1; continue
            out.append('a'); continue                                # the implicit vowel
        if ch in _IV: out.append(_IV[ch]); i += 1; continue
        if ch in _SI: out.append(_SI[ch]); i += 1; continue
        if ch in _MV: out.append(_MV[ch]); i += 1; continue           # orphan mātrā
        if ch in _DIGITS: out.append(' '); i += 1; continue           # a verse number is not a syllable
        if ch == _VIRAMA: i += 1; continue
        out.append(ch); i += 1
    return ''.join(out)


# %% ../nbs/09_sanskrit.ipynb #c_syll
_VOW2 = ('ai', 'au')
_VOW1 = frozenset('aāiīuūṛṝḷḹeo')
_LONG = frozenset(('ā','ī','ū','ṝ','ḹ','e','o','ai','au'))    # `e` and `o` are always long
_ASP  = ('kh','gh','ch','jh','ṭh','ḍh','th','dh','ph','bh')
_CON1 = frozenset('kgṅcjñṭḍṇtdnpbmyrlvśṣshḻ')
_CODA = frozenset('ṃṁḥ')
_WORDS = re.compile(r'[^\W\d_]+')

def _phones(text:str) -> list:
    "`[('V'|'C', unit)]` for a Sanskrit string, matched word by word so a vowel never fuses across a gap."
    s = deva2iast(text) if _DEVA.search(text or '') else (text or '')
    out = []
    for w in _WORDS.findall(s.lower()):
        i, n = 0, len(w)
        while i < n:
            if w[i:i+2] in _VOW2: out.append(('V', w[i:i+2])); i += 2; continue
            if w[i:i+2] in _ASP:  out.append(('C', w[i:i+2])); i += 2; continue
            # `ḷ` before a vowel is the retroflex lateral, not vocalic l
            if w[i] == 'ḷ' and i+1 < n and (w[i+1:i+3] in _VOW2 or w[i+1] in _VOW1):
                out.append(('C', w[i])); i += 1; continue
            if w[i] in _VOW1:     out.append(('V', w[i]));     i += 1; continue
            if w[i] in _CON1 or w[i] in _CODA: out.append(('C', w[i])); i += 1; continue
            i += 1                                          # not a phoneme; skip it
    return out

def syllables(text:str) -> L:
    'The syllables of a Sanskrit string as `(syllable, guru)` pairs.'
    ph = _phones(text)
    out, onset, coda_at = L(), '', -1
    for j, (k, u) in enumerate(ph):
        # a phone spent as the previous coda is not also this onset (`kaṃsa`, `duḥkha`)
        if k == 'C':
            if j != coda_at: onset += u
            continue
        run, closes = [], True
        for k2, u2 in ph[j+1:]:
            if k2 == 'V': closes = False; break
            run.append(u2)
        heavy = (u in _LONG or any(c in _CODA for c in run) or len(run) >= 2
                 or (closes and len(run) >= 1))
        # at the end of the text the whole run closes the syllable: `gam`, `varam`
        cod = ''.join(run) if closes else ''.join(c for c in run[:1] if c in _CODA)
        if cod: coda_at = j + 1
        out.append((onset + u + cod, heavy))
        onset = ''
    return out

def scan(text:str) -> str:
    'The guru/laghu skeleton of a string as `g`/`l` — what every metre is matched against.'
    return ''.join('g' if h else 'l' for _, h in syllables(text))


# %% ../nbs/09_sanskrit.ipynb #c_gana
GANAS = {'ya':'lgg', 'ma':'ggg', 'ta':'ggl', 'ra':'glg',
         'ja':'lgl', 'bha':'gll', 'na':'lll', 'sa':'llg',
         'ga':'g',   'la':'l'}
_OF_GANA = {v: k for k, v in GANAS.items() if len(v) == 3}

def ganas(pattern:str) -> L:
    'The gaṇa names of a `g`/`l` pattern, three at a time; a trailing one or two become `ga`/`la`.'
    s, out = pattern or '', L()
    cut = len(s) - len(s) % 3
    out += L(_OF_GANA[s[i:i+3]] for i in range(0, cut, 3))
    return out + L('ga' if c == 'g' else 'la' for c in s[cut:])

def gana_pattern(recipe:str) -> str:
    'The `g`/`l` pattern a gaṇa recipe spells out: `ta ta ja ga ga` -> `gglgglglgg`.'
    return ''.join(GANAS[x] for x in (recipe or '').split())

METERS = {
    'śālinī':           'ma ta ta ga ga',
    'indravajrā':       'ta ta ja ga ga',
    'upendravajrā':     'ja ta ja ga ga',
    'rathoddhatā':      'ra na ra la ga',
    'svāgatā':          'ra na bha ga ga',
    'vaṃśastha':        'ja ta ja ra',
    'indravaṃśā':       'ta ta ja ra',
    'drutavilambita':   'na bha bha ra',
    'toṭaka':           'sa sa sa sa',
    'bhujaṅgaprayāta':  'ya ya ya ya',
    'praharṣiṇī':       'ma na ja ra ga',
    'rucirā':           'ja bha sa ja ga',
    'vasantatilakā':    'ta bha ja ja ga ga',
    'mālinī':           'na na ma ya ya',
    'pṛthvī':           'ja sa ja sa ya la ga',
    'mandākrāntā':      'ma bha na ta ta ga ga',
    'śikhariṇī':        'ya ma na sa bha la ga',
    'hariṇī':           'na sa ma ra sa la ga',
    'śārdūlavikrīḍita': 'ma sa ja sa ta ta ga',
    'sragdharā':        'ma ra bha na ya ya ya',
}
VRTTA_EXTRA = """
    paṅkti:gllgg tanumadhyā:ggllgg vasumatī:gglllg śaśivadanā:llllgg haṃsamālā:llgglgg kumāralalitā:lglllgg
    madalekhā:gggllgg madhumatī:llllllg citrapadā:gllgllgg haṃsaruta:ggglllgg māṇavaka:gllggllg
    nārācaka:gglglglg pramāṇikā:lglglglg samānikā:glglglgl vidyunmālā:gggggggg bhujagaśiśubhṛtā:llllllggg
    halamukhī:glglllllg campakamālā:gllgggllgg manoramā:lllglglglg mattā:ggggllllgg mayūrasāriṇī:glglglglgg
    paṇava:gggllllggg upasthitā:ggllgllglg śuddhavirāṭ:gggllglglg bhadrikā:llllllglglg
    bhramaravilasitaṃ:ggggllllllg dodhaka:gllgllgllgg mauktikamālā:gllgllggllg sumukhī:llllgllgllg
    sāndrapada:gllggllllgg upasthita:lglllggglgg vātormī:ggggllgglgg vṛntā:llllllllggg śyenikā:glglglglglg
    candravartma:glglllgllllg jaladharamālā:ggggllllgggg jaloddhatagati:lglllglglllg
    kusumavicitrā:llllggllllgg lalitā:gglglllglglg mauktidadāma:lgllgllgllgl maṇimālā:ggllggggllgg
    mālatī:llllgllglglg navamālinī:llllglglllgg pañcacāmara:lglglglglglg pramitākṣarā:llglglllgllg
    pramuditavadanā:llllllglgglg priyaṃvadā:lllglllglglg puṭa:llllllggglgg sragviṇī:glgglgglgglg
    tāmarasa:llllgllgllgg ujjvalā:llllllgllglg vaiśvadevī:gggggglgglgg candrikā:llllllgglglgg
    kṣamā:llllllgglgglg mattamayūra:gggggllggllgg mañjubhāṣiṇī:llglglllglglg nandinī:llglglllgllgg
    alolā:gggllgggggllgg aparājitā:llllllglgllglg asambādhā:gggggllllllggg induvadanā:glllglllglllgg
    praharaṇakalikā:llllllgllllllg candralekhā:gggglgggglgglgg elā:llglgllllllllgg prabhadraka:llllglglllglglg
    śaśikalā:llllllllllllllg vāṇinī:llllglglllglglgg ṛṣabhagajavilasita:gllglglllllllllg
    narkuṭaka:llllglglllgllgllg vaṃśapatrapatitam:gllglglllgllllllg kusumitalatāvellitā:ggggglllllgglgglgg
    meghavisphurjita:lggggglllllgglgglgg suvadanā:gggglggllllllggglllg vṛtta:glglglglglglglglglgl
    madraka:gllglglllglglllglglllg aśvalalita:llllglglllglglllglglllg mattākrīḍa:ggggggggllllllllllllllg
    tanvī:gllggllllllggllgllllllgg krauñcapadā:gllgggllggllllllllllllllg apavāha:gggllllllllllllllllllllggg
    bhujaṅgavijṛmbhita:ggggggggllllllllllglgllglg
"""

_PAT = {k: gana_pattern(v) for k, v in METERS.items()}
_PAT.update({n: q for n, q in (e.split(':') for e in VRTTA_EXTRA.split()) if len(set(q)) > 1})
# upajāti is not a metre but a licence: any mix of these two across the four pādas of one verse.
_MIXED = {'upajāti': ('indravajrā', 'upendravajrā')}

def _pada_ok(w, pat) -> bool:
    'Does one pāda of weights fit a pattern? The last syllable of a pāda is anceps, always.'
    return len(w) == len(pat) and all(x == (c == 'g') for x, c in zip(w[:-1], pat[:-1]))

_PATHYA = 'lgg'
_VIPULA = {'lll':'na-vipulā', 'gll':'bha-vipulā', 'ggg':'ma-vipulā', 'glg':'ra-vipulā'}

def _anustubh(qs):
    'The śloka variant when four 8-syllable pādas scan as one, else None.'
    if not all(list(q[4:7]) == [False, True, False] for q in qs[1::2]): return None
    var = set()
    for q in qs[0::2]:
        k = ''.join('g' if x else 'l' for x in q[4:7])
        if k == _PATHYA: var.add('pathyā')
        elif k in _VIPULA: var.add(_VIPULA[k])
        else: return None
    return ' '.join(sorted(var))

_BARENUM = re.compile(r'(?:\|\||//|॥)\s*[\d०-९]+\s*(?:\|\||//|॥)')
_NOSCAN  = re.compile(r'^[ \t]*>[^\n]*'          # a gloss or translation line
                      r'|^[ \t]*#{1,6}[^\n]*'    # a heading
                      r'|\[[^\]\n]*\]', re.M)    # [h: ... :h], [page 3], the [57M] variant number

def metrical_text(s:str) -> str:
    'A verse with everything removed that is printed beside it but does not scan.'
    return _NOSCAN.sub(' ', _BARENUM.sub(' ', CITE_RE.sub(' ', s or '')))



# %% ../nbs/09_sanskrit.ipynb #c_matra
_G, _S = 'gana', 'syl'
_PURVA  = [(_G,4)]*7 + [(_S,0)]                     # 30 morae
_UTTARA = [(_G,4)]*5 + [(_G,1), (_G,4), (_S,0)]     # 27 morae — the 6th gaṇa shrinks to one laghu
_GITI8  = [(_G,4)]*8                                # 32 morae

MATRA_METERS = {
    'āryā':     (_PURVA,  _UTTARA),   # 30 + 27
    'gīti':     (_PURVA,  _PURVA),    # 30 + 30
    'upagīti':  (_UTTARA, _UTTARA),   # 27 + 27
    'udgīti':   (_UTTARA, _PURVA),    # 27 + 30 — the āryā halves the other way round
    'āryāgīti': (_GITI8,  _GITI8),    # 32 + 32
}
CATURMATRA = ('gg', 'gll', 'llg', 'lgl', 'llll')    # the five four-mora gaṇas; `lgl` is the ja-gaṇa

def matras(text:str) -> int:
    'The morae of a string: one for a laghu, two for a guru.'
    return sum(2 if h else 1 for _, h in syllables(text))

def _fit_half(w, slots):
    "Fill one half's ladder of gaṇas from a list of weights; the gaṇa patterns, or None."
    i, pats = 0, []
    for kind, want in slots:
        if kind == _S:                              # the closing guru: one syllable, whatever it is
            if i >= len(w): return None
            pats.append('g'); i += 1; continue
        s, j, pat = 0, i, ''
        while j < len(w) and s < want:
            s += 2 if w[j] else 1
            pat += 'g' if w[j] else 'l'
            j += 1
        if s != want: return None                   # overshot: the boundary is mid-syllable
        pats.append(pat); i = j
    return pats if i == len(w) else None

def _half_ok(pats, slots) -> bool:
    'The two gaṇa constraints that separate an āryā from any other 57 morae.'
    if any(pats[i] == 'lgl' for i in (0, 2, 4, 6) if i < len(pats)): return False
    six = pats[5] if len(pats) > 5 else ''
    return six == 'l' if slots[5][1] == 1 else six in ('lgl', 'llll')

def detect_matra_meter(text:str, weights:list=None):
    'The āryā-family metre of a verse — `AttrDict(name, halves, ganas, matras)` — or None.'
    w = weights if weights is not None else [h for _, h in syllables(metrical_text(text))]
    for k in range(4, len(w)):
        a, b = list(w[:k]), list(w[k:])
        if not b: continue
        a[-1] = b[-1] = True                        # each half closes on an anceps, read as guru
        for nm, (s1, s2) in MATRA_METERS.items():
            p1, p2 = _fit_half(a, s1), _fit_half(b, s2)
            if p1 and p2 and _half_ok(p1, s1) and _half_ok(p2, s2):
                m1 = sum(2 if h else 1 for h in a)
                m2 = sum(2 if h else 1 for h in b)
                return AttrDict(name=nm, halves=(m1, m2), matras=m1 + m2,
                                ganas=' '.join(p1) + ' | ' + ' '.join(p2))
    return None

def detect_meter(text:str):
    'The metre of one verse as `AttrDict(name, variant, syllables, per_pada, ganas, scan, matras)`, or None.'
    w = [h for _, h in syllables(metrical_text(text))]
    n = len(w)
    if n < 8: return None
    sc, mt = ''.join('g' if h else 'l' for h in w), sum(2 if h else 1 for h in w)
    if not n % 4:
        q  = n // 4
        qs = [w[i*q:(i+1)*q] for i in range(4)]
        sig = ' '.join(ganas(sc[:q][:-1] + 'g'))
        mk = lambda nm, var=None: AttrDict(name=nm, variant=var, syllables=n, per_pada=q,
                                           ganas=sig, scan=sc, matras=mt, halves=None)
        for nm, pat in _PAT.items():
            if len(pat) == q and all(_pada_ok(x, pat) for x in qs): return mk(nm)
        for nm, (a, b) in _MIXED.items():
            pa, pb = _PAT[a], _PAT[b]
            if len(pa) == q and all(_pada_ok(x, pa) or _pada_ok(x, pb) for x in qs): return mk(nm)
        if q == 8 and (v := _anustubh(qs)) is not None: return mk('anuṣṭubh', v)
    # only now the mora-counting family, so a varṇa metre is never relabelled by it
    if (a := detect_matra_meter(text, w)):
        return AttrDict(name=a.name, variant=None, syllables=n, per_pada=None,
                        ganas=a.ganas, scan=sc, matras=a.matras, halves=a.halves)
    if n % 4: return None
    return AttrDict(name=None, variant=None, syllables=n, per_pada=n//4,
                    ganas=' '.join(ganas(sc[:n//4][:-1] + 'g')), scan=sc, matras=mt, halves=None)



# %% ../nbs/09_sanskrit.ipynb #c_facet
PADA_RANGE = (4, 26)

def verse_units(text:str) -> L:
    'The individual verses inside one chunk — a chunk may pack several, and metre is per verse.'
    return L(t for _, _, t, _ in verse_spans(text)) or L([(text or '').strip()])

def verse_meta(text:str) -> dict:
    'The metrical facets of one chunk, as the dict that becomes its `metadata` JSON.'
    ms = L(verse_units(text)).map(detect_meter).filter(lambda m: m is not None)
    if not ms: return {}
    out, named = {}, ms.filter(lambda m: m.name)
    if named:
        out['meter'] = ' '.join(dict.fromkeys(named.attrgot('name')))
        if (vs := [v for v in dict.fromkeys(named.attrgot('variant')) if v]): out['variant'] = ' '.join(vs)
    ok = lambda m: bool(m.name) or PADA_RANGE[0] <= (m.per_pada or 0) <= PADA_RANGE[1]
    var, mat = ms.filter(lambda m: m.per_pada and ok(m)), ms.filter(lambda m: m.halves)
    if (gs := dict.fromkeys(m.ganas.replace(' ', '_') for m in var if m.ganas)): out['gana'] = ' '.join(gs)
    if (ps := dict.fromkeys(str(m.per_pada) for m in var)): out['pada'] = ' '.join(ps)
    if (hs := dict.fromkeys('+'.join(map(str, m.halves)) for m in mat)): out['matra'] = ' '.join(hs)
    return out



# %% ../nbs/09_sanskrit.ipynb #c_lemma
def lemma_facets(text:str,          # chunk text
                 nlp,               # a `vidyut_pipe()` (or any spaCy-shaped pipeline)
                 max_terms:int=96   # cap, so one chunk's metadata cannot outgrow its content
                 ) -> dict:
    "`{'lemma': 'gam vac ...'}` for a chunk — the dictionary forms behind its inflected words."
    if not (nlp and (text or '').strip()): return {}
    try: doc = nlp(metrical_text(text))
    except Exception: return {}
    out = {}
    for t in doc:
        lem, surf = (getattr(t, 'lemma_', '') or '').strip(), (t.text or '').strip()
        if not lem or getattr(t, 'is_punct', False) or getattr(t, 'is_digit', False): continue
        if fold_token(lem) == fold_token(surf): continue     # nothing the surface index lacks
        if len(lem) < 2: continue
        out[lem] = None
        if len(out) >= max_terms: break
    return {'lemma': ' '.join(out)} if out else {}

def sanskrit_meta(nlp=None, mw:dict=None):
    'The `Profile.meta` callable: metre always, lemmas and glosses when their sources are supplied.'
    if nlp is None: return verse_meta
    if mw is None:
        def meta(text:str) -> dict: return {**verse_meta(text), **lemma_facets(text, nlp)}
    else:
        def meta(text:str) -> dict:
            return {**verse_meta(text), **lemma_facets(text, nlp), **gloss_facets(text, nlp, mw)}
    return meta

@patch
def by_lemma(self:Database,
             lemma:str,           # a dictionary form, e.g. `gam`
             store:str='store',
             prefix:str=None,
             columns:list=None,
             limit:int=50) -> list:
    'Chunks whose verses inflect `lemma`. Needs an index built with `register_profiles(nlp=...)`.'
    cols = list(dict.fromkeys((columns or ['content']) + ['metadata', 'node_id', 'doc_id', 'page']))
    return self.t[ifnone(prefix, '') + store](
        select=', '.join(cols), where='metadata like :sa_l',
        where_args={'sa_l': f'%"lemma": "%{lemma}%'}, limit=limit)

@patch
def by_meter(self:Database,
             meter:str=None,      # metre name, e.g. `mandākrāntā`
             gana:str=None,       # gaṇa signature, `ma bha na ta ta ga ga` or `ma_bha_na_...`
             store:str='store',
             prefix:str=None,
             columns:list=None,
             limit:int=50) -> list:
    'Chunks whose verses are in a metre, or share a gaṇa signature. A filter, not a ranking.'
    wh, wa = [], {}
    if meter: wh.append('metadata like :sa_m'); wa['sa_m'] = f'%"meter": "%{meter}%'
    if gana:  wh.append('metadata like :sa_g'); wa['sa_g'] = f'%{gana.strip().replace(" ", "_")}%'
    if not wh: return []
    cols = list(dict.fromkeys((columns or ['content']) + ['metadata', 'node_id', 'doc_id', 'page']))
    return self.t[ifnone(prefix, '') + store](select=', '.join(cols), where=' AND '.join(wh),
                                              where_args=wa, limit=limit)

# %% ../nbs/09_sanskrit.ipynb #c17
_GRETIL_END = re.compile(r'COPYRIGHT AND TERMS OF USAGE AS FOR SOURCE FILE\.|'
                         r'For further information see:\s*\n\s*http\S+', re.I)

def _detag(t:str) -> str:
    import html
    t = re.sub(r'<(script|style)[^>]*>.*?</\1>', ' ', t, flags=re.S | re.I)
    return html.unescape(re.sub(r'<[^>]+>', '', t))

def gretil_parse(src) -> tuple:
    'GRETIL plain-text (`*_u.htm`) to `(pages, meta)`.'
    txt = _detag(Path(src).read_text(encoding='utf-8', errors='replace') if _isfile(src) else str(src))
    head, body = '', txt
    if (m := _GRETIL_END.search(txt)):
        head, body = txt[:m.end()], txt[m.end():]
        # the diacritics table sits *after* the banner; drop lines up to the last of its entries
        if (d := list(re.finditer(r'^\s*\w[\w\s]*\s{2,}[^\x00-\x7f]\s*$', body, re.M))):
            head, body = head + body[:d[-1].end()], body[d[-1].end():]
    body = re.sub(r'\n{3,}', '\n\n', body).strip()
    blocks = [b for b in re.split(r'\n\s*\n', body) if b.strip()]
    while blocks and not _has_sanskrit(blocks[0]):
        head += '\n\n' + blocks.pop(0)
    body = '\n\n'.join(blocks)
    spans = verse_spans(body)
    pages = [(i, s) for i, (_, _, s, _) in enumerate(spans)] if len(spans) > 1 else list(enumerate(blocks))
    ttl = _first_line(head) or (Path(src).stem if _isfile(src) else 'gretil')
    return pages or [(0, body)], dict(fmt='gretil', title=ttl, header=head.strip()[:2000])

def tei_parse(src) -> tuple:
    'GRETIL `corpustei` / SARIT TEI to `(pages, meta)`.'
    from xml.etree import ElementTree as ET
    raw = Path(src).read_text(encoding='utf-8', errors='replace') if _isfile(src) else str(src)
    root = ET.fromstring(raw)
    ns = {'t': 'http://www.tei-c.org/ns/1.0'}
    def tag(e): return e.tag.split('}')[-1]
    def txt(e):
        parts = []
        for n in e.iter():
            if tag(n) in ('note', 'app', 'rdg', 'lem'): continue
            if n.text: parts.append(n.text)
            if n is not e and n.tail: parts.append(n.tail)
        return re.sub(r'\s+', ' ', ' '.join(parts)).strip()
    body = root.find('.//t:text/t:body', ns) or root.find('.//text/body') or root
    pages, path = [], []
    def walk(el, depth=0):
        for ch in el:
            t = tag(ch)
            if t == 'div':
                nm = ch.get('type') or 'div'; n = ch.get('n') or ''
                path.append(f"{nm} {n}".strip())
                pages.append((len(pages), f"{'#' * min(depth + 2, 6)} {path[-1]}"))
                walk(ch, depth + 1); path.pop()
            elif t == 'lg':
                cid = ch.get('{http://www.w3.org/XML/1998/namespace}id') or ch.get('id') or ''
                # `<l>` often already carries a trailing `//`; appending the id beside it would
                # leave `// || Manu_1.2 ||` and two boundary markers where there is one boundary.
                s = re.sub(r'\s*(?://|\|\|)\s*$', '', txt(ch))
                if s: pages.append((len(pages), f"{s} || {cid} ||" if cid else s))
            elif t in ('p', 'ab'):
                if (s := txt(ch)): pages.append((len(pages), s))
            elif t in ('note', 'app'): continue
            else: walk(ch, depth)
    walk(body)
    ttl = (root.findtext('.//t:titleStmt/t:title', default='', namespaces=ns)
           or root.findtext('.//titleStmt/title', default='') or '').strip()
    return _merge_pages(pages), dict(fmt='tei', title=ttl or (Path(src).stem if _isfile(src) else 'tei'))

def vr_xml_parse(src) -> tuple:
    'vedicreader `<lyrics>` XML to `(pages, meta)`.'
    from xml.etree import ElementTree as ET
    raw = Path(src).read_text(encoding='utf-8', errors='replace') if _isfile(src) else str(src)
    root = ET.fromstring(raw)
    pages, ttl = [], ''
    for so, s in enumerate(root.iter('section')):
        nm = s.get('name') or f'section {so}'
        lines = [l for l in s.iterfind('line')
                 if (l.text or '').strip() and (l.get('exclude_from_display') or 'false').lower() != 'true']
        if nm == 'title' and lines and not ttl: ttl = (lines[0].text or '').strip()
        if not lines: continue
        pages.append((len(pages), f'## {nm}'))
        buf = []
        for l in lines:
            buf.append((l.text or '').strip())
            if (g := (l.get('meaning') or l.get('caption') or '').strip()): buf.append('> ' + g)
        body = '\n'.join(buf)
        if not re.search(r'[।॥]\s*$', body.split('\n>')[0]): body += '\n॥'
        if (sm := (s.get('meaning') or '').strip()): body += '\n> ' + sm
        pages.append((len(pages), body))
    cat = (root.findtext('category') or '').strip()
    tags = (root.findtext('tags') or '').strip()
    return _merge_pages(pages), dict(fmt='vedicreader', title=ttl, category=cat, tags=tags)

def dcs_parse(src) -> tuple:
    'DCS / ambuda analysed text to `(pages, meta)`.'
    raw = Path(src).read_text(encoding='utf-8', errors='replace') if _isfile(src) else str(src)
    pages, cur, lem, cid = [], [], [], None
    def flush():
        if not cur: return
        v = ' '.join(cur)
        # lemmas on the verse's own page, so they travel with it rather than opening the next unit
        pages.append((len(pages), (f"{v} || {cid} ||" if cid else v)
                      + ('\n> lemmas: ' + ' '.join(dict.fromkeys(lem)) if lem else '')))
    for ln in raw.splitlines():
        if ln.startswith('#'):
            if (m := re.search(r'id\s*=\s*(\S+)', ln)): flush(); cur, lem, cid = [], [], m.group(1)
            continue
        if not ln.strip():
            flush(); cur, lem, cid = [], [], None
            continue
        f = ln.split('\t')
        if f and f[0].strip(): cur.append(f[0].strip())
        if len(f) > 1 and f[1].strip(): lem.append(f[1].strip())
    flush()
    return _merge_pages(pages), dict(fmt='dcs', title=(Path(src).stem if _isfile(src) else 'dcs'))

def _isfile(x):
    try: return Path(x).is_file()
    except (OSError, ValueError): return False

def _first_line(t):
    for l in (t or '').splitlines():
        if (s := l.strip()) and not s.startswith('http') and len(s) > 3: return s[:120]
    return ''

def _merge_pages(pages, per:int=1):
    'One page per structural unit is fine for the tree; collapse to text blocks for build_tree.'
    return [(i, t) for i, t in pages if (t or '').strip()]

_IAST_DIAC = re.compile('[āīūṛṝḷḹṅñṭḍṇśṣṃḥĀĪŪṚṄÑṬḌṆŚṢṂḤ]')

def _has_sanskrit(block:str) -> bool:
    'Whether a block carries any Sanskrit signal — script, diacritic, daṇḍa or citation.'
    return bool(_DEVA.search(block) or _IAST_DIAC.search(block)
                or DANDA in block or DDANDA in block or CITE_RE.search(block))

_SANSKRIT_EXTS = '.xml,.tei,.htm,.html,.conllu,.txt'

_DANDA_EOL = re.compile(r'(?:[।॥]|//|/|\|\||\|)[ \t]*$', re.M)

def is_sanskrit(text:str, thresh:float=0.15) -> bool:
    'Whether `text` reads as Sanskrit — by script, by transliteration, or by structure.'
    s = (text or '')[:20000]
    if not s.strip(): return False
    if len(_DEVA.findall(s)) / max(len(s), 1) > thresh: return True
    lines = max(len(s.splitlines()), 1)
    strict = len(CITE_RE.findall(s)) + s.count(DDANDA)
    if strict >= 3 and strict / lines > 0.05: return True
    loose = strict + len(_DANDA_EOL.findall(s))
    return (len(_IAST_DIAC.findall(s)) / max(len(s), 1) > 0.01) and loose >= 3 and loose / lines > 0.02

def sanskrit_parse(src) -> tuple:
    'Parse any supported Sanskrit source to `(pages, meta)`, picking the reader by shape.'
    p = Path(src) if _isfile(src) else None
    raw = p.read_text(encoding='utf-8', errors='replace')[:4000] if p else str(src)[:4000]
    sfx = p.suffix.lower() if p else ''
    if sfx in ('.conllu',) or re.search(r'^#\s*id\s*=', raw, re.M): return dcs_parse(src)
    if '<lyrics' in raw: return vr_xml_parse(src)
    if 'tei-c.org' in raw or '<TEI' in raw or '<teiHeader' in raw: return tei_parse(src)
    if sfx in ('.htm', '.html') or 'GRETIL' in raw: return gretil_parse(src)
    if sfx == '.xml':
        return vr_xml_parse(src) if '<lyrics' in raw else tei_parse(src)
    return gretil_parse(src)


# %% ../nbs/09_sanskrit.ipynb #c20
def _sniff(text:str) -> bool:
    'Whether a shared extension (`.xml`, `.txt`, `.htm`) holds Sanskrit this module can read.'
    raw = (text or '')[:60000]
    if '<lyrics' in raw[:4000]: return True
    # TEI states its language, which beats sniffing: a 16 KB edition can be almost entirely header,
    # and TEI keeps the citation in an `xml:id` attribute where no content sniff will find it.
    if ('tei-c.org' in raw or '<teiHeader' in raw) and re.search(r'xml:lang=["\'](sa|pi|pra)\b', raw): return True
    t = _detag(raw)
    if re.search(r'^#\s*id\s*=', t, re.M): return True
    return is_sanskrit(t)

def register_profiles(nlp=None, mw:dict=None):
    'Register the Sanskrit profiles. Called on import; safe to call again.'
    from litesearch.data import Profile, register_profile
    meta = sanskrit_meta(nlp, mw)
    register_profile(Profile(name='sanskrit_verse', exts='.xml,.tei,.htm,.html,.conllu,.txt',
                             parse=sanskrit_parse, chunker=VerseChunker, mode='verse',
                             detect=_sniff, kind='sanskrit', meta=meta))
    register_profile(Profile(name='sanskrit_prose', exts='', parse=sanskrit_parse,
                             chunker=ProseChunker, mode='verse',
                             detect=lambda _t: False, kind='sanskrit', meta=meta))

register_profiles()


# %% ../nbs/09_sanskrit.ipynb #vidyut_mw
_VIDYUT_URL_NOTE = 'https://github.com/ambuda-org/vidyut'   # MIT
MW_URL = 'https://raw.githubusercontent.com/sanskrit-lexicon/csl-orig/master/v02/mw/mw.txt'

def sanskrit_home(name:str=None) -> Path:
    'Where the downloaded Sanskrit data lives: `$LITESEARCH_HOME`, else the XDG cache.'
    import os
    d = Path(os.environ.get('LITESEARCH_HOME')
             or Path(os.environ.get('XDG_CACHE_HOME', Path.home()/'.cache'))/'litesearch')/'sanskrit'
    d.mkdir(parents=True, exist_ok=True)
    return d/name if name else d

def vidyut_data(path=None, force:bool=False) -> Path:
    "vidyut's linguistic data, downloaded on first use (~81 MB) and cached thereafter."
    d = Path(path) if path else sanskrit_home('vidyut')
    if force or not (d/'kosha').exists():
        try: import vidyut
        except ImportError: raise ImportError('lemmas and glosses need vidyut: pip install vidyut') from None
        d.mkdir(parents=True, exist_ok=True)
        vidyut.download_data(str(d))
    return d

def to_slp1(text:str) -> str:
    'Any supported script to SLP1, which is what the kosha is keyed on. Needs no downloaded data.'
    from vidyut.lipi import transliterate, Scheme
    return transliterate(text, Scheme.Devanagari if _DEVA.search(text or '') else Scheme.Iast, Scheme.Slp1)

def from_slp1(text:str, iast:bool=True) -> str:
    'SLP1 back to something readable — IAST by default, Devanagari otherwise.'
    from vidyut.lipi import transliterate, Scheme
    return transliterate(text or '', Scheme.Slp1, Scheme.Iast if iast else Scheme.Devanagari)

class _VTok:
    'A spaCy-shaped token, so `lemma_facets` needs no knowledge of where the lemma came from.'
    is_punct = is_digit = False
    def __init__(self, text, lemma, slp=''): self.text, self.lemma_, self.lemma_slp = text, lemma, slp
    def __repr__(self): return f'_VTok({self.text!r}→{self.lemma_!r})'

_TOKEN = re.compile(r'[^\s।॥|/,;:()\[\]]+')

def _pausa_keys(slp:str) -> L:
    'The forms to try in the kosha for one written word, best first.'
    ks = L(slp)
    if slp.endswith('H'): ks += [slp[:-1]+'s', slp[:-1]+'r']
    if slp.endswith('M'): ks.append(slp[:-1]+'m')
    return ks

def _splitter(path=None):
    'vidyut\'s sandhi rule table, as a splitter. Cached by the caller.'
    from vidyut.sandhi import Splitter
    return Splitter.from_csv(str(vidyut_data(path)/'sandhi'/'rules.csv'))

def _cover(w:str, sp, known, depth:int=0, max_depth:int=3, min_piece:int=2) -> tuple:
    'Split an SLP1 string into pieces the kosha recognises, or `()` if it cannot be covered.'
    if known(w): return (w,)
    # SLP1 is an ASCII scheme, and vidyut's splitter indexes by *byte*. A character `to_slp1` could
    # not map survives into the string, and `split_at` then panics from Rust — not an exception
    # Python can catch. Real editions carry them: a nukta in `पितṛ़न` (Gītā 1.34) is enough.
    if not w.isascii(): return ()
    if depth >= max_depth or len(w) < 2*min_piece: return ()
    for i in range(len(w)-min_piece, min_piece-1, -1):
        for s in sp.split_at(w, i):
            if not s.is_valid or len(s.first) < min_piece or not known(s.first): continue
            if (rest := _cover(s.second, sp, known, depth+1, max_depth, min_piece)): return (s.first,)+rest
    return ()

def vidyut_pipe(path=None, split:bool=True):
    "A spaCy-shaped lemmatiser backed by vidyut's kosha — the deterministic answer to inflection."
    from vidyut.kosha import Kosha
    ko = Kosha(str(vidyut_data(path)/'kosha'))
    sp = _splitter(path) if split else None
    def lem(k):
        try: return dict.fromkeys(e.lemma for e in ko.get(k) if e.lemma)
        except Exception: return {}
    known = lambda s: bool(s) and any(ko.get(k) for k in _pausa_keys(s))
    def pipe(text:str):
        out = []
        for w in _TOKEN.findall(text or ''):
            w = w.strip("'’॒॑")
            if not w or not (_DEVA.search(w) or _IAST_DIAC.search(w) or w.isalpha()): continue
            slps, slp = (), to_slp1(w)
            for k in _pausa_keys(slp):
                if (slps := lem(k)): break
            # nothing in the lexicon: the token is probably two words fused by sandhi
            if not slps and sp is not None and len(slp) >= 5:
                for piece in _cover(slp, sp, known):
                    for k in _pausa_keys(piece):
                        if (pl := lem(k)): slps = {**slps, **pl}; break
            out += [_VTok(w, from_slp1(s), s) for s in slps]
        return out
    return pipe

def sanskrit_terms(path=None,        # vidyut data dir; None -> `sanskrit_home()`
                   topk:int=12,      # most frequent nominals kept per chunk
                   min_len:int=3,    # skip particles and one-syllable words
                   split:bool=True   # undo sandhi on tokens the kosha does not know
                   ):
    'A `terms_fn` for `build_graph`: the nominal words of a Sanskrit chunk, via the kosha.'
    from vidyut.kosha import Kosha, PadaEntry
    ko = Kosha(str(vidyut_data(path)/'kosha'))
    sp = _splitter(path) if split else None
    known = lambda s: bool(s) and any(ko.get(k) for k in _pausa_keys(s))
    def entries(slp):
        for k in _pausa_keys(slp):
            if (es := ko.get(k)): return es
        return []
    def nominal(w) -> bool:
        es = entries(to_slp1(w))
        if not es and sp is not None and len(w) >= 4:
            # a fused token counts as nominal only if every piece of it is
            parts = _cover(to_slp1(w), sp, known)
            if not parts: return False
            return all(nominal_slp(p) for p in parts)
        return bool(es) and not any(isinstance(e, PadaEntry.Tinanta) for e in es)
    def nominal_slp(slp) -> bool:
        es = entries(slp)
        return bool(es) and not any(isinstance(e, PadaEntry.Tinanta) for e in es)
    def terms(text:str, topk:int=topk) -> L:
        seen = {}
        for w in _TOKEN.findall(metrical_text(text) or ''):
            w = w.strip("'’॒॑")
            if len(w) < min_len or not (_DEVA.search(w) or _IAST_DIAC.search(w) or w.isalpha()): continue
            if w in seen: seen[w] += 1; continue
            if nominal(w): seen[w] = 1
        return L(sorted(seen, key=lambda k: -seen[k])[:topk])
    return terms

_MW_DROP = re.compile(r'<(s|s1|ls|lex|ab|hom|info|srs|etym|gk|lang|bot|pb|div)[^>]*>.*?</\1>'
                      r'|<(info|srs|pb|div|s1)[^>]*/?>', re.S)
_MW_TAG, _MW_K1 = re.compile(r'<[^>]+>'), re.compile(r'<k1>([^<]*)')
_MW_WORD = re.compile(r'[A-Za-z][A-Za-z-]{2,}')

def _mw_clean(body:str) -> str:
    t = body.split('¦', 1)[-1] if '¦' in body else body
    t = _MW_TAG.sub(' ', _MW_DROP.sub(' ', t)).replace('&c.', '').replace('√', ' ')
    t = re.sub(r'\([^)]*\)', ' ', t)                 # parentheticals are citations or grammar
    t = re.sub(r'[\[\]‘’"]', ' ', t)
    # A root entry opens with its conjugation table, which is all `<s>`/`<ab>` and strips to bare
    # punctuation — `gam` came out as `1. ; 2. ( ; 3. ,` before this line.
    if not _MW_WORD.search(t.split(',')[0] or ''): t = re.sub(r'(?:\s*[\d.,;:—-]+\s*)+', ' ', t)
    t = re.sub(r'\s+', ' ', t).strip(' ,;.:—-')
    if (m := re.search(r'[A-Za-z]', t)): t = t[m.start():]
    return re.sub(r'\s+', ' ', t).strip(' ,;.:—-')

def _mw_ok(g:str) -> bool:
    'Real English, not the debris a conjugation table leaves behind.'
    return len(_MW_WORD.findall(g)) >= 2 and len(re.sub(r'[^A-Za-z]', '', g))/max(len(g), 1) > 0.55

def _clip(s:str, n:int) -> str:
    'Truncate on a word boundary — a half word like `ema` is an index term that matches nothing.'
    return s if len(s) <= n else s[:n].rsplit(' ', 1)[0].rstrip(' ,;')

def mw_lexicon(path=None, force:bool=False, maxlen:int=110) -> dict:
    'Monier-Williams as `{SLP1 headword: short English gloss}`, downloaded and reduced on first use.'
    tsv = (Path(path) if path else sanskrit_home())/'mw.tsv'
    if force or not tsv.exists():
        import urllib.request
        raw = tsv.with_suffix('.src')
        if force or not raw.exists():
            req = urllib.request.Request(MW_URL, headers={'User-Agent': 'litesearch'})
            with urllib.request.urlopen(req, timeout=300) as r, open(raw, 'wb') as f:
                while (b := r.read(1 << 20)): f.write(b)
        out, k, buf = {}, None, []
        with open(raw, encoding='utf-8', errors='replace') as f:
            for ln in f:
                if ln.startswith('<L>'): m = _MW_K1.search(ln); k, buf = (m.group(1) if m else None), []
                elif ln.startswith('<LEND>'):
                    if k and buf and _mw_ok(g := _mw_clean(' '.join(buf))):
                        prev = out.get(k)
                        out[k] = _clip(g, maxlen) if not prev else (
                            _clip(prev+'; '+g, maxlen) if len(prev) < 60 else prev)
                    k, buf = None, []
                elif k is not None: buf.append(ln.rstrip('\n'))
        tsv.write_text(''.join(f'{a}\t{b}\n' for a, b in out.items()), encoding='utf-8')
        raw.unlink(missing_ok=True)
    return dict(ln.split('\t', 1) for ln in tsv.read_text(encoding='utf-8').splitlines() if '\t' in ln)

GLOSS_STOP = frozenset('''the and for with that this from any all not are was has had its his her
their they which who whom what when where how such into out off over under also more most other
some one two being been have does did must may might can could would should shall will upon than
then them these those there here about above after before between during through against among
substitution used said say saying called esp cf viz ibid etc set out come towards'''.split())

def gloss_facets(text:str,          # chunk text
                 nlp,               # a `vidyut_pipe()`; tokens must carry `.lemma_slp`
                 mw:dict,           # a `mw_lexicon()`
                 max_terms:int=24   # cap, so the gloss cannot outgrow the verse
                 ) -> dict:
    "`{'gloss': 'law duty; land soil; ...'}` — the English behind a chunk's Sanskrit words."
    if not (nlp and mw and (text or '').strip()): return {}
    out = {}
    for t in nlp(metrical_text(text)):
        if (g := mw.get(getattr(t, 'lemma_slp', ''))):
            for w in g.replace(';', ' ').replace(',', ' ').split():
                w = w.lower()
                if len(w) > 2 and w.isalpha() and w not in GLOSS_STOP: out[w] = None
        if len(out) >= max_terms: break
    return {'gloss': ' '.join(list(out)[:max_terms])} if out else {}

