# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_tree.ipynb.

# %% auto #0
__all__ = ['MIN_CHUNK', 'DOC_EXTS', 'TreeNode', 'summarize_extractive', 'detect_mode', 'build_tree', 'heading_path', 'doc_id',
           'adaptive_weights', 'merge_spans']

# %% ../nbs/06_tree.ipynb #bfd0799d
from fastcore.all import Path, patch, first, L, AttrDict, ifnone
from fastlite import Database
from apswutils.db import Table
from apswutils.utils import hash_record
from dataclasses import dataclass, field
import re
import numpy as np

from .core import _in, _rid, rrf_merge, process_content
from .data import chunk_markdown

# %% ../nbs/06_tree.ipynb #e1da63fc
_md_head  = re.compile(r'^(#{1,6})\s+(.+?)\s*#*\s*$')
_chapter  = re.compile(r'^\s{0,6}(?:CHAPTER|Chapter|CANTO|Canto|PART|Part|LESSON|Lesson|ADHYAYA|Adhyaya|'
                       r'BOOK|Book|SECTION|Section)\s+([IVXLCDM]+|\d+)\b[\s.:—-]*(.{0,80})$')
_ws       = re.compile(r'\s+')

@dataclass
class TreeNode:
    'One section of a document. `seq` is its index in the flat list; `parent` is another `seq`.'
    seq:int
    title:str
    level:int
    parent:int|None = None
    page_start:int = 0
    page_end:int = 0
    segments:list = field(default_factory=list)   # [(page, text), ...]
    children:list = field(default_factory=list)   # [seq, ...]
    summary:str = ''
    def text(self): return '\n\n'.join(s for _, s in self.segments if s.strip())

def summarize_extractive(text:str, n:int=300) -> str:
    'First `n` clean characters. Cheap, deterministic, and the seam an LLM slots into via `summarize=`.'
    t = _ws.sub(' ', text).strip()
    return t[:n] + ('…' if len(t) > n else '')

def _clean_title(t:str, max_len:int=100): return _ws.sub(' ', t).strip(' #*_')[:max_len].strip()

def detect_mode(pages) -> str:
    '''Which structural signal this document carries: `markdown`, `chapter` or `window`.

    The markdown threshold scales with length so that three stray `#` lines in a 600-page scan do
    not outvote 200 real chapter headings.'''
    md = ch = 0
    for _, txt in pages:
        for ln in (txt or '').splitlines():
            if _md_head.match(ln): md += 1
            elif _chapter.match(ln): ch += 1
    # short docs are usually born-markdown (a README, a note); long ones are usually scans where a
    # stray `#` is punctuation, so the bar rises with length instead of being one fixed number
    thresh = 2 if len(pages) <= 3 else max(3, len(pages) // 25)
    if md >= thresh: return 'markdown'
    return 'chapter' if ch >= 3 else 'window' 

# %% ../nbs/06_tree.ipynb #ac650c0e
def build_tree(pages,                  # [(page_no, text)] — markdown or plain text
               title:str='Document',   # title of the root node
               summarize=None,         # callable(text)->str for node summaries (LLM goes here)
               window:int=8,           # pages per node in `window` mode
               min_level:int=1,        # floor for heading depth
               max_levels:int=4        # deepest node level kept
) -> list:
    'A flat list of `TreeNode` for a document (index = seq, root = 0).'
    pages = [(p, t or '') for p, t in pages]
    summarize = summarize or summarize_extractive
    mode, nodes = detect_mode(pages), []
    def fresh(t, lvl, parent, page):
        nd = TreeNode(seq=len(nodes), title=_clean_title(t) or f'Section {len(nodes)}',
                      level=lvl, parent=parent, page_start=page, page_end=page)
        nodes.append(nd)
        if parent is not None: nodes[parent].children.append(nd.seq)
        return nd
    root = fresh(title, 0, None, pages[0][0] if pages else 0)
    stack, cur, buf, cur_page = [root], root, [], root.page_start
    def open_node(t, lvl, page):
        nonlocal cur
        lvl = min(lvl, max_levels)
        while len(stack) > lvl: stack.pop()
        cur = fresh(t, lvl, stack[-1].seq, page)
        stack.append(cur)
    def flush(page):
        if (txt := '\n'.join(buf).strip()): cur.segments.append((page, txt))
        cur.page_end = max(cur.page_end, page)
        buf.clear()

    if mode == 'window':
        for i in range(0, len(pages), window):
            grp = pages[i:i+window]
            lead = next((l.strip() for _, t in grp for l in t.splitlines() if l.strip()), '')
            open_node(f'Pages {grp[0][0]+1}–{grp[-1][0]+1}: {lead[:60]}', 1, grp[0][0])
            for p, t in grp:
                if t.strip(): cur.segments.append((p, t.strip()))
                cur.page_end = p
        cur = root
    else:
        for p, txt in pages:
            for ln in txt.splitlines():
                m = _md_head.match(ln) if mode == 'markdown' else _chapter.match(ln)
                # a lowercase first character usually means a `#` that was punctuation, not a heading
                if m and (mode == 'chapter' or (len(t := _clean_title(m.group(2))) >= 2 and not t[0].islower())):
                    flush(cur_page)
                    open_node(ln.strip() if mode == 'chapter' else m.group(2),
                              1 if mode == 'chapter' else max(min_level, len(m.group(1))), p)
                    cur_page = p
                    continue
                buf.append(ln)
            flush(p)
            cur_page = p
    flush(cur_page)
    for nd in nodes:
        base = nd.text() or ' / '.join(nodes[c].title for c in nd.children[:8])
        nd.summary = summarize(base) if base else ''
    root.page_end = max((n.page_end for n in nodes), default=root.page_end)
    return nodes

def heading_path(tree,              # the node list from build_tree
                 nd,                # the TreeNode to describe
                 title:str,         # document title
                 sep:str=' › ',
                 max_len:int=200) -> str:
    '''`Doc › Part › Chapter` for one node.

    Embedded with the chunk and indexed for FTS, this is what stops a chunk reading as an
    out-of-context fragment: "the effects are severe" means nothing until you know which chapter
    said it.'''
    parts, cur = [], nd
    while cur is not None:
        if cur.level > 0: parts.append(cur.title)
        cur = tree[cur.parent] if cur.parent is not None else None
    return sep.join([title] + parts[::-1])[:max_len]

# %% ../nbs/06_tree.ipynb #4b0349a2
def doc_id(source, title='') -> str:
    'Content-addressed document id — re-adding the same source is a no-op, not a duplicate.'
    return hash_record({'k': f'{source}|{title}'})[:16]

@patch
def get_tree(self:Database,
             store:str='store',   # chunk store the tree is built over
             prefix:str=None,     # table prefix (default: '' for 'store', else '<store>_')
             ann:bool=True,       # register an ANN index on the chunk store
             **kw                 # extra typed columns for the chunk store
) -> AttrDict:
    'Create the docs/nodes tables and a node-aware chunk store. Idempotent; returns the tables.'
    p = prefix if prefix is not None else ('' if store == 'store' else f'{store}_')
    dt, nt = f'{p}docs', f'{p}nodes'
    st = self.get_store(store, hash=True, ann=ann, doc_id=str, node_id=str, page=int, heading=str, **kw)
    self.t[dt].create(id=str, title=str, source=str, kind=str, pages=int, meta=str, added_at=float,
                      pk='id', if_not_exists=True, defaults=dict(added_at='CURRENT_TIMESTAMP'))
    self.t[nt].create(id=str, doc_id=str, parent_id=str, level=int, seq=int, title=str,
                      page_start=int, page_end=int, summary=str, nchunks=int, pk='id', if_not_exists=True)
    for t, c in ((nt,'doc_id'), (nt,'parent_id'), (store,'doc_id'), (store,'node_id')):
        self.t[t].create_index([c], if_not_exists=True)
    return AttrDict(docs=self.t[dt], nodes=self.t[nt], store=st, prefix=p)

# %% ../nbs/06_tree.ipynb #1ec67c50
MIN_CHUNK = 40

def _node_chunks(tree, title, did, chunker=None, min_chunk=MIN_CHUNK):
    """Chunk every node segment, tagging each chunk with its node, page and heading path.

    A chunk under `min_chunk` is *merged into its predecessor*, never dropped. Dropping is the
    tempting reading of a minimum size and it is wrong here: `read()` assembles a section out of
    its chunks, so a discarded chunk is text that has silently left the corpus."""
    out = L()
    for nd in tree:
        head, nid = heading_path(tree, nd, title), f'{did}#{nd.seq}'
        for page, seg in nd.segments:
            prev = None
            for c in chunk_markdown(seg, chunker):
                if not (c or '').strip(): continue
                if prev is not None and len(c.strip()) < min_chunk:
                    prev['content'] = f"{prev['content']}\n\n{c}"
                    continue
                prev = dict(content=c, doc_id=did, node_id=nid, page=page, heading=head)
                out.append(prev)
    return out

@patch
def add_doc(self:Database,
            pages,                  # [(page_no, text)] — or a single string
            title:str,              # document title
            source:str=None,        # path or url (defaults to the title)
            kind:str='text',        # 'pdf' | 'web' | 'md' | 'code' | anything you filter on
            store:str='store',      # chunk store
            prefix:str=None,        # tree table prefix
            emb_fn=None,            # embedder: list[str] -> vectors
            chunker=None,           # chonkie chunker (default: FastChunker via chunk_markdown)
            summarize=None,         # callable(text)->str for node summaries
            with_heading:bool=True, # embed each chunk together with its heading path
            meta:dict=None,         # arbitrary json metadata for the doc row
            force:bool=False        # re-ingest a document already present
) -> dict:
    '''Ingest one document: build its tree, chunk it per node, embed and store.

    Chunks are embedded as `heading ⏎⏎ content` but **stored** as bare content, so retrieval sees
    the context and the caller gets clean text back.'''
    import json as _json
    if isinstance(pages, str): pages = [(0, pages)]
    pages = [(p, t or '') for p, t in pages]
    g, src = self.get_tree(store, prefix), str(ifnone(source, title))
    did = doc_id(src, title)
    if first(g.docs(where=f'id={did!r}')):
        if not force: return dict(doc_id=did, title=title, skipped='already ingested; pass force=True')
        self.delete_doc(did, store, prefix)
    tree = build_tree(pages, title=title, summarize=summarize)
    g.docs.insert(dict(id=did, title=title, source=src, kind=kind,
                       pages=(max(p for p, _ in pages)+1 if pages else 0),
                       meta=_json.dumps(meta or {})), replace=True)
    chunks = _node_chunks(tree, title, did, chunker)
    counts = {}
    for c in chunks: counts[c['node_id']] = counts.get(c['node_id'], 0) + 1
    g.nodes.insert_all([dict(id=f'{did}#{nd.seq}', doc_id=did, seq=nd.seq, level=nd.level,
                             parent_id=None if nd.parent is None else f'{did}#{nd.parent}',
                             title=nd.title, page_start=nd.page_start, page_end=nd.page_end,
                             summary=nd.summary, nchunks=counts.get(f'{did}#{nd.seq}', 0))
                        for nd in tree], replace=True)
    if chunks:
        fn = emb_fn if not (emb_fn and with_heading) else (
            lambda ts, **kw: emb_fn([f"{h}\n\n{t}" if (h := heads.get(t)) else t for t in ts], **kw))
        heads = {c['content']: c['heading'] for c in chunks}
        process_content(g.store, list(chunks), embed=bool(emb_fn), emb_fn=fn)
        if self._ann_meta(store): g.store.rebuild_index()
    return dict(doc_id=did, title=title, kind=kind, nodes=len(tree), chunks=len(chunks))

@patch
def delete_doc(self:Database, did:str, store:str='store', prefix:str=None):
    'Remove a document, its nodes and its chunks; rebuild the ANN index so no keys are orphaned.'
    g = self.get_tree(store, prefix)
    g.store.delete_where(where=f'doc_id={did!r}')
    g.nodes.delete_where(where=f'doc_id={did!r}')
    g.docs.delete_where(where=f'id={did!r}')
    if self._ann_meta(store): g.store.rebuild_index()

# %% ../nbs/06_tree.ipynb #136ddc7f
DOC_EXTS = '.pdf,.md,.markdown,.txt,.rst,.ipynb'

@patch
def add_file(self:Database,
             path,                 # file to ingest
             title:str=None,       # defaults to a prettified filename
             store:str='store',
             prefix:str=None,
             **kw                  # forwarded to add_doc (emb_fn, chunker, summarize, force, ...)
) -> dict:
    'Ingest one document file. PDFs page through `pdf_parse`; everything else is one page of text.'
    p = Path(path)
    ttl = title or p.stem.replace('_',' ').replace('-',' ').strip()
    if p.suffix.lower() == '.pdf':
        from litesearch.data import pdf_parse
        pages, kind = list(enumerate(pdf_parse(str(p)))), 'pdf'
    elif p.suffix.lower() == '.ipynb':
        from litesearch.data import ipynb_parse
        pages, kind = [(0, '\n\n'.join(c['content'] for c in ipynb_parse(p)))], 'notebook'
    else:
        pages, kind = [(0, p.read_text(errors='replace'))], p.suffix.lstrip('.').lower() or 'text'
    return self.add_doc(pages, ttl, source=str(p), kind=kind, store=store, prefix=prefix, **kw)

@patch
def add_dir(self:Database,
            dir,                    # directory to walk
            types:str=DOC_EXTS,     # comma-separated extensions to ingest
            store:str='store',
            prefix:str=None,
            **kw                    # forwarded to add_doc
) -> list:
    'Ingest every document under a directory tree. Already-ingested sources are skipped, not duplicated.'
    exts = {f".{t.strip().lstrip('.')}".lower() for t in types.split(',')}
    return [self.add_file(p, store=store, prefix=prefix, **kw)
            for p in sorted(Path(dir).rglob('*')) if p.is_file() and p.suffix.lower() in exts]

# %% ../nbs/06_tree.ipynb #8dd42d34
@patch
def toc(self:Database,
        doc:str=None,           # doc id, or a substring of the title (None = every document)
        store:str='store',
        prefix:str=None,
        max_depth:int=3,        # deepest level included
        summaries:bool=True     # include node summaries
) -> list:
    'The document tree as nested dicts — titles, page ranges, summaries. No embeddings touched.'
    g = self.get_tree(store, prefix)
    docs = (g.docs(where=f'id={doc!r} or title like {"%"+doc+"%"!r}') if doc else g.docs())
    out = []
    for d in docs:
        rows = sorted(g.nodes(where=f'doc_id={d["id"]!r}'), key=lambda r: r['seq'])
        kids = {}
        for r in rows: kids.setdefault(r['parent_id'], []).append(r)
        def node(r):
            o = dict(id=r['id'], title=r['title'], level=r['level'], nchunks=r['nchunks'],
                     pages=(r['page_start'], r['page_end']))
            if summaries and r['summary']: o['summary'] = r['summary']
            if r['level'] < max_depth and (ch := kids.get(r['id'])): o['children'] = [node(c) for c in ch]
            return o
        root = first(rows, lambda r: r['parent_id'] is None)
        out.append(dict(doc_id=d['id'], title=d['title'], source=d['source'], pages=d['pages'],
                        tree=node(root) if root else None))
    return out

@patch
def breadcrumb(self:Database, node_id:str, store:str='store', prefix:str=None, sep:str=' › ') -> str:
    'The path from the document down to a node: `Book › Chapter › Section`.'
    g = self.get_tree(store, prefix)
    parts, cur, seen = [], first(g.nodes(where=f'id={node_id!r}')), set()
    while cur and cur['id'] not in seen:
        seen.add(cur['id'])
        parts.append(cur['title'])
        cur = first(g.nodes(where=f'id={cur["parent_id"]!r}')) if cur['parent_id'] else None
    return sep.join(parts[::-1])

@patch
def read(self:Database,
         node_id:str,           # 'doc#seq', as returned by toc() or sections()
         store:str='store',
         prefix:str=None,
         max_chars:int=20000,   # cap on the assembled text
         children:bool=True     # append the text of child nodes too
) -> dict:
    'One whole section — the unit an agent should read instead of guessing from fragments.'
    g = self.get_tree(store, prefix)
    nd = first(g.nodes(where=f'id={node_id!r}'))
    if not nd: return {}
    ids = [node_id]
    if children:
        frontier = [node_id]
        while frontier:
            kids = [r['id'] for r in g.nodes(where=_in('parent_id', frontier))]
            if not kids: break
            ids += kids
            frontier = kids
    rows = sorted(g.store(select='content, node_id, page', where=_in('node_id', ids)),
                  key=lambda r: (ids.index(r['node_id']) if r['node_id'] in ids else 1<<30, r['page'] or 0))
    text = '\n\n'.join(r['content'] for r in rows)[:max_chars]
    return dict(id=node_id, title=nd['title'], breadcrumb=self.breadcrumb(node_id, store, prefix),
                pages=(nd['page_start'], nd['page_end']), summary=nd['summary'],
                children=[r['id'] for r in g.nodes(where=f'parent_id={node_id!r}')], text=text)

# %% ../nbs/06_tree.ipynb #b1a334b8
_QUOTED = re.compile(r'"[^"]+"')
_NAMEY  = re.compile(r'[A-Z][a-z]{2,}|\d|_')

def adaptive_weights(q:str,      # the raw query
                     fts:list,   # the FTS leg's results
                     vec:list    # the vector leg's results
) -> tuple:
    '''`(fts_weight, vec_weight)` for RRF, from cheap signals in the query and the legs.

    Deliberately three rules, not a learned model: a quoted phrase and a rare identifier are
    literal requests, an empty FTS leg cannot vote, and everything else is a tie.'''
    if not fts: return (0.0, 1.0)
    if not vec: return (1.0, 0.0)
    w = 1.0
    if _QUOTED.search(q or ''): w += 0.6
    toks = (q or '').split()
    if toks and sum(bool(_NAMEY.search(t)) for t in toks)/len(toks) >= 0.5: w += 0.4
    return (w, 1.0)

def merge_spans(hits,            # ranked hits carrying node_id + page
                gap:int=1        # merge hits at most this many pages apart
) -> list:
    '''Collapse hits that are adjacent inside the same node into one span.

    The merged hit keeps the best rank and score of its members, so ordering is unchanged; what
    changes is that the caller gets one contiguous passage where it had two halves.'''
    out, byn = [], {}
    for i, h in enumerate(hits):
        nid = h.get('node_id')
        if not nid: out.append(h); continue
        byn.setdefault(nid, []).append((i, h))
    for nid, group in byn.items():
        group.sort(key=lambda t: (t[1].get('page') or 0, t[0]))
        cur = None
        for i, h in group:
            if cur and (h.get('page') or 0) - (cur['_page_end'] or 0) <= gap:
                cur['content'] = f"{cur['content']}\n\n{h.get('content') or ''}"
                cur['_page_end'] = h.get('page') or cur['_page_end']
                cur['_nspan'] += 1
                cur['_rrf_score'] = max(cur.get('_rrf_score', 0), h.get('_rrf_score', 0))
                cur['_rank'] = min(cur['_rank'], i)
            else:
                cur = dict(h, _page_end=h.get('page'), _nspan=1, _rank=i)
                out.append(cur)
    return sorted(out, key=lambda h: h.get('_rank', 1<<30))

@patch
def doc_search(self:Database,
               q:str,                 # query string
               emb:bytes,             # query embedding
               columns:list=None,     # extra columns (node_id, page, heading, doc_id always included)
               limit:int=10,
               store:str='store',
               prefix:str=None,
               spans:bool=True,       # merge adjacent hits inside a node
               gap:int=1,             # span merge tolerance, in pages
               adaptive:bool=True,    # weight the RRF legs by query shape
               rrf_k:int=60,
               **kw                   # forwarded to Database.search
) -> list:
    'Hybrid search over a node-aware store: adaptive RRF, span merging, and a breadcrumb per hit.'
    cols = list(dict.fromkeys((columns or ['content']) + ['node_id','page','heading','doc_id','rowid']))
    base = self.search(q, emb, columns=cols, limit=max(limit*3, 30), table_name=store, rrf=False, **kw)
    if not base: return []
    fts, vec = base['fts'], base['vec']
    wf, wv = adaptive_weights(q, fts, vec) if adaptive else (1.0, 1.0)
    hits = _wrrf(fts, vec, wf, wv, rrf_k, limit*(3 if spans else 1))
    if spans: hits = merge_spans(hits, gap)
    for h in hits[:limit]: h['breadcrumb'] = h.get('heading') or self.breadcrumb(h.get('node_id') or '', store, prefix)
    return hits[:limit]

def _wrrf(fts, vec, wf=1.0, wv=1.0, k=60, limit=50, id_key='rowid'):
    'Weighted RRF over the two legs. `rrf_merge` with a thumb on the scale.'
    scores = {}
    for lst, w in ((fts, wf), (vec, wv)):
        for rank, row in enumerate(lst or []):
            rid = row.get(id_key, id(row))
            if rid in scores: scores[rid]['_rrf_score'] += w/(k+rank)
            else: scores[rid] = dict(row, _rrf_score=w/(k+rank))
    return sorted(scores.values(), key=lambda r: -r['_rrf_score'])[:limit]

@patch
def sections(self:Database,
             q:str,               # query string
             emb:bytes,           # query embedding
             limit:int=5,         # sections to return
             per:int=3,           # snippets kept per section
             store:str='store',
             prefix:str=None,
             fanout:int=8,        # chunk hits gathered before rolling up
             **kw                 # forwarded to doc_search
) -> list:
    '''Ranked *sections*, not chunks: hits grouped by node, scored by their summed RRF mass.

    Five weak hits inside one chapter beat one strong hit in an unrelated appendix — which is the
    judgement a reader makes and a top-k chunk list cannot. Each result carries its `read` handle.'''
    hits = self.doc_search(q, emb, limit=max(limit*fanout, 20), store=store, prefix=prefix, spans=False, **kw)
    g, agg = self.get_tree(store, prefix), {}
    for h in hits:
        nid = h.get('node_id')
        if not nid: continue
        a = agg.setdefault(nid, dict(node_id=nid, score=0.0, snippets=[], pages=[]))
        a['score'] += h.get('_rrf_score', 0.0)
        if len(a['snippets']) < per: a['snippets'].append((h.get('content') or '')[:400])
        if h.get('page') is not None: a['pages'].append(h['page'])
    if not agg: return []
    nodes = {r['id']: r for r in g.nodes(where=_in('id', list(agg)))}
    out = []
    for nid, a in sorted(agg.items(), key=lambda kv: -kv[1]['score'])[:limit]:
        nd = nodes.get(nid) or {}
        out.append(dict(node_id=nid, title=nd.get('title', ''), score=a['score'],
                        breadcrumb=self.breadcrumb(nid, store, prefix), summary=nd.get('summary', ''),
                        pages=(min(a['pages']) if a['pages'] else nd.get('page_start'),
                               max(a['pages']) if a['pages'] else nd.get('page_end')),
                        nchunks=nd.get('nchunks', 0), snippets=a['snippets'],
                        read=f'read({nid!r})'))
    return out
