# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_utils.ipynb.

# %% auto #0
__all__ = ['static_code_embedder', 'static_embedder', 'hash_embed', 'doc_encoder', 'query_encoder']

# %% ../nbs/03_utils.ipynb #44d1b5a9be20
import re, zlib
from functools import cache
import numpy as np
from fastcore.all import L, bind
from model2vec import StaticModel

# %% ../nbs/03_utils.ipynb #61f6375afd2e
@cache
def static_embedder(model_nm='minishlab/potion-multilingual-128M'):
    'A model2vec model, shared per name. potion-multilingual-128M is ~500MB, so every caller loading its own hurts.'
    return StaticModel.from_pretrained(model_nm, force_download=False)

static_code_embedder = bind(static_embedder, model_nm='minishlab/potion-code-16M-v2')

# %% ../nbs/03_utils.ipynb #e6cef76dcf5e
_WS = re.compile(r'\s+')

def hash_embed(texts,           # strings to embed
               ndim:int=256,    # output dimensions
               ngram=(3,5),     # character n-gram range
               dtype=np.float16):
    'Char-n-gram hashing: no model, no download, same vectors every run. Lexical only.'
    lo, hi = ngram
    txts = list(L(texts))
    out, crc = np.zeros((len(txts), ndim), dtype=np.float32), zlib.crc32
    for i, t in enumerate(txts):
        s = ' ' + _WS.sub(' ', (t or '').lower().strip()) + ' '
        b = s.encode()
        # n-grams count characters, so the byte path is only safe where encoding preserves length
        if len(b) == len(s): h = [crc(b[j:j+n]) % ndim for n in range(lo, hi+1) for j in range(len(b)-n+1)]
        else:                h = [crc(s[j:j+n].encode()) % ndim for n in range(lo, hi+1) for j in range(len(s)-n+1)]
        if h: out[i] = np.bincount(h, minlength=ndim)
    out /= np.clip(np.linalg.norm(out, axis=1, keepdims=True), 1e-12, None)
    return out.astype(dtype)

# %% ../nbs/03_utils.ipynb #e900658c222b
def _side(embedder, meth):
    'The named encode method, else the plain one.'
    f = getattr(embedder, meth, None)
    return f or (lambda txts, **kw: embedder.encode(L(txts)))

def doc_encoder(embedder):   return _side(embedder, 'encode_document')
def query_encoder(embedder): return _side(embedder, 'encode_query')
