# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/thedu',
                'doc_host': 'https://Karthik777.github.io',
                'git_url': 'https://github.com/Karthik777/thedu',
                'lib_path': 'thedu'},
  'syms': {'thedu.core': {'thedu.core.foo': ('core.html#foo', 'thedu/core.py')}}}
